#!/usr/bin/env -S deno run --allow-read --allow-write
// gen-v8-gc-table.ts -- write `src/Litedoc4/Global/V8GcTable.lean` from V8's
// own `\p{Z}\p{C}`.
//
// The frozen prototype's `autolinkTokens` splits code spans on V8's
// `/[\p{Z}\p{C}]/u`; the renderer — and therefore `Litedoc4.Md.Gc` — splits on
// UnicodeBasic's `Z | C`, and the two disagree on 4,803 code points, all in one
// direction (measured 2026-08-12 → benchmarks/results/m2b-v6-token-separators.json).
// The map delta's tokeniser splits on the **union**, which is what this table
// is for; it is generated because the alternative is a hand-copied UCD.
//
// This is *a* V8's answer, not *the* V8's: the set is pinned to the runtime
// recorded in the generated header. Every code point the two tables disagree on
// is unassigned in the older of the two UCDs, so a different V8 moves this
// table only over code points no text can contain a meaning for.
//
// The generated module holds the table and nothing else. Splitting it out of
// `Litedoc4.Global.V8Gc` rather than emitting that whole file is what keeps a
// hand edit and a regeneration from being the same event: the file this writes
// is overwritten wholesale, and prose put in it is lost without a word. That is
// not hypothetical — the doc comments of the Rust table this script used to
// write were rewritten by hand on 2026-08-24 and `--check` went red and stayed
// red, unnoticed, because no gate ran it (measured 2026-08-31 →
// benchmarks/results/unicode-table-regenerators-2026-08-31.txt §2). Merge the
// two files back together only if the prose ever becomes derivable too.
//
// npm/node are broken in this environment; this must run under deno.
//
// usage:
//   deno run --allow-read --allow-write \
//     tools/oracle/gen-v8-gc-table.ts
//   ... --check    fail if the committed .lean is not what this produces.
//                  `tools/v8-gc-table-gate.sh` is what runs it.

const OUT = new URL("../../src/Litedoc4/Global/V8GcTable.lean", import.meta.url);
const check = Deno.args.includes("--check");

const ZC = /[\p{Z}\p{C}]/u;
const ranges: [number, number][] = [];
let members = 0;
for (let cp = 0; cp <= 0x10ffff; cp++) {
  if (!ZC.test(String.fromCodePoint(cp))) continue;
  members++;
  const last = ranges[ranges.length - 1];
  if (last && last[1] + 1 === cp) last[1] = cp;
  else ranges.push([cp, cp]);
}

// Not the Rust encoding: `Litedoc4.gcRanges` reads one string literal, because
// 737 array elements are elaborated one by one and a string is one token.
const hex = (cp: number) => cp.toString(16).toUpperCase();
const table = ranges.map(([lo, hi]) => `${hex(lo)}-${hex(hi)}`).join(",");

const source = `/-
Holds the answers of V8 (BSD-3-Clause, Copyright 2006-2011 the V8 project
authors). See this repository's NOTICE.

**Generated by \`tools/oracle/gen-v8-gc-table.ts\`; do not edit.** The ranges are
the answers of the V8 in \`deno ${Deno.version.deno}\` (V8 \`${Deno.version.v8}\`),
enumerated over every code point. Regenerate with the script above; \`--check\`
fails if this file is not what it produces, and \`tools/v8-gc-table-gate.sh\` runs
that check on every push.

What may and may not use the table is said in \`Litedoc4.Global.V8Gc\`, which
imports this module. Prose written here does not survive the next run.
-/

namespace Litedoc4

/-- V8's \`\\p{Z}\\p{C}\` as ${ranges.length} inclusive \`lo-hi\` hex pairs, in order —
${members} code points, in the encoding \`Litedoc4.gcRanges\` reads. Surrogates are
members (they are \`Cs\`, inside \`C\`); no \`Char\` can hold one anyway. -/
def v8ZcTable : String :=
  "${table}"

end Litedoc4
`;

/** The one line a reader gets when `--check` is red: what moved, not that something did. */
function whatMoved(committed: string): string {
  const at = (haystack: string) => {
    const match = haystack.match(/^ {2}"(.*)"$/m);
    return match ? match[1] : null;
  };
  const theirs = at(committed);
  if (theirs === null) return "it holds no `  \"…\"` table line at all";
  if (theirs !== table) {
    let i = 0;
    while (i < theirs.length && i < table.length && theirs[i] === table[i]) i++;
    return (
      `the table moved — this V8 says ${ranges.length} ranges / ${table.length} chars, ` +
      `the file says ${theirs.split(",").length} / ${theirs.length}, ` +
      `first difference at character ${i} (${JSON.stringify(theirs.slice(i, i + 24))} ` +
      `where this V8 has ${JSON.stringify(table.slice(i, i + 24))})`
    );
  }
  const mine = source.split("\n");
  const yours = committed.split("\n");
  let line = 0;
  while (line < mine.length && line < yours.length && mine[line] === yours[line]) line++;
  return (
    `the table is identical (${ranges.length} ranges / ${table.length} chars); ` +
    `the surrounding text differs first at line ${line + 1} ` +
    `(${JSON.stringify(yours[line] ?? "<end of file>")})`
  );
}

const path = OUT.pathname;
if (check) {
  const committed = await Deno.readTextFile(OUT).catch(() => null);
  if (committed === null) {
    console.error(`${path} is not there; run this script without --check to write it`);
    Deno.exit(1);
  }
  if (committed !== source) {
    console.error(`${path}: ${whatMoved(committed)}`);
    Deno.exit(1);
  }
  console.error(`${path} is current (${ranges.length} ranges, ${members} code points)`);
} else {
  await Deno.writeTextFile(OUT, source);
  console.error(`${ranges.length} ranges / ${members} code points -> ${path}`);
}
