#!/usr/bin/env -S deno run --allow-read --allow-write
// gen-v8-gc-table.ts -- write `src/v8_gc.rs` from V8's own `\p{Z}\p{C}`.
//
// The frozen prototype's `autolinkTokens` splits code spans on V8's
// `/[\p{Z}\p{C}]/u`; the renderer — and therefore `litedoc4_md::gc` — splits on
// UnicodeBasic's `Z | C`, and the two disagree on 4,803 code points, all in one
// direction (measured 2026-08-12 → benchmarks/results/m2b-v6-token-separators.json).
// The map delta's tokeniser splits on the **union**, which is what this table
// is for; it is generated because the alternative is a hand-copied UCD.
//
// This is *a* V8's answer, not *the* V8's: the set is pinned to the runtime
// recorded in the generated header. Every code point the two tables disagree on
// is unassigned in the older of the two UCDs, so a different V8 moves this
// table only over code points no text can contain a meaning for.
//
// npm/node are broken in this environment; this must run under deno.
//
// usage:
//   deno run --allow-read --allow-write \
//     crates/litedoc4-global/tests/oracle/gen-v8-gc-table.ts
//   ... --check    fail if the committed src/v8_gc.rs is not what this produces

const OUT = new URL("../../src/v8_gc.rs", import.meta.url);
const check = Deno.args.includes("--check");

const ZC = /[\p{Z}\p{C}]/u;
const ranges: [number, number][] = [];
let members = 0;
for (let cp = 0; cp <= 0x10ffff; cp++) {
  if (!ZC.test(String.fromCodePoint(cp))) continue;
  members++;
  const last = ranges[ranges.length - 1];
  if (last && last[1] + 1 === cp) last[1] = cp;
  else ranges.push([cp, cp]);
}

const hex = (cp: number) => `0x${cp.toString(16).toUpperCase()}`;
const table =
  `static Z_C: [(u32, u32); ${ranges.length}] = [\n` +
  ranges.map(([lo, hi]) => `    (${hex(lo)}, ${hex(hi)}),`).join("\n") +
  "\n];";

const source = `//! Holds the answers of V8 (BSD-3-Clause, Copyright 2006-2011 the V8 project
//! authors). See this repository's NOTICE.
//!
//! V8's \`\\p{Z}\\p{C}\` — the separator set the **frozen prototype** tokenises
//! code spans on.
//!
//! **Generated by \`tests/oracle/gen-v8-gc-table.ts\`; do not edit.** The ranges
//! are the answers of the V8 in \`deno ${Deno.version.deno}\` (V8
//! \`${Deno.version.v8}\`), enumerated over every code point. Regenerate with the
//! script above; \`--check\` fails if this file is not what it produces.
//!
//! # Not the renderer's table, and not a general-purpose one
//!
//! [\`crate::facts::autolink_tokens\`] splits on this set **united with**
//! [\`litedoc4_md::gc::is_z_c\`], which is UnicodeBasic's answer and the one the
//! renderer's \`autoLinkInline\` uses. Nothing may use this table alone, and
//! nothing that produces bytes may use it at all: the renderer's split is what
//! doc-gen4's output is compared against, and it is UnicodeBasic's.
//!
//! Surrogates are members here (they are \`Cs\`, inside \`C\`), as they are in
//! \`litedoc4_md::gc\`; no \`char\` can hold one anyway.

/// \`\\p{Z}\\p{C}\` as ${ranges.length} inclusive code point ranges, in order —
/// ${members} code points.
${table}

fn contains(table: &[(u32, u32)], c: char) -> bool {
    let cp = c as u32;
    table
        .binary_search_by(|&(lo, hi)| {
            if hi < cp {
                std::cmp::Ordering::Less
            } else if lo > cp {
                std::cmp::Ordering::Greater
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

/// \`c\` matches V8's \`/[\\p{Z}\\p{C}]/u\`.
///
/// Half of what [\`crate::facts::autolink_tokens\`] splits on. See the module
/// docs: this is never the whole answer.
#[must_use]
pub fn is_z_c(c: char) -> bool {
    contains(&Z_C, c)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_sorted_and_disjoint() {
        for pair in Z_C.windows(2) {
            assert!(pair[0].0 <= pair[0].1, "{:?} is empty", pair[0]);
            assert!(
                pair[0].1 + 1 < pair[1].0,
                "{:?} and {:?} touch",
                pair[0],
                pair[1]
            );
        }
    }

    /// The separators and the punctuation, the same spot checks
    /// \`litedoc4_md::gc\` makes: a tokeniser that splits on \`.\` would offer
    /// every component of every name and re-render half the package.
    #[test]
    fn the_category_is_the_one_named() {
        for c in [' ', '\\t', '\\n', '\\u{0}', '\\u{a0}', '\\u{ad}', '\\u{2028}'] {
            assert!(is_z_c(c), "U+{:04X}", c as u32);
        }
        for c in ['.', '_', '\\'', '!', '?', '-', ':'] {
            assert!(!is_z_c(c), "U+{:04X}", c as u32);
        }
        for c in ['a', 'α', '→', '\\u{1D4A9}'] {
            assert!(!is_z_c(c), "U+{:04X}", c as u32);
        }
    }
}
`;

if (check) {
  const committed = await Deno.readTextFile(OUT);
  if (committed !== source) {
    console.error(`${OUT.pathname} is not what this script produces`);
    Deno.exit(1);
  }
  console.error(`${OUT.pathname} is current (${ranges.length} ranges, ${members} code points)`);
} else {
  await Deno.writeTextFile(OUT, source);
  console.error(`${ranges.length} ranges / ${members} code points -> ${OUT.pathname}`);
}
