//! The two escapes that reach the generated bytes. Both transcribe a Lean
//! function rather than a general convention, and both differ from the obvious
//! Rust default:
//!
//! - [`escape_html`] is `Html.escape` (doc-gen4's `ToHtmlFormat.lean`), which
//!   covers `& < > "` and nothing else. Every HTML-escaping crate also escapes
//!   `'`, and one of those extra characters in a page is one byte of mismatch.
//!   It lives in `litedoc4-md` and is re-exported rather than copied so that
//!   the docstring renderer and this crate cannot drift apart.
//! - [`lean_quote`] is Lean core's `String.quote`, which is *not*
//!   `format!("{:?}")`: it emits `\xNN` for the C0 controls and U+007F, and
//!   leaves everything else — including `\r` and every non-ASCII scalar — as
//!   the literal character.

use std::fmt::Write as _;

pub use litedoc4_md::{escape_html, escape_html_into};

/// Lean's `String.quote`, quotation marks included.
pub fn lean_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    lean_quote_into(&mut out, s);
    out
}

pub fn lean_quote_into(out: &mut String, s: &str) {
    out.push('"');
    for c in s.chars() {
        match c {
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            // `Char.quoteCore`'s catch-all: `\r` lands here rather than on an
            // `\r` escape, and the hex is lower case, zero-padded to two.
            _ if (c as u32) <= 31 || c as u32 == 127 => {
                let _ = write!(out, "\\x{:02x}", c as u32);
            }
            _ => out.push(c),
        }
    }
    out.push('"');
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quote_uses_lean_escapes() {
        assert_eq!(lean_quote("a\nb\tc\\d\"e"), r#""a\nb\tc\\d\"e""#);
        assert_eq!(lean_quote("\r"), r#""\x0d""#);
        assert_eq!(lean_quote("\u{0}\u{1f}\u{7f}"), r#""\x00\x1f\x7f""#);
        // U+0080 is a control in Unicode's sense but not in Lean's.
        assert_eq!(lean_quote("\u{80}"), "\"\u{80}\"");
        assert_eq!(lean_quote(""), "\"\"");
        assert_eq!(lean_quote("./"), "\"./\"");
    }
}
