//! Reading the dependency closure's `name -> module` map (`.lidx`).
//!
//! Ported from `experiments/stage7d/render.ts` (2067-2084), which is frozen.
//!
//! # Why the reader lives in the renderer
//!
//! Because the renderer is the only consumer. doc-gen4 resolves a docstring
//! autolink through `env.name2ModIdx`, which it has because it holds the whole
//! environment; this renderer holds none of it, so the map is an input. Nothing
//! else in the pipeline opens the file.
//!
//! **The producer moves; the format does not.** Today the map is derived from a
//! doc-gen4 site's `declarations/declaration-data.bmp`
//! (`experiments/stage7d/build-link-index.ts`), and M5 replaces that with a
//! scan of the environment the extractor already has loaded (plan 決定 4 / 決定
//! 5). That swap is confined to the writing side: what the renderer reads is
//! still a `.lidx`, so this module does not move with it.
//!
//! Passing the map is **not optional in the product**. The prototype's
//! full-generation path never passed `--link-index`, and the difference is 150
//! of 432 pages (34.7%) — plan 決定 4, 実測.
//!
//! # Format
//!
//! ```text
//! #lidx2                       format marker; any `#` line is ignored
//! @Mathlib.Order.Basic         a module name that is a link target in its own right
//! Mathlib.Order.Basic          a group header: the module the following names live in
//! \tMathlib.Order.le_refl\t67\t67  one declaration, and its first and last source line
//! \t<a name with no range>     one declaration the extractor had no range for
//! ```
//!
//! Line-oriented, split on `\n` only, first byte decides. Empty lines are
//! ignored, and an unknown leading byte is a group header — the prototype's
//! parser has no error path and neither does this one, so a garbled file
//! produces a map with garbage in it rather than a failure. Keeping that is
//! deliberate: the file is generated by this same toolchain, and diverging here
//! would be a behaviour change smuggled in with a port.
//!
//! **That rule extends to the range** (M7-a): a declaration line with no extra
//! fields, or with fields that are not two numbers, is a declaration **with no
//! range** — never an error. Both are real: the extractor writes one field when
//! `findDeclarationRanges?` has nothing, and every `.lidx` written before M7-a
//! has one field on every line. A missing range costs the link its `#L…-L…`
//! anchor and nothing else, so failing here would trade a
//! degraded link for no site.

use std::collections::{HashMap, HashSet};
use std::num::NonZeroU32;
use std::path::Path;

/// The marker the current writer puts on the first line.
///
/// **Not enforced, and both spellings are read** — the parser ignores every `#`
/// line, so this is documentation rather than a gate. What the number says is
/// how many fields a declaration line can have: `#lidx1` is name-only (the
/// prototype's, and M5-a's), `#lidx2` adds the two line numbers (M7-a). A
/// `#lidx1` file still parses, and every one of its entries simply has no range
/// — which is the same answer this parser gives for a `#lidx2` entry whose
/// declaration had none.
pub const FORMAT_MARKER: &str = "#lidx2";

/// What one declaration line says: which group it was under, and where its
/// source is.
///
/// 12 bytes, and that is the point: the target package's map is **255,975** of
/// these 【実測 2026-08-16】. The range is `Option<(NonZeroU32, u32)>` rather
/// than two `Option`s or a `String` because Lean's `Position.line` is 1-based,
/// so the niche is free — `None` costs no extra word, and a `String` per range
/// would be 24 bytes of header before a single digit of it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct Entry {
    module: u32,
    range: Option<(NonZeroU32, u32)>,
}

/// A `name -> (defining module, source line range)` map over a whole dependency
/// closure.
///
/// Module names are interned: the target package's map is 255,975 entries over
/// 5,693 modules 【実測 2026-08-16, M5-a's writer】 — 258,760 over 5,775 when it
/// was still built from a doc-gen4 site's `.bmp` 【実測, 段階 7c】 — so storing
/// the module name per entry would be about 40x the text it stands for.
#[derive(Debug, Default)]
pub struct LinkIndex {
    /// Group headers, in order of first appearance. Index 0 is the empty
    /// module, which entries before the first header fall into — as they do in
    /// the prototype, where the current module starts as `""`.
    modules: Vec<String>,
    module_ids: HashMap<String, u32>,
    names: HashMap<String, Entry>,
    known_modules: HashSet<String>,
}

impl LinkIndex {
    /// Parses the file's text.
    pub fn parse(text: &str) -> Self {
        let mut index = Self {
            modules: vec![String::new()],
            ..Self::default()
        };
        let mut current = 0;
        for line in text.split('\n') {
            match line.as_bytes().first() {
                // A declaration in the current group. A repeated name takes the
                // later entry whole — module *and* range — as
                // `Map.prototype.set` does.
                Some(b'\t') => {
                    let (name, range) = split_entry(&line[1..]);
                    index.names.insert(
                        name.to_owned(),
                        Entry {
                            module: current,
                            range,
                        },
                    );
                }
                Some(b'@') => {
                    index.known_modules.insert(line[1..].to_owned());
                }
                // Two different nothings, kept apart on purpose: `#` is a
                // comment line the format defines, `None` is a blank line.
                #[expect(clippy::match_same_arms, reason = "distinct reasons to skip")]
                Some(b'#') => {}
                Some(_) => current = index.intern(line),
                None => {}
            }
        }
        index
    }

    /// Reads and parses a `.lidx` file.
    pub fn read(path: impl AsRef<Path>) -> std::io::Result<Self> {
        Ok(Self::parse(&std::fs::read_to_string(path)?))
    }

    fn intern(&mut self, module: &str) -> u32 {
        if let Some(&id) = self.module_ids.get(module) {
            return id;
        }
        let id = u32::try_from(self.modules.len()).expect("a .lidx has fewer than 4G modules");
        self.modules.push(module.to_owned());
        self.module_ids.insert(module.to_owned(), id);
        id
    }

    /// The module a declaration is defined in, if the map knows the name.
    pub fn module_of(&self, name: &str) -> Option<&str> {
        self.names
            .get(name)
            .map(|entry| self.modules[entry.module as usize].as_str())
    }

    /// The declaration's first and last source line, as
    /// [`crate::ExternalLinks::url_for`] wants them.
    ///
    /// `None` covers two different things on purpose — a name the map does not
    /// hold, and a name it holds with no range — because the caller does the
    /// same thing with both: build the URL without an anchor if the module
    /// resolves at all. Telling them apart is [`LinkIndex::module_of`]'s job.
    pub fn range_of(&self, name: &str) -> Option<(u32, u32)> {
        let entry = self.names.get(name)?;
        entry.range.map(|(from, to)| (from.get(), to))
    }

    /// Every declaration the map holds, in no particular order — the shape a
    /// whole-map audit wants (M7-a's gate walks it against doc-gen4's own
    /// per-declaration URLs).
    pub fn names(&self) -> impl ExactSizeIterator<Item = &str> {
        self.names.keys().map(String::as_str)
    }

    /// Entries that carry a source range. The complement of it against
    /// [`LinkIndex::len`] is the set whose links lose their line anchor, which
    /// M7-a measures rather than assumes.
    pub fn ranged_len(&self) -> usize {
        self.names
            .values()
            .filter(|entry| entry.range.is_some())
            .count()
    }

    /// Whether a name is a module that is a link target in its own right — the
    /// `@` section, which doc-gen4 checks (`res.moduleNames.contains`) before
    /// falling back to the module-local search.
    pub fn is_known_module(&self, name: &str) -> bool {
        self.known_modules.contains(name)
    }

    /// The `@` section, for merging into the renderer's own set of modules.
    pub fn known_modules(&self) -> impl ExactSizeIterator<Item = &str> {
        self.known_modules.iter().map(String::as_str)
    }

    /// Declarations in the map.
    pub fn len(&self) -> usize {
        self.names.len()
    }

    pub fn is_empty(&self) -> bool {
        self.names.is_empty()
    }

    /// Distinct group headers, i.e. modules that define at least one of those
    /// declarations. Not the same number as [`LinkIndex::known_modules`]: the
    /// `@` section also lists modules that define nothing.
    pub fn module_count(&self) -> usize {
        self.modules.len() - 1
    }
}

/// One declaration line, minus its leading tab: the name, then the range when
/// the two extra fields are there and are numbers.
///
/// Any other shape is "no range" (see the module heading): one field is a
/// pre-M7-a file or a declaration the extractor had no range for, and a field
/// that will not parse is a file this reader does not understand — neither is
/// worth losing the entry over. Fields past the second are ignored, so a later
/// writer can add one without this reader having to be taught about it first.
fn split_entry(rest: &str) -> (&str, Option<(NonZeroU32, u32)>) {
    let mut fields = rest.split('\t');
    // `split` always yields at least one item, so the name is the whole line
    // when there is no tab in it.
    let name = fields.next().unwrap_or(rest);
    let range = match (fields.next(), fields.next()) {
        (Some(from), Some(to)) => from.parse::<NonZeroU32>().ok().zip(to.parse::<u32>().ok()),
        _ => None,
    };
    (name, range)
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "#lidx2\n\
        @Mathlib.Order.Basic\n\
        @Mathlib.Init\n\
        Mathlib.Order.Basic\n\
        \tMathlib.Order.le_refl\t67\t67\n\
        \tMathlib.Order.le_trans\t70\t74\n\
        Mathlib.Data.Nat\n\
        \tNat.succ\n";

    #[test]
    fn reads_groups_and_module_names() {
        let index = LinkIndex::parse(SAMPLE);
        assert_eq!(index.len(), 3);
        assert_eq!(index.module_count(), 2);
        assert_eq!(index.known_modules().len(), 2);
        assert_eq!(
            index.module_of("Mathlib.Order.le_refl"),
            Some("Mathlib.Order.Basic")
        );
        assert_eq!(index.module_of("Nat.succ"), Some("Mathlib.Data.Nat"));
        assert_eq!(index.module_of("Nat.pred"), None);
        assert!(index.is_known_module("Mathlib.Init"));
        // A group header is not automatically an `@` entry.
        assert!(!index.is_known_module("Mathlib.Data.Nat"));
    }

    /// The two shapes of a declaration line, side by side: the range is an
    /// extra field, and its absence is an entry like any other.
    #[test]
    fn a_declaration_carries_its_line_range_when_the_writer_had_one() {
        let index = LinkIndex::parse(SAMPLE);
        assert_eq!(index.range_of("Mathlib.Order.le_refl"), Some((67, 67)));
        assert_eq!(index.range_of("Mathlib.Order.le_trans"), Some((70, 74)));
        // Present, and with no range: the entry is still here, and still
        // resolves to its module. That is the whole point of keeping it
        // (§M7「行範囲が取れない宣言でリンクを消さない」).
        assert_eq!(index.range_of("Nat.succ"), None);
        assert_eq!(index.module_of("Nat.succ"), Some("Mathlib.Data.Nat"));
        // Absent altogether — the same `None`, told apart by `module_of`.
        assert_eq!(index.range_of("Nat.pred"), None);
        assert_eq!(index.module_of("Nat.pred"), None);
        assert_eq!(index.ranged_len(), 2);
    }

    /// A `#lidx1` file — the prototype's, and M5-a's — still parses, and every
    /// entry in it has no range. The marker is documentation; nothing branches
    /// on it.
    #[test]
    fn a_file_from_before_the_range_still_reads() {
        let index = LinkIndex::parse(
            "#lidx1\n\
             @Mathlib.Init\n\
             Mathlib.Order.Basic\n\
             \tMathlib.Order.le_refl\n\
             \tMathlib.Order.le_trans\n",
        );
        assert_eq!(index.len(), 2);
        assert_eq!(index.ranged_len(), 0);
        assert_eq!(
            index.module_of("Mathlib.Order.le_refl"),
            Some("Mathlib.Order.Basic")
        );
        assert_eq!(index.range_of("Mathlib.Order.le_refl"), None);
    }

    /// A field that is not two numbers means "no range", never a failure. The
    /// entry survives every one of these, because a link without an anchor
    /// beats no link.
    #[test]
    fn a_malformed_range_costs_the_range_and_not_the_entry() {
        let index = LinkIndex::parse(
            "M\n\
             \tA.half\t67\n\
             \tA.words\tsixty\tseven\n\
             \tA.empty\t\t\n\
             \tA.negative\t-3\t7\n\
             \tA.huge\t99999999999999999999\t7\n\
             \tA.zero\t0\t0\n\
             \tA.spaced\t 67\t67 \n\
             \tA.extra\t67\t70\tsomething-new\n",
        );
        assert_eq!(index.len(), 8);
        for name in [
            "A.half",
            "A.words",
            "A.empty",
            "A.negative",
            "A.huge",
            // 0 is not a line: Lean's `Position.line` is 1-based, which is what
            // makes `None` free in the storage.
            "A.zero",
            "A.spaced",
        ] {
            assert_eq!(index.module_of(name), Some("M"), "{name} kept its module");
            assert_eq!(index.range_of(name), None, "{name} has no range");
        }
        // A field this reader does not know about is ignored rather than
        // treated as garbage — a later writer can add one.
        assert_eq!(index.range_of("A.extra"), Some((67, 70)));
        assert_eq!(index.ranged_len(), 1);
    }

    /// 12 bytes per entry on top of the name, not a `String` per range: the
    /// real file is 258,760 of them.
    #[test]
    fn an_entry_is_twelve_bytes() {
        assert_eq!(
            size_of::<Entry>(),
            12,
            "a 1-based line number leaves a niche, so `Option` costs nothing"
        );
    }

    #[test]
    fn empty_input_is_an_empty_map() {
        for text in ["", "\n", "#lidx1\n", "#lidx2\n"] {
            let index = LinkIndex::parse(text);
            assert!(index.is_empty());
            assert_eq!(index.module_count(), 0);
        }
    }

    /// Names carry the same characters the rest of the port has to survive.
    #[test]
    fn non_ascii_names_round_trip() {
        let index = LinkIndex::parse("M.𝒜\n\tFoo.𝓧'\n\tℕ.add\n");
        assert_eq!(index.module_of("Foo.𝓧'"), Some("M.𝒜"));
        assert_eq!(index.module_of("ℕ.add"), Some("M.𝒜"));
    }

    /// The prototype's parser has no error path; a missing marker or a stray
    /// blank line changes nothing.
    #[test]
    fn blank_lines_and_a_missing_marker_are_tolerated() {
        let index = LinkIndex::parse("M\n\n\tA\n\n@N\n");
        assert_eq!(index.module_of("A"), Some("M"));
        assert!(index.is_known_module("N"));
        assert_eq!(index.module_count(), 1);
    }

    /// A repeated header is one module, and a repeated name takes the later
    /// one, as `Map.prototype.set` does.
    #[test]
    fn repeats_follow_the_prototype() {
        let index = LinkIndex::parse("M\n\tA\nN\n\tA\nM\n\tB\n");
        assert_eq!(index.module_count(), 2);
        assert_eq!(index.module_of("A"), Some("N"));
        assert_eq!(index.module_of("B"), Some("M"));
    }

    /// The range goes with the module: a repeated name takes the later entry
    /// whole, so the two halves can never come from different lines.
    #[test]
    fn a_repeated_name_takes_the_later_entrys_range() {
        let index = LinkIndex::parse("M\n\tA\t1\t2\nN\n\tA\t30\t40\n");
        assert_eq!(index.module_of("A"), Some("N"));
        assert_eq!(index.range_of("A"), Some((30, 40)));
        // …including when the later one has none: the anchor is dropped rather
        // than carried over from a module the name no longer belongs to.
        let overwritten = LinkIndex::parse("M\n\tA\t1\t2\nN\n\tA\n");
        assert_eq!(overwritten.module_of("A"), Some("N"));
        assert_eq!(overwritten.range_of("A"), None);
    }

    /// An entry before any header belongs to the empty module rather than to
    /// nothing, which is what the prototype's `let module = ""` produces.
    #[test]
    fn an_entry_before_the_first_header_has_an_empty_module() {
        let index = LinkIndex::parse("#lidx1\n\tA\nM\n\tB\n");
        assert_eq!(index.module_of("A"), Some(""));
        assert_eq!(index.module_count(), 1);
    }
}
