//! Every answer in this file was produced by the TypeScript prototype, not by
//! the Rust code it checks.
//!
//! `tests/data/autolink-expected.json` was generated by
//! `tests/oracle/gen-autolink-expected.ts`, which sliced `renderDocString` and
//! its helpers out of the frozen prototype and ran them against the **real** IR
//! and the **real** dependency map.
//!
//! **The fixture is a frozen value: HEAD has no way to regenerate it.** The
//! generator and the prototype it drove were removed with `experiments/` on
//! 2026-08-16 and exist only at tag `experiments-frozen`.
//!
//! # Why the prototype and not doc-gen4
//!
//! The earlier steps of M1-c compared against doc-gen4 itself, which was
//! possible because `nameToLink?` reads nothing but `SiteContext.result` and an
//! empty `AnalyzerResult` makes every lookup miss. That is exactly the
//! configuration this step is undoing, so the same oracle would answer
//! `NoLinks` to every question.
//!
//! It would also be the wrong function. doc-gen4's `nameToLink?` and the
//! prototype's `nameToLink` are not the same: doc-gen4 has an environment and
//! uses `isPrivateName`, `name2ModIdx`, an automatically-generated-eliminator
//! fallback and `sameEnd`; the prototype has no environment and uses a
//! `_private.` prefix test, `known` + `linkIndex`, `knownModules` and a
//! component-suffix scan. **The prototype is the one that scores 439/439**, so
//! it is the one this port has to agree with (plan §5).
//!
//! # The two halves
//!
//! - The committed fixture is self-contained. Each case carries the three
//!   sources of its own world reduced to the names it looks up, and the
//!   generator proves the reduction is faithful by re-rendering with it.
//! - [`the_whole_corpus_matches_the_prototype`] runs all 4,858 docstrings
//!   against the real IR and the real `.lidx`, which is the only place the
//!   *building* of the name index is exercised on real data. It is `#[ignore]`d
//!   and needs `LITEDOC4_AUTOLINK_FULL` to point at the generator's `--full`
//!   output.
//!
//! # The one branch this port answers differently on purpose (M8, gate UI-2)
//!
//! A **source path** — `` `EPI/Stam/ToBridge.lean` `` — is a link the prototype
//! and doc-gen4 both build without consulting anything: the path is read as
//! relative to the repository root and the extension is swapped. The target
//! package writes those paths relative to the *module*, so the page named does
//! not exist, and 160 of the site's 32,868 internal links were dangling
//! 【実測 2026-08-16】. This port asks [`NameIndex::module_for_source_path`]
//! instead.
//!
//! Both comparisons below therefore run the prototype's answer through that
//! question before comparing ([`Case::with_source_paths_resolved`]) and pin how
//! many anchors it moved. Everything else stays byte for byte, so a second
//! divergence still fails.

#![expect(
    clippy::case_sensitive_file_extension_comparisons,
    reason = "reproduces the prototype's `endsWith`, which is the thing being checked"
)]
#![expect(
    clippy::format_push_string,
    reason = "in the escape helper, which runs only once an assertion has already failed"
)]

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::path::PathBuf;

use litedoc4_ir::IrTree;
use litedoc4_md::LinkResolver;
use litedoc4_render::{
    ExternalLinks, LinkIndex, NameIndex, PageLinks, module_decl_names, page_root,
};
use serde::Deserialize;

mod common;
use common::{Tally, rewrite_source_path_anchors, unescape};

const FIXTURE: &str = include_str!("data/autolink-expected.json");

const DEFAULT_IR: &str = "/private/tmp/lean-doc-relay/w7h/base-ir";
const DEFAULT_LINK_INDEX: &str = "/private/tmp/lean-doc-relay/w7c/linkindex/link-index.lidx";

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    oracle: String,
    /// Docstrings in the corpus the sample was drawn from.
    ir_docstrings: usize,
    known_entries: usize,
    link_index_entries: usize,
    known_modules: usize,
    ir_module_names: usize,
    lidx_module_names: usize,
    total_anchors: usize,
    cases_with_anchors: usize,
    /// Docstrings where the prototype's CommonMark subset differs from
    /// doc-gen4, taken from the md crate's fixture. Excluded from the full
    /// comparison: there this crate is on doc-gen4's side by design.
    prototype_differs: Vec<String>,
    /// Cases where the prototype puts an anchor inside an anchor. See
    /// [`the_prototype_is_the_one_that_nests_anchors`].
    prototype_nests_anchors: Vec<String>,
    /// How many of those are real docstrings.
    real_docstrings_nesting_anchors: usize,
    cases: Vec<Case>,
}

/// One case, and the whole world it resolves against.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Case {
    what: String,
    root: String,
    /// What `nameToLink`'s last branch scans, in the order it scans it.
    decl_names: Vec<String>,
    /// The IR's name -> module map.
    known: BTreeMap<String, String>,
    /// The dependency closure's map, as `.lidx` text.
    lidx: String,
    /// Module names contributed by the IR itself.
    ir_modules: Vec<String>,
    md: String,
    html: String,
}

impl Case {
    /// The case's [`NameIndex`], built from its three sources the way a run
    /// builds it from the IR and the `.lidx`.
    fn index(&self) -> NameIndex {
        let mut builder = NameIndex::builder();
        for module in &self.ir_modules {
            builder.module_name(module);
        }
        for (name, module) in &self.known {
            builder.declaration(name, module);
        }
        // M7-c: the prototype had no dependency map, so its bytes are the
        // **fallback** branch — which an empty [`ExternalLinks`] reproduces
        // exactly. With a map every link into a dependency moves, on purpose
        // (`docs/implementation-plan.md` §1).
        //
        // 2026-08-17: and the prototype rendered the whole environment, so its
        // links point at pages it wrote. A run's world has pages for the target
        // package alone; the oracle is resolved in the world it was recorded in.
        builder.build_with_a_page_for_every_module(
            LinkIndex::parse(&self.lidx),
            ExternalLinks::default(),
        )
    }

    fn render(&self) -> String {
        let index = self.index();
        let names: Vec<&str> = self.decl_names.iter().map(String::as_str).collect();
        let links = PageLinks::new_unchecked(&index, &self.root, &names);
        links.renderer().docstring(&self.md)
    }

    /// The prototype's bytes with the source-path branch re-answered by this
    /// port's resolver against this case's own world (`common`).
    fn with_source_paths_resolved(&self, tally: &mut Tally) -> String {
        let index = self.index();
        let names: Vec<&str> = self.decl_names.iter().map(String::as_str).collect();
        let links = PageLinks::new_unchecked(&index, &self.root, &names);
        rewrite_source_path_anchors(
            &self.html,
            &|stem| links.source_path_to_link(&self.root, stem),
            tally,
        )
    }
}

fn expected() -> Expected {
    serde_json::from_str(FIXTURE).expect("tests/data/autolink-expected.json is valid")
}

#[test]
fn fixture_is_the_prototypes_own_output() {
    let e = expected();
    assert!(e.oracle.contains("render.ts"), "{}", e.oracle);
    assert!(e.oracle.contains("--link-index"), "{}", e.oracle);
    assert!(
        e.cases.len() >= 150,
        "only {} cases; the sample stopped covering the corpus",
        e.cases.len()
    );
    assert!(
        e.cases
            .iter()
            .filter(|c| c.what.starts_with("curated: "))
            .count()
            >= 25,
        "the hand-written cases are what reach the corners the package has none of"
    );
    // Carried from the md crate's fixture rather than restated, so that the two
    // lists of "where the prototype is not the authority" cannot drift apart.
    assert_eq!(
        e.prototype_differs,
        ["InformationTheory.Shannon.TimeBandLimiting.Count module doc 1"],
        "the CommonMark-subset divergence list changed; re-run the md crate's \
         generator and this one in the same session"
    );
}

/// What the corpus is, pinned so that a number quoted anywhere else can be
/// traced to a run of the generator rather than to a memory of one.
#[test]
fn the_corpus_numbers_are_what_was_measured() {
    let e = expected();
    assert_eq!(e.ir_docstrings, 4_858, "distinct docstrings in the IR");
    assert_eq!(e.known_entries, 5_296, "names in `known`");
    assert_eq!(e.link_index_entries, 258_760, "names in the .lidx");
    assert_eq!(e.ir_module_names, 432, "modules in the IR");
    assert_eq!(e.lidx_module_names, 6_115, "modules in the .lidx @ section");
    assert_eq!(e.known_modules, 6_158, "the union of the three sources");
    assert_eq!(e.total_anchors, 5_495, "anchors over the whole corpus");
    assert_eq!(
        e.cases_with_anchors, 1_904,
        "docstrings that resolve at all"
    );
}

/// The comparison this file exists for.
#[test]
fn matches_the_prototype_on_every_case() {
    let e = expected();
    let nests: BTreeSet<&str> = e
        .prototype_nests_anchors
        .iter()
        .map(String::as_str)
        .collect();
    let mut failures = Vec::new();
    let mut tally = Tally::default();
    for case in &e.cases {
        if nests.contains(case.what.as_str()) || case.what == NAME_SEARCH_FOR_A_SOURCE_PATH {
            continue;
        }
        let got = case.render();
        let want = case.with_source_paths_resolved(&mut tally);
        if got != want {
            failures.push(format!(
                "{}\n  want: {}\n  got:  {}",
                case.what,
                show(&want),
                show(&got)
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ from the prototype:\n{}",
        failures.len(),
        e.cases.len(),
        failures.join("\n")
    );
    // M8, gate UI-2 — and the reason the numbers look like this: each case
    // carries only the world the *prototype* needed, and the prototype needed
    // nothing to link a source path. So the module a path names is in the case's
    // world only when the path happens to be the module's own full name, which
    // is the one anchor below that survives. What the rule does with the real
    // world is [`the_whole_corpus_matches_the_prototype`]'s number.
    // 【実測 2026-08-16】
    assert_eq!(
        tally,
        Tally {
            unchanged: 2,
            relinked: 0,
            dropped: 17
        },
        "the sample's source-path anchors moved differently"
    );
}

/// The one case whose M8 answer is not in an anchor's text and so cannot be
/// re-answered by [`rewrite_source_path_anchors`]: `##name` is a name search,
/// and its path reaches the resolver as a link *destination*.
const NAME_SEARCH_FOR_A_SOURCE_PATH: &str =
    "curated: a name search resolving to a module and to a source path";

/// `extendLink`'s first branch, with a source path in it (M8, gate UI-2).
///
/// `[b](##Foo/Bar.lean)` asks the same question a code span does, so the same
/// answer follows: with no module of that name, there is no link to build, and
/// `extendLink` does what it already does for an unresolved `##name` — it sends
/// the reader to the search page (`DocString.lean:91-93`). The prototype's
/// answer, kept in the fixture, is a link to a page nobody wrote.
#[test]
fn a_name_search_for_an_unknown_source_path_falls_back_to_the_find_page() {
    let e = expected();
    let case = e
        .cases
        .iter()
        .find(|c| c.what == NAME_SEARCH_FOR_A_SOURCE_PATH)
        .expect("the fixture records the prototype's answer for a name search on a path");
    assert_eq!(
        case.html, "<p><a href=\".././Pkg/A.html\">a</a> <a href=\".././Foo/Bar.html\">b</a></p>",
        "the prototype's answer changed"
    );
    assert_eq!(
        case.render(),
        "<p><a href=\".././Pkg/A.html\">a</a> \
         <a href=\".././find/?pattern=Foo/Bar.lean#doc\">b</a></p>"
    );
}

/// The one place the prototype and doc-gen4 disagree about *resolution* rather
/// than about CommonMark.
///
/// `renderText` carries an `inLink` flag and renders a code span inside an
/// `<a>` as plain text (`DocString.lean:264`); `renderInline` auto-links every
/// code span unconditionally (`render.ts:1622`). Under `NoLinks` the two are
/// indistinguishable, which is why the 4,987-case doc-gen4 comparison of M1-c's
/// earlier step could not see it. Plan §5 decides such cases in doc-gen4's
/// favour, and `tests/docgen4_linked.rs` carries the positive expectation —
/// doc-gen4's own bytes for the same input.
///
/// **No docstring of the target package reaches it** 【実測: 0 of 4,858】, so
/// gate A is untouched. What is asserted here is that the difference is *real*:
/// a port that had reproduced the prototype's nesting would fail.
#[test]
fn the_prototype_is_the_one_that_nests_anchors() {
    let e = expected();
    assert_eq!(
        e.real_docstrings_nesting_anchors, 0,
        "a real docstring now nests anchors; the divergence has reached gate A's bytes"
    );
    assert!(
        !e.prototype_nests_anchors.is_empty(),
        "no case reaches the inLink divergence any more"
    );
    let nests: BTreeSet<&str> = e
        .prototype_nests_anchors
        .iter()
        .map(String::as_str)
        .collect();
    let mut seen = 0;
    for case in e.cases.iter().filter(|c| nests.contains(c.what.as_str())) {
        seen += 1;
        let got = case.render();
        assert_ne!(
            got, case.html,
            "{}: matches the prototype's nesting",
            case.what
        );
        assert_eq!(depth_of_anchors(&got), 1, "{}: nests anchors", case.what);
        assert!(depth_of_anchors(&case.html) > 1, "{}", case.what);
    }
    assert_eq!(seen, nests.len(), "the sample dropped a recorded case");
}

/// The deepest `<a>` nesting in a fragment: 1 for well-formed output.
fn depth_of_anchors(html: &str) -> usize {
    let mut depth = 0usize;
    let mut max = 0usize;
    let mut rest = html;
    loop {
        let open = rest.find("<a ");
        let close = rest.find("</a>");
        match (open, close) {
            (Some(o), c) if c.is_none_or(|c| o < c) => {
                depth += 1;
                max = max.max(depth);
                rest = &rest[o + 3..];
            }
            (_, Some(c)) => {
                depth = depth.saturating_sub(1);
                rest = &rest[c + 4..];
            }
            _ => return max,
        }
    }
}

/// The sample has to keep reaching every branch of the resolver, or the test
/// above decays into one that a resolver returning `None` would pass.
///
/// Each entry names a shape only one branch produces.
#[test]
fn the_sample_reaches_every_branch() {
    let e = expected();
    let anchors: Vec<(String, String)> = e.cases.iter().flat_map(|c| anchors_of(&c.html)).collect();
    assert!(
        anchors.len() >= 200,
        "only {} anchors in the sample",
        anchors.len()
    );

    let any = |p: &dyn Fn(&str, &str) -> bool| anchors.iter().any(|(h, t)| p(h, t));
    // Branch 2: the name is documented, so the link carries its fragment.
    assert!(
        any(&|h, t| h.ends_with(&format!("#{t}"))),
        "no anchor whose fragment is the name itself"
    );
    // Branch 3: the name is a module, so there is no fragment at all.
    assert!(
        any(&|h, t| !h.contains('#') && h.ends_with(".html") && !t.ends_with(".lean")),
        "no anchor to a module page"
    );
    // Branch 4: the fragment is a *different* name — the one this page declares.
    assert!(
        any(&|h, t| h.contains('#') && !h.ends_with(&format!("#{t}"))),
        "no anchor produced by the component-suffix scan"
    );
    // `nameToLink`'s first branch, which the renderer answers itself.
    assert!(
        any(&|_, t| t.ends_with(".lean")),
        "no anchor for a source path"
    );
    // `extendLink`'s fallback for an unresolved `##name`.
    assert!(
        any(&|h, _| h.contains("find/?pattern=")),
        "no name search falling back to the find page"
    );
    // The characters an ASCII notion of a name would reject.
    assert!(
        any(&|_, t| t.contains('\'') || t.contains('!') || t.contains('?')),
        "no name containing an apostrophe, a bang or a question mark"
    );
    // The letter-like range above the BMP.
    assert!(
        any(&|_, t| t.chars().any(|c| c as u32 > 0xffff)),
        "no name containing a scalar above U+FFFF"
    );
    // Auto-linking inside a fenced code block, not just a code span.
    assert!(
        e.cases.iter().any(|c| c.html.contains("<pre><code")
            && c.html[c.html.find("<pre><code").unwrap_or(0)..].contains("<a href=")),
        "no anchor inside a code block"
    );
    // Every root the pages use has to appear, since it prefixes every link.
    let roots: BTreeSet<&str> = e.cases.iter().map(|c| c.root.as_str()).collect();
    assert!(
        roots.len() >= 3,
        "only {roots:?}; a resolver that ignored the root would pass"
    );
}

/// Every docstring of the target package, against the real IR and the real
/// dependency map.
///
/// `#[ignore]`d: it needs `LITEDOC4_AUTOLINK_FULL` to name the generator's
/// `--full` output, and that file is 5.6 MB and does not belong in the
/// repository.
///
/// This is the only place [`NameIndex`] is built the way a run builds it —
/// dependency slices, then declarations, then references, then the `.lidx` —
/// so it is what stands behind the claim that the reduced worlds above are the
/// same thing in miniature.
#[test]
#[ignore = "corpus: needs LITEDOC4_AUTOLINK_FULL + LITEDOC4_IR + LITEDOC4_LINK_INDEX (tools/corpus-gate.sh)"]
fn the_whole_corpus_matches_the_prototype() {
    let path = std::env::var("LITEDOC4_AUTOLINK_FULL").unwrap_or_else(|_| {
        panic!(
            "set LITEDOC4_AUTOLINK_FULL to a `--full` recording made by the generator at tag \
             experiments-frozen (HEAD cannot make one), or run this test through \
             tools/corpus-gate.sh, which is the only thing that should be asking for it"
        )
    });
    let ir_dir = env_path("LITEDOC4_IR", DEFAULT_IR);
    let lidx_path = env_path("LITEDOC4_LINK_INDEX", DEFAULT_LINK_INDEX);

    #[derive(Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct Full {
        prototype_differs: Vec<String>,
        cases: Vec<FullCase>,
    }
    #[derive(Deserialize)]
    struct FullCase {
        what: String,
        module: String,
        root: String,
        md: String,
        html: String,
    }

    let text = std::fs::read_to_string(&path).expect("LITEDOC4_AUTOLINK_FULL is readable");
    let full: Full = serde_json::from_str(&text).expect("the --full file is valid");

    let tree = IrTree::open(&ir_dir).expect("the IR opens");
    let modules = tree.load_modules().expect("every module reads");
    let mut builder = NameIndex::builder();
    for dep in tree.load_dep_maps().expect("every dependency slice reads") {
        builder.dep_map(&dep);
    }
    for module in &modules {
        builder.module(module);
    }
    // M7-c: the prototype had no dependency map, so its bytes are the
    // **fallback** branch — which an empty [`ExternalLinks`] reproduces
    // exactly. With a map every link into a dependency moves, on purpose
    // (`docs/implementation-plan.md` §1).
    // 2026-08-17: and the prototype rendered the whole environment, so its
    // links point at pages it wrote. A run's world has pages for the target
    // package alone; the oracle is resolved in the world it was recorded in.
    let index = builder.build_with_a_page_for_every_module(
        LinkIndex::read(&lidx_path).expect("the .lidx reads"),
        ExternalLinks::default(),
    );
    eprintln!(
        "{} names / {} in the .lidx / {} modules",
        index.len(),
        index.link_index_len(),
        index.known_module_count()
    );

    let decl_names: HashMap<&str, Vec<&str>> = modules
        .iter()
        .map(|m| (m.module.as_str(), module_decl_names(m)))
        .collect();

    let excluded: BTreeSet<&str> = full.prototype_differs.iter().map(String::as_str).collect();
    let mut compared = 0usize;
    let mut matched = 0usize;
    let mut failures = Vec::new();
    let mut tally = Tally::default();
    for case in &full.cases {
        if excluded.contains(case.what.as_str()) {
            continue;
        }
        // `getRoot` is an input to both sides, so check it rather than trust it.
        assert_eq!(page_root(&case.module), case.root, "{}", case.what);
        let names = &decl_names[case.module.as_str()];
        let links = PageLinks::new_unchecked(&index, &case.root, names);
        let got = links.renderer().docstring(&case.md);
        // M8, gate UI-2: the source-path branch, and only it, is this port's
        // own answer. Here the world is the real one, so the paths the package
        // writes relative to a module do resolve — to a different page than the
        // prototype's.
        let want = rewrite_source_path_anchors(
            &case.html,
            &|stem| links.source_path_to_link(&case.root, stem),
            &mut tally,
        );
        compared += 1;
        if got == want {
            matched += 1;
        } else if failures.len() < 20 {
            failures.push(format!(
                "{}\n  want: {}\n  got:  {}",
                case.what,
                show(&want),
                show(&got)
            ));
        }
    }
    eprintln!(
        "whole corpus: {matched} of {compared} match the prototype \
         ({} excluded as known CommonMark-subset differences); \
         source paths: {tally:?}",
        full.cases.len() - compared
    );
    assert_eq!(
        matched,
        compared,
        "{} differ:\n{}",
        compared - matched,
        failures.join("\n")
    );
    assert!(compared >= 4_800, "only {compared} cases were compared");
    // How many source paths the corpus's docstrings write is a property of the
    // IR, so it is pinned; how they split is a property of the `.lidx` this run
    // was given, so it is not.
    //
    // 【実測 2026-08-16, IR `m4d-final/base/ir` + `.lidx m5a/full-link-index-r4`】
    // `Tally { unchanged: 39, relinked: 153, dropped: 1 }` — the prototype's
    // repository-root reading was right for the 39 paths that name their module
    // in full and wrong for the 153 that name it relative to the module, which
    // are the dangling links gate UI-2 is about. One path names no module.
    assert_eq!(tally.total(), 193, "the corpus's source paths changed");
    assert!(
        tally.relinked > 0 && tally.unchanged > 0,
        "{tally:?}: a rule that moved every link, or none, is not this one"
    );
}

// ------------------------------------------------------------------- helpers

fn env_path(var: &str, default: &str) -> PathBuf {
    PathBuf::from(std::env::var(var).unwrap_or_else(|_| default.to_owned()))
}

/// `(href, text)` of every anchor whose text is plain, which is every anchor
/// `autoLinkInline` makes.
fn anchors_of(html: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut rest = html;
    while let Some(at) = rest.find("<a href=\"") {
        rest = &rest[at + 9..];
        let Some(end) = rest.find('"') else { break };
        let href = unescape(&rest[..end]);
        rest = &rest[end + 2..];
        let Some(close) = rest.find("</a>") else {
            break;
        };
        let text = &rest[..close];
        if !text.contains('<') {
            out.push((href, unescape(text)));
        }
        rest = &rest[close + 4..];
    }
    out
}

/// Renders a string so a failure names the code points rather than printing
/// control characters into the terminal.
fn show(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if c == '\n' {
            out.push_str("\\n");
        } else if (c.is_ascii_graphic() || c == ' ') || !c.is_control() {
            out.push(c);
        } else {
            out.push_str(&format!("<U+{:04X}>", c as u32));
        }
    }
    out
}
