//! Every answer in this file was produced by the TypeScript prototype, not by
//! the Rust code it checks.
//!
//! `tests/data/ts-expected.json` was generated by `tests/gen-ts-expected.ts`,
//! which sliced the function definitions out of the prototype and imported
//! them, so the expectations are the prototype's own bytes running. **It is a
//! frozen value: HEAD has no way to regenerate it** — the generator and the
//! prototype it drove exist only at tag `experiments-frozen`. It is
//! `include_str!`d, so these tests pass on a machine that has never seen the
//! target package.
//!
//! A passing run is worth only as much as the corpus, which is built to contain
//! the cases where Rust's defaults are *wrong* rather than the cases where they
//! happen to work: `'` (which every HTML-escaping crate escapes and
//! `Html.escape` does not), C0 controls and U+007F (`String.quote`'s `\xNN`,
//! which `{:?}` writes differently), and scalars above U+FFFF (where UTF-16
//! order and UTF-8 byte order invert). [`utf16_order_is_not_byte_order`] fails
//! if that last group ever stops being present, so this cannot quietly decay
//! into a file that would pass with `Vec<String>::sort`.

use std::cmp::Ordering;

use litedoc4_ir::{Span, Utf16Text, cmp_utf16, sort_utf16};
use litedoc4_render::escape::{escape_html, escape_html_into, lean_quote};
use litedoc4_render::order::{cmp_name, string_lt};
use litedoc4_render::whitespace::apply_ws_widths;
use litedoc4_testutil::text::show_ascii;
use serde::Deserialize;

const FIXTURE: &str = include_str!("data/ts-expected.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    deno: String,
    escape_html: Vec<(String, String)>,
    lean_quote: Vec<(String, String)>,
    string_lt: Vec<(String, String, bool)>,
    name_lt: Vec<(String, String, bool)>,
    name_sort: SortCase,
    utf16_sort: SortCase,
    apply_ws_widths: Vec<WsCase>,
}

#[derive(Deserialize)]
struct SortCase {
    input: Vec<String>,
    output: Vec<String>,
}

#[derive(Deserialize)]
struct WsCase {
    what: String,
    text: String,
    spans: Vec<Span>,
    output: String,
    changed: u32,
}

fn expected() -> Expected {
    serde_json::from_str(FIXTURE).expect("tests/data/ts-expected.json is valid")
}

#[test]
fn fixture_is_the_prototypes_own_output() {
    let e = expected();
    assert!(!e.deno.is_empty(), "the fixture records which deno ran");
    // A corpus that shrank is a corpus that stopped covering something.
    assert!(e.escape_html.len() >= 100);
    assert!(e.string_lt.len() >= 1_000);
    assert!(e.apply_ws_widths.len() >= 5);
}

#[test]
fn escape_html_matches_the_prototype() {
    for (input, want) in expected().escape_html {
        assert_eq!(
            escape_html(&input),
            want,
            "escapeHtml({})",
            show_ascii(&input)
        );
        let mut buf = String::from("<p>");
        escape_html_into(&mut buf, &input);
        assert_eq!(
            buf,
            format!("<p>{want}"),
            "escapeHtmlInto({})",
            show_ascii(&input)
        );
    }
}

/// The specific default this port must not inherit: `Html.escape` leaves `'`
/// alone, so a general-purpose escaper is wrong here by exactly one entity.
#[test]
fn escape_html_leaves_the_apostrophe_alone() {
    let cases = expected().escape_html;
    let with_quote: Vec<_> = cases.iter().filter(|(i, _)| i.contains('\'')).collect();
    assert!(
        !with_quote.is_empty(),
        "the corpus must contain an apostrophe"
    );
    for (input, want) in with_quote {
        assert!(
            !want.contains("&#"),
            "the prototype escaped {}",
            show_ascii(input)
        );
        let got = escape_html(input);
        assert_eq!(got, *want, "escapeHtml({})", show_ascii(input));
        assert_eq!(got.matches('\'').count(), input.matches('\'').count());
    }
}

#[test]
fn lean_quote_matches_the_prototype() {
    for (input, want) in expected().lean_quote {
        assert_eq!(
            lean_quote(&input),
            want,
            "leanQuote({})",
            show_ascii(&input)
        );
    }
}

#[test]
fn lean_quote_is_not_rusts_debug() {
    let mut differing = 0;
    for (input, want) in expected().lean_quote {
        if format!("{input:?}") != want {
            differing += 1;
        }
    }
    assert!(
        differing >= 30,
        "only {differing} corpus entries told String.quote apart from Debug"
    );
}

#[test]
fn string_lt_matches_the_prototype() {
    for (a, b, want) in expected().string_lt {
        assert_eq!(
            string_lt(&a, &b),
            want,
            "stringLt({}, {})",
            show_ascii(&a),
            show_ascii(&b)
        );
    }
}

#[test]
fn name_lt_matches_the_prototype() {
    for (a, b, want) in expected().name_lt {
        let want = if want {
            Ordering::Less
        } else if cmp_name(&b, &a) == Ordering::Less {
            Ordering::Greater
        } else {
            Ordering::Equal
        };
        assert_eq!(
            cmp_name(&a, &b),
            want,
            "nameLt({}, {})",
            show_ascii(&a),
            show_ascii(&b)
        );
    }
}

#[test]
fn name_sort_matches_the_prototype() {
    let case = expected().name_sort;
    let mut names = case.input.clone();
    names.sort_by(|a, b| cmp_name(a, b));
    assert_eq!(names, case.output);
}

#[test]
fn utf16_sort_matches_the_prototype() {
    let case = expected().utf16_sort;
    let mut names = case.input.clone();
    sort_utf16(&mut names);
    assert_eq!(names, case.output);
}

/// The reason [`sort_utf16`] exists. If this ever stops finding an inversion,
/// the corpus has lost its non-BMP entries and every other sort assertion in
/// this file has become vacuous.
#[test]
fn utf16_order_is_not_byte_order() {
    let case = expected().utf16_sort;

    let mut by_bytes = case.input.clone();
    by_bytes.sort();
    assert_ne!(
        by_bytes, case.output,
        "Vec<String>::sort() reproduced the prototype's order, so this corpus proves nothing"
    );

    let inversions: Vec<_> = case
        .input
        .iter()
        .flat_map(|a| case.input.iter().map(move |b| (a, b)))
        .filter(|(a, b)| cmp_utf16(a, b) != a.cmp(b))
        .collect();
    assert!(
        !inversions.is_empty(),
        "no pair in the corpus separates UTF-16 order from byte order"
    );
    for (a, b) in &inversions {
        // Every inversion is a supplementary scalar meeting one in
        // U+E000..=U+FFFF, never two BMP strings.
        let astral = |s: &str| s.chars().any(|c| c as u32 > 0xFFFF);
        assert!(
            astral(a) || astral(b),
            "{} / {} disagree without a supplementary scalar",
            show_ascii(a),
            show_ascii(b)
        );
    }

    assert_eq!(cmp_utf16("𝒜", "\u{FB00}"), Ordering::Less);
    assert_eq!("𝒜".cmp("\u{FB00}"), Ordering::Greater);
}

/// `String.lt` is code point order, which is what `str`'s own `Ord` is, and is
/// *not* the order the global artifacts are sorted in. Both halves matter: the
/// first says `string_lt` may be a plain comparison, the second says it may not
/// be used where `Array.prototype.sort()` was.
#[test]
fn string_lt_is_code_point_order_not_utf16_order() {
    let pairs = expected().string_lt;
    for (a, b, want) in &pairs {
        assert_eq!(*want, a < b, "stringLt vs str::cmp on {}", show_ascii(a));
    }
    let disagreeing = pairs
        .iter()
        .filter(|(a, b, want)| *want != (cmp_utf16(a, b) == Ordering::Less))
        .count();
    assert!(
        disagreeing > 0,
        "the corpus never separates String.lt from UTF-16 order"
    );
}

#[test]
fn apply_ws_widths_matches_the_prototype() {
    for case in expected().apply_ws_widths {
        let text = Utf16Text::from(case.text.as_str());
        let got = apply_ws_widths(&text, &case.spans);
        assert_eq!(
            got.as_text().as_str(),
            case.output,
            "applyWsWidths({}): {}",
            case.what,
            show_ascii(&case.text)
        );
        assert_eq!(
            got.changed_units, case.changed,
            "wsWidthChars: {}",
            case.what
        );
        // Length preservation is the property the caller depends on: the spans
        // are reused over the result.
        assert_eq!(got.as_text().len_utf16(), text.len_utf16(), "{}", case.what);
    }
}
