//! The referee: **doc-gen4's own bytes** for docstrings whose names resolve.
//!
//! `tests/data/docgen4-linked-expected.json` was generated by
//! `tests/oracle/gen-docgen4-linked-expected.ts`, which ran
//! `DocGen4.Output.docStringToHtml` under `lake env lean` in the measurement
//! target with `AnalyzerResult.name2ModIdx` and `.moduleNames` filled in.
//!
//! **The fixture is a frozen value: HEAD has no way to regenerate it.** The
//! expected HTML came from doc-gen4, but the generator also imported the frozen
//! prototype — to pick the cases and to record `prototypeDiffers` — so it went
//! with `experiments/` on 2026-08-16 and exists only at tag
//! `experiments-frozen`. `tests/oracle/dump-html-linked.lean`, the doc-gen4 half,
//! is still here.
//!
//! # Why a second oracle, when the target is the prototype
//!
//! Plan §5 is explicit that this port's target is `experiments/stage7d/render.ts`
//! and not doc-gen4: the two `nameToLink`s are different functions and it is the
//! prototype that scores 439/439. But M1-c's earlier doc-gen4 comparison ran
//! with an *empty* `AnalyzerResult`, so nothing had ever asked doc-gen4 what a
//! resolved docstring looks like — and "the prototype is the target" does not
//! mean "the prototype is right about everything".
//!
//! It was not. The first run of this file found that the prototype auto-links a
//! code span **inside an `<a>`** and doc-gen4 does not (`inLink`,
//! `DocString.lean:264` against `render.ts:1622`). Under `NoLinks` the two are
//! byte-identical, which is why 4,987 comparisons had not seen it. This crate
//! follows doc-gen4, and this file is where that expectation comes from.
//!
//! **No docstring of the target package reaches the difference** 【実測: 0 of
//! 4,858, `tests/autolink.rs`】, so gate A's bytes are unaffected.
//!
//! # The agreement zone
//!
//! The two specifications genuinely differ in three more places, and the corpus
//! avoids all three rather than papering over them — see the generator. The one
//! that is enforced *here* is the last: doc-gen4 runs with `currentName := none`,
//! so its module-local branch never fires, and these cases are therefore
//! rendered with an empty declaration list. `tests/autolink.rs` is what covers
//! that branch, against the prototype.

use std::collections::{BTreeMap, BTreeSet};

use litedoc4_md::LinkResolver;
use litedoc4_render::autolink::{NameIndex, PageLinks};
use litedoc4_render::{ExternalLinks, LinkIndex};
use serde::Deserialize;

mod common;
use common::{Tally, rewrite_source_path_anchors};

const FIXTURE: &str = include_str!("data/docgen4-linked-expected.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    oracle: String,
    agreement_zone: String,
    lean_toolchain: String,
    /// Cases where the *prototype* does not produce doc-gen4's bytes.
    prototype_differs: Vec<String>,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    what: String,
    root: String,
    /// `AnalyzerResult.moduleNames`.
    modules: Vec<String>,
    /// `AnalyzerResult.name2ModIdx`, as name -> module.
    names: BTreeMap<String, String>,
    md: String,
    html: String,
}

impl Case {
    fn render(&self) -> String {
        let index = self.index();
        // Empty: doc-gen4's module-local branch is disabled for this corpus.
        let links = PageLinks::new(&index, &self.root, &[]);
        links.renderer().docstring(&self.md)
    }

    /// doc-gen4's own bytes with the **source-path** branch re-answered by this
    /// crate's resolver (`common`, M8 gate UI-2).
    fn with_source_paths_resolved(&self, tally: &mut Tally) -> String {
        let index = self.index();
        let links = PageLinks::new(&index, &self.root, &[]);
        rewrite_source_path_anchors(
            &self.html,
            &|stem| links.source_path_to_link(&self.root, stem),
            tally,
        )
    }

    /// **Not `common::name_index`.** That one ends in
    /// `build_with_a_page_for_every_module` against a parsed `.lidx`, which is
    /// the prototype's whole-environment world; this corpus has no `.lidx` and
    /// its oracle is doc-gen4, so it ends in `build`.
    fn index(&self) -> NameIndex {
        let mut builder = NameIndex::builder();
        for module in &self.modules {
            builder.module_name(module);
        }
        for (name, module) in &self.names {
            builder.declaration(name, module);
        }
        // **The doc-gen4 oracle still applies here, and M7-c is why that needs
        // saying.** doc-gen4 wrote these answers with every link a relative page
        // link, which is what an empty [`ExternalLinks`] produces byte for byte.
        // Give this corpus a dependency map instead and the two would part
        // company on every resolved name — by design, since doc-gen4 byte
        // compatibility is retired. The map is
        // empty rather than absent because there is nothing to fill it with:
        // these cases are synthetic worlds with no package behind them.
        builder.build(LinkIndex::default(), ExternalLinks::default())
    }
}

fn expected() -> Expected {
    serde_json::from_str(FIXTURE).expect("tests/data/docgen4-linked-expected.json is valid")
}

#[test]
fn fixture_is_doc_gen4s_own_output() {
    let e = expected();
    assert!(e.oracle.contains("docStringToHtml"), "{}", e.oracle);
    assert!(e.oracle.contains("AnalyzerResult"), "{}", e.oracle);
    assert!(
        e.agreement_zone.contains("currentName"),
        "{}",
        e.agreement_zone
    );
    assert_eq!(e.lean_toolchain, "leanprover/lean4:v4.31.0");
    assert!(e.cases.len() >= 120, "only {} cases", e.cases.len());
    // A corpus in which nothing resolves would pass every assertion below.
    let anchors: usize = e
        .cases
        .iter()
        .map(|c| c.html.matches("<a href=").count())
        .sum();
    assert!(
        anchors >= 200,
        "only {anchors} anchors in doc-gen4's answers"
    );
}

/// The comparison this file exists for.
#[test]
fn matches_doc_gen4_on_every_case() {
    let e = expected();
    let mut failures = Vec::new();
    let mut tally = Tally::default();
    for case in &e.cases {
        let got = case.render();
        let want = case.with_source_paths_resolved(&mut tally);
        if got != want {
            failures.push(format!("{}\n  want: {}\n  got:  {}", case.what, want, got));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ from doc-gen4:\n{}",
        failures.len(),
        e.cases.len(),
        failures.join("\n")
    );
    // M8, gate UI-2. These worlds are `AnalyzerResult` reduced to the names each
    // case looks up, and doc-gen4 looks nothing up to link a source path — so
    // none of the modules the paths name is in them, and every one of these
    // anchors is a link this crate now declines to build. What the rule does
    // with a real world is `tests/autolink.rs`'s and `tests/pages.rs`'s number.
    // 【実測 2026-08-16】
    assert_eq!(
        tally,
        Tally {
            unchanged: 0,
            relinked: 0,
            dropped: 12
        },
        "the corpus's source-path anchors moved differently"
    );
}

/// The inputs on which the prototype is *not* the authority, named rather than
/// counted.
///
/// If this list ever grows past the `inLink` pair, the new entry is a place
/// where `tests/autolink.rs` is asserting the wrong expectation, and it has to
/// be looked at before either fixture is regenerated.
#[test]
fn the_prototype_differs_only_where_it_nests_anchors() {
    let e = expected();
    let differs: BTreeSet<&str> = e.prototype_differs.iter().map(String::as_str).collect();
    assert_eq!(
        differs,
        BTreeSet::from([
            "curated: a code span inside a link is not auto-linked",
            "curated: a code span inside an emphasised link is not auto-linked",
        ]),
        "the set of prototype-vs-doc-gen4 differences changed"
    );
    // And doc-gen4's answer really is the un-nested one, so that the assertion
    // in `tests/autolink.rs` stands on bytes rather than on a reading.
    for case in e.cases.iter().filter(|c| differs.contains(c.what.as_str())) {
        assert!(
            case.html.contains("<code>Pkg.A.f</code>"),
            "{}: {}",
            case.what,
            case.html
        );
    }
}

/// Every case a real docstring contributed agreed with doc-gen4 when the
/// fixture was generated. Recorded so that a corpus which quietly became
/// hand-written only would fail.
#[test]
fn most_of_the_corpus_is_real_docstrings() {
    let e = expected();
    let real = e
        .cases
        .iter()
        .filter(|c| !c.what.starts_with("curated: "))
        .count();
    assert!(real >= 100, "only {real} real docstrings in the corpus");
    assert!(
        e.prototype_differs
            .iter()
            .all(|w| w.starts_with("curated: ")),
        "a real docstring now separates the prototype from doc-gen4"
    );
}
