//! Every answer in this file was produced by the TypeScript prototype, not by
//! the Rust code it checks.
//!
//! `tests/data/fragment-expected.json` was generated by
//! `tests/oracle/gen-fragment-expected.ts`, which sliced `Renderer` and its
//! helpers out of the frozen prototype and ran them over the **real** IR.
//!
//! **The fixture is a frozen value: HEAD has no way to regenerate it.** The
//! generator and the prototype it drove were removed with `experiments/` on
//! 2026-08-16 and exist only at tag `experiments-frozen`.
//!
//! # Why the prototype and not doc-gen4
//!
//! M1-c could use doc-gen4 itself, because `docStringToHtml` takes a markdown
//! string and both implementations take the same one. This step has no such
//! input in common: doc-gen4's `renderedCodeToHtmlAux` walks a `CodeWithInfos`
//! tree, and the IR carries the *flattened* span list the extractor made out of
//! it. The prototype is the only other consumer of that list, and it is the one
//! scoring 439/439 (plan §1).
//!
//! # The two halves
//!
//! - The committed fixture is self-contained. Each case carries the two maps it
//!   resolves against, reduced to the names it looks up, and the generator
//!   proves the reduction faithful by re-rendering with it.
//! - [`the_whole_corpus_matches_the_prototype`] runs **all 55,514 fragments** of
//!   the target package against the real IR. It is `#[ignore]`d and needs
//!   `LITEDOC4_FRAGMENT_FULL` to point at the generator's `--full` output
//!   (29 MB, which does not belong in the repository).
//!
//! # What the real corpus does not reach
//!
//! Three of the ten branches never fire over all 55,514 fragments
//! (`branchTotals` in the fixture): no constant fails to resolve, none resolves
//! through [`find_linkable_parent`], and none is missing from its declaration's
//! own `refs`. A mutation to any of those three is therefore invisible to real
//! data, and the hand-written cases are the only thing standing over them —
//! [`the_curated_cases_cover_what_the_package_does_not`] refuses to let that
//! quietly stop being true.

// The span counts are differenced against each other, and a difference that
// comes out negative is what names the branch — hence `isize` rather than
// `usize`. One fixture case holds tens of spans.
#![expect(
    clippy::cast_possible_wrap,
    reason = "counts from the frozen fixture, differenced as isize"
)]

use std::collections::{BTreeMap, BTreeSet};

use litedoc4_ir::{IrTree, Span, SpanKind, Utf16Text};
use litedoc4_render::autolink::{NameIndex, page_root};
use litedoc4_render::code::{
    CodeRenderer, Refs, Rendered, decl_refs, kind_description, module_from_private_prefix,
    private_to_user_name,
};
use litedoc4_render::{ExternalLinks, LinkIndex, break_within, css_kind};
use litedoc4_testutil::corpus;
use litedoc4_testutil::text::show;
use serde::Deserialize;

mod common;
use common::anchors_of;

const FIXTURE: &str = include_str!("data/fragment-expected.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    oracle: String,
    /// Span-carrying fragments in the IR — the `--full` corpus.
    ir_fragments: usize,
    ir_modules: usize,
    ir_declarations: usize,
    /// Distinct declaration and member names, the population `breaks` samples.
    ir_names: usize,
    known_entries: usize,
    anchors: usize,
    anchored_fragments: usize,
    /// Every `getRoot` the corpus produces. The root prefixes every link, so a
    /// port that ignored it would pass a one-root corpus.
    roots: Vec<String>,
    /// How often each branch of the walk fires over the whole corpus.
    branch_totals: BTreeMap<String, u64>,
    /// Branches the hand-written cases reach.
    curated_branches: BTreeSet<String>,
    cases: Vec<Case>,
    kinds: Vec<KindCase>,
    breaks: Vec<BreakCase>,
    privates: Vec<PrivateCase>,
}

/// One fragment, and the whole world it resolves against.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Case {
    what: String,
    root: String,
    /// The IR's global name -> module map, reduced to what this case asks for.
    known: BTreeMap<String, String>,
    /// The declaration's own references, same reduction.
    refs: BTreeMap<String, String>,
    text: String,
    /// The wire form, so the span parser is exercised too.
    spans: Vec<Span>,
    html: String,
    has_anchor: bool,
}

#[derive(Deserialize)]
struct KindCase {
    kind: String,
    modifiers: Vec<String>,
    description: String,
    css: String,
}

#[derive(Deserialize)]
struct BreakCase {
    name: String,
    html: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct PrivateCase {
    name: String,
    user_name: String,
    module: Option<String>,
}

impl Case {
    /// **Not `common::name_index`.** This corpus has no `.lidx` and no IR
    /// module list, so the index is built from `known` alone against an empty
    /// [`LinkIndex`] — a different world, not the same one written twice.
    fn index(&self) -> NameIndex {
        let mut builder = NameIndex::builder();
        for (name, module) in &self.known {
            builder.declaration(name, module);
        }
        // M7-c: the oracle is the frozen prototype, which had no dependency
        // map, so the comparison is against the **fallback** branch — which an
        // empty [`ExternalLinks`] reproduces byte for byte. A populated map
        // would move every link into a dependency, on purpose — doc-gen4
        // byte compatibility is no longer required.
        //
        // 2026-08-17: and the prototype rendered the whole environment, so its
        // links point at pages it wrote. A run's world has pages for the target
        // package alone; the oracle is resolved in the world it was recorded in.
        builder.build_with_a_page_for_every_module(LinkIndex::default(), ExternalLinks::default())
    }

    fn refs(&self) -> Refs<'_> {
        self.refs
            .iter()
            .map(|(name, module)| (name.as_str(), module.as_str()))
            .collect()
    }

    fn render(&self, index: &NameIndex) -> Rendered {
        CodeRenderer::new(index).fragment(
            &Utf16Text::from(self.text.as_str()),
            &self.spans,
            &self.root,
            &self.refs(),
        )
    }
}

fn expected() -> Expected {
    serde_json::from_str(FIXTURE).expect("tests/data/fragment-expected.json is valid")
}

#[test]
fn fixture_is_the_prototypes_own_output() {
    let e = expected();
    assert!(e.oracle.contains("render.ts"), "{}", e.oracle);
    assert!(e.oracle.contains("Renderer.fragment"), "{}", e.oracle);
    assert!(
        e.cases.len() >= 150,
        "only {} cases; the sample stopped covering the corpus",
        e.cases.len()
    );
    assert!(
        e.cases
            .iter()
            .filter(|c| c.what.starts_with("curated: "))
            .count()
            >= 20,
        "the hand-written cases are what reach the corners the package has none of"
    );
}

/// What the corpus is, pinned so that a number quoted anywhere else can be
/// traced to a run of the generator rather than to a memory of one.
///
/// **The denominator is the fragment, not the declaration or the page**: one
/// `Decl.type` + `typeCode`, one per `Decl.binders[i]` + `binderCode[i]`, one
/// per `Decl.equations[i]` + `equationCode[i]`, one per `Member.text` + `code`,
/// and one per `Member.binders[i]` + `binderCode[i]`.
#[test]
fn the_corpus_numbers_are_what_was_measured() {
    let e = expected();
    assert_eq!(e.ir_fragments, 55_514, "span-carrying fragments in the IR");
    assert_eq!(e.ir_modules, 432, "modules in the IR");
    assert_eq!(e.ir_declarations, 4_750, "declarations in the IR");
    assert_eq!(e.ir_names, 4_750, "distinct declaration and member names");
    assert_eq!(e.known_entries, 5_296, "names in `known`");
    assert_eq!(e.anchors, 120_868, "anchors over the whole corpus");
    assert_eq!(e.anchored_fragments, 54_452, "fragments that link at all");
    assert_eq!(
        e.roots,
        [
            "../../../../.././",
            "../../../.././",
            "../../.././",
            "../.././",
            ".././"
        ],
        "the roots the target package's module depths produce"
    );
    assert_eq!(
        e.branch_totals,
        BTreeMap::from([
            ("anchorsConst".to_owned(), 113_318),
            ("anchorsSort".to_owned(), 7_550),
            ("anchorsModuleFallback".to_owned(), 13),
            ("constSpansSuppressedByNesting".to_owned(), 28_916),
            ("constSpansUnlinkable".to_owned(), 0),
            ("constSpansViaParent".to_owned(), 0),
            ("constSpansPrivate".to_owned(), 13),
            ("constSpansNameNotInRefs".to_owned(), 0),
            ("wsWidthChars".to_owned(), 3_417),
            ("wsWidthFragments".to_owned(), 1_792),
        ]),
        "the branch profile of the corpus changed"
    );
    assert_eq!(
        e.branch_totals["anchorsConst"] + e.branch_totals["anchorsSort"],
        e.anchors as u64,
        "every anchor comes from one of the two branches that make one"
    );
}

/// The comparison this file exists for, over the committed sample.
#[test]
fn matches_the_prototype_on_every_case() {
    let e = expected();
    let mut failures = Vec::new();
    for case in &e.cases {
        let got = case.render(&case.index());
        if got.html != case.html {
            failures.push(format!(
                "{}\n  want: {}\n  got:  {}",
                case.what,
                show(&case.html),
                show(&got.html)
            ));
        } else if got.has_anchor != case.has_anchor {
            failures.push(format!(
                "{}: hasAnchor {}, want {}",
                case.what, got.has_anchor, case.has_anchor
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ from the prototype:\n{}",
        failures.len(),
        e.cases.len(),
        failures.join("\n")
    );
}

/// The sample has to keep reaching every branch, or the test above decays into
/// one that a renderer emitting escaped text and nothing else would pass.
///
/// Each assertion names a shape exactly one branch produces, read back out of
/// the fixture's own bytes rather than out of the port.
#[test]
fn the_sample_reaches_every_branch() {
    let e = expected();
    let anchors: Vec<(String, String)> = e.cases.iter().flat_map(|c| anchors_of(&c.html)).collect();
    assert!(
        anchors.len() >= 400,
        "only {} anchors in the sample",
        anchors.len()
    );

    let span_names: BTreeSet<&str> = e
        .cases
        .iter()
        .flat_map(|c| c.spans.iter().filter_map(|s| s.name.as_deref()))
        .collect();

    // The sort branch: the one link that is not derived from a name.
    assert!(
        anchors
            .iter()
            .any(|(href, _)| href.ends_with("foundational_types.html")),
        "no anchor to the foundational types page"
    );
    // A direct hit: the fragment is the tagged constant's own name.
    assert!(
        anchors.iter().any(|(href, _)| href
            .rsplit_once('#')
            .is_some_and(|(_, frag)| span_names.contains(frag))),
        "no anchor whose fragment is a tagged constant's name"
    );
    // `findLinkableParent`: the fragment is a *proper prefix* of the name.
    assert!(
        anchors
            .iter()
            .any(|(href, _)| href.rsplit_once('#').is_some_and(|(_, frag)| {
                !span_names.contains(frag)
                    && span_names
                        .iter()
                        .any(|n| n.starts_with(frag) && n[frag.len()..].starts_with('.'))
            })),
        "no anchor produced by findLinkableParent"
    );
    // The private-name fallback: a module link with no fragment at all.
    assert!(
        anchors
            .iter()
            .any(|(href, _)| !href.contains('#') && !href.ends_with("foundational_types.html")),
        "no module-link fallback for a private name"
    );
    // The escape in the link target, which is `Html.escape` and not a general
    // one — an apostrophe in a name has to survive it.
    assert!(
        e.cases
            .iter()
            .any(|c| c.html.contains("<a href=\"") && c.html.contains("&amp;")),
        "no link target that needed escaping"
    );
    assert!(
        e.cases.iter().any(|c| c.text.contains('\'')),
        "no fragment containing an apostrophe"
    );
    // Above the BMP, where a byte-indexed port slices in the wrong place.
    assert!(
        e.cases
            .iter()
            .any(|c| c.text.chars().any(|ch| ch as u32 > 0xffff)),
        "no fragment containing a scalar above U+FFFF"
    );
    // Schema-3 widths that actually rewrite something.
    assert!(
        e.cases.iter().any(|c| c.spans.iter().any(
            |s| (s.front > 0 || s.back > 0) && (c.text.contains('\n') || c.text.contains('\t'))
        )),
        "no fragment where the whitespace widths change a code unit"
    );
    // Every root the pages use, since it prefixes every link.
    let roots: BTreeSet<&str> = e.cases.iter().map(|c| c.root.as_str()).collect();
    assert!(
        roots.len() >= 6,
        "only {roots:?}; a port that ignored the root would pass"
    );

    // The two suppressions, counted rather than pattern-matched. Every tag
    // accounts for exactly one thing in the output: a kind-0 span is always a
    // `span.fn`, a constant is an `<a>` or a `span.fn` or nothing (suppressed),
    // and a sort is an `<a>` or nothing. So the leftovers name the branch.
    let mut sort_suppressed = 0isize;
    let mut const_suppressed = 0isize;
    let mut unlinkable = 0isize;
    for case in &e.cases {
        let count =
            |p: &dyn Fn(SpanKind) -> bool| case.spans.iter().filter(|s| p(s.kind)).count() as isize;
        let fn_spans = count(&|k| k == SpanKind::Fn);
        // An unknown kind takes the constant branch, as it does in the
        // prototype, so it is counted with the constants rather than ignored.
        let const_spans = count(&|k| !matches!(k, SpanKind::Fn | SpanKind::Sort));
        let sort_spans = count(&|k| k == SpanKind::Sort);
        let fn_tags = case.html.matches("<span class=\"fn\">").count() as isize;
        let sort_anchors = case.html.matches("foundational_types.html\">").count() as isize;
        let all_anchors = case.html.matches("<a href=\"").count() as isize;
        // A `span.fn` beyond one per kind-0 span is an unlinkable constant.
        let unlinkable_here = fn_tags - fn_spans;
        assert!(
            unlinkable_here >= 0,
            "{}: fewer span.fn than kind-0 spans",
            case.what
        );
        unlinkable += unlinkable_here;
        sort_suppressed += sort_spans - sort_anchors;
        if sort_spans == 0 {
            const_suppressed += const_spans - unlinkable_here - all_anchors;
        }
    }
    assert!(unlinkable > 0, "no constant that resolves to nothing");
    assert!(
        sort_suppressed > 0,
        "no sort whose anchor is suppressed by a nested one"
    );
    assert!(
        const_suppressed > 0,
        "no constant whose anchor is suppressed by a nested one"
    );
}

/// The `>=` in `buildTree`: two spans that merely touch are siblings.
///
/// Asserted on the *sample* rather than on the port, by rebuilding the nesting
/// under both rules here. If no committed case distinguishes them, changing the
/// comparison in the port would not fail anything, and this says so.
#[test]
fn the_sample_distinguishes_touching_from_nested() {
    let e = expected();
    let differing = e
        .cases
        .iter()
        .filter(|c| parents_under(&c.spans, false) != parents_under(&c.spans, true))
        .count();
    assert!(
        differing > 0,
        "no case where a span starts exactly where another ends; \
         `start >= stop` and `start > stop` would be indistinguishable"
    );
}

/// Which span each span is nested in, under a given rule. `strict` is the
/// mutation `buildTree` must not have.
fn parents_under(spans: &[Span], strict: bool) -> Vec<isize> {
    let mut out = Vec::with_capacity(spans.len());
    let mut stack: Vec<usize> = Vec::new();
    for span in spans {
        while let Some(&top) = stack.last() {
            let past = if strict {
                span.start > spans[top].stop
            } else {
                span.start >= spans[top].stop
            };
            if past {
                stack.pop();
            } else {
                break;
            }
        }
        out.push(stack.last().map_or(-1, |&p| p as isize));
        stack.push(out.len() - 1);
    }
    out
}

/// The three branches no real fragment reaches, and the fact that the curated
/// cases do reach them.
#[test]
fn the_curated_cases_cover_what_the_package_does_not() {
    let e = expected();
    let never: BTreeSet<&str> = e
        .branch_totals
        .iter()
        .filter(|(_, n)| **n == 0)
        .map(|(k, _)| k.as_str())
        .collect();
    assert_eq!(
        never,
        BTreeSet::from([
            "constSpansNameNotInRefs",
            "constSpansUnlinkable",
            "constSpansViaParent",
        ]),
        "which branches the target package never reaches has changed"
    );
    for branch in &never {
        assert!(
            e.curated_branches.contains(*branch),
            "{branch} fires nowhere in the corpus and nowhere in the curated cases either: \
             nothing would catch a mutation to it"
        );
    }
    // And the curated set reaches everything, not only the three.
    let all: BTreeSet<&str> = e.branch_totals.keys().map(String::as_str).collect();
    let curated: BTreeSet<&str> = e.curated_branches.iter().map(String::as_str).collect();
    assert_eq!(all, curated, "the curated cases stopped covering a branch");
}

/// `kindDescription` and `cssKind` over every `(kind, modifiers)` combination
/// the IR contains.
#[test]
fn kinds_match_the_prototype() {
    let e = expected();
    assert!(e.kinds.len() >= 10, "only {} combinations", e.kinds.len());
    for case in &e.kinds {
        assert_eq!(
            kind_description(&case.kind, &case.modifiers),
            case.description,
            "kindDescription({:?}, {:?})",
            case.kind,
            case.modifiers
        );
        assert_eq!(css_kind(&case.kind), case.css, "cssKind({:?})", case.kind);
    }
    // The two mappings must not have collapsed into one.
    assert!(
        e.kinds.iter().any(|c| c.description != c.css),
        "no kind where the displayed words and the CSS class differ"
    );
}

#[test]
fn break_within_matches_the_prototype() {
    let e = expected();
    assert!(e.breaks.len() >= 100, "only {} names", e.breaks.len());
    for case in &e.breaks {
        assert_eq!(break_within(&case.name), case.html, "{}", case.name);
    }
    assert!(
        e.breaks.iter().any(|c| !c.name.is_ascii()),
        "no non-ASCII name; the sample stopped covering them"
    );
}

/// Every `_private.` name in the package — the declarations and the tagged
/// constants both.
#[test]
fn private_names_match_the_prototype() {
    let e = expected();
    assert!(
        e.privates.len() >= 8,
        "only {} private names; plan §4 measured 8",
        e.privates.len()
    );
    for case in &e.privates {
        assert_eq!(
            private_to_user_name(&case.name),
            case.user_name,
            "privateToUserName({:?})",
            case.name
        );
        assert_eq!(
            module_from_private_prefix(&case.name),
            case.module.as_deref(),
            "moduleFromPrivatePrefix({:?})",
            case.name
        );
    }
}

/// Every span-carrying fragment of the target package, against the real IR.
///
/// `#[ignore]`d: it needs `LITEDOC4_FRAGMENT_FULL` to name the generator's
/// `--full` output, and that file is 29 MB and does not belong in the
/// repository.
///
/// This is the only place [`NameIndex`] is built the way a run builds it —
/// dependency slices, then declarations, then references — and the only place
/// the fragments are enumerated from the IR rather than read from a fixture, so
/// it is what stands behind the claim that the reduced worlds above are the
/// same thing in miniature.
#[test]
#[ignore = "corpus: needs LITEDOC4_FRAGMENT_FULL + LITEDOC4_IR (tools/corpus-gate.sh)"]
fn the_whole_corpus_matches_the_prototype() {
    let path = corpus::recording("LITEDOC4_FRAGMENT_FULL");
    let ir_dir = corpus::LITEDOC4_IR.path();

    #[derive(Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct Full {
        ir_fragments: usize,
        cases: Vec<FullCase>,
        kinds: Vec<KindCase>,
        breaks: Vec<BreakCase>,
        privates: Vec<PrivateCase>,
    }
    #[derive(Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct FullCase {
        what: String,
        html: String,
        has_anchor: bool,
    }

    let text = std::fs::read_to_string(&path).expect("LITEDOC4_FRAGMENT_FULL is readable");
    let full: Full = serde_json::from_str(&text).expect("the --full file is valid");

    let tree = IrTree::open(&ir_dir).expect("the IR opens");
    let modules = tree.load_modules().expect("every module reads");
    let mut builder = NameIndex::builder();
    for dep in tree.load_dep_maps().expect("every dependency slice reads") {
        builder.dep_map(&dep);
    }
    for module in &modules {
        builder.module(module);
    }
    // M7-c: the oracle is the frozen prototype, which had no dependency
    // map, so the comparison is against the **fallback** branch — which an
    // empty [`ExternalLinks`] reproduces byte for byte. A populated map
    // would move every link into a dependency, on purpose — doc-gen4 byte
    // compatibility is no longer required.
    // 2026-08-17: and the prototype rendered the whole environment, so its
    // links point at pages it wrote. A run's world has pages for the target
    // package alone; the oracle is resolved in the world it was recorded in.
    let index =
        builder.build_with_a_page_for_every_module(LinkIndex::default(), ExternalLinks::default());
    let renderer = CodeRenderer::new(&index);
    eprintln!("{} names in `known`", index.len());

    let mut compared = 0usize;
    let mut matched = 0usize;
    let mut failures = Vec::new();
    let mut check = |what: String, got: &Rendered| {
        let case = full.cases.get(compared);
        assert!(case.is_some(), "the IR has more fragments than the oracle");
        let case = case.expect("checked");
        assert_eq!(case.what, what, "the two sides walk the IR differently");
        compared += 1;
        if got.html == case.html && got.has_anchor == case.has_anchor {
            matched += 1;
        } else if failures.len() < 20 {
            failures.push(format!(
                "{what}\n  want: {}\n  got:  {}",
                show(&case.html),
                show(&got.html)
            ));
        }
    };

    // The same order the generator walks: binders, the type, the equations,
    // then each member's own text and binders. Members and equations resolve
    // against the *declaration's* references; they have none of their own.
    let empty: Vec<Span> = Vec::new();
    for module in &modules {
        let root = page_root(&module.module);
        for decl in &module.declarations {
            let refs = decl_refs(decl);
            let name = |what: &str| format!("{} {} {what}", module.module, decl.name);
            let mut one = |what: String, text: &Utf16Text, spans: &[Span]| {
                check(what, &renderer.fragment(text, spans, &root, &refs));
            };
            for (i, binder) in decl.binders.iter().enumerate() {
                one(
                    name(&format!("binder {i}")),
                    binder,
                    decl.binder_code.get(i).unwrap_or(&empty),
                );
            }
            one(name("type"), &decl.ty, &decl.type_code);
            for (i, equation) in decl.equations.iter().enumerate() {
                one(
                    name(&format!("equation {i}")),
                    equation,
                    decl.equation_code.get(i).unwrap_or(&empty),
                );
            }
            for (j, member) in decl.members.iter().enumerate() {
                let head = format!("member {j} {} {}", member.label, member.name);
                one(name(&head), &member.text, &member.code);
                for (k, binder) in member.binders.iter().enumerate() {
                    one(
                        name(&format!("{head} binder {k}")),
                        binder,
                        member.binder_code.get(k).unwrap_or(&empty),
                    );
                }
            }
        }
    }

    eprintln!("whole corpus: {matched} of {compared} match the prototype");
    assert_eq!(
        matched,
        compared,
        "{} differ:\n{}",
        compared - matched,
        failures.join("\n")
    );
    assert_eq!(
        compared, full.ir_fragments,
        "the IR walk produced a different number of fragments than the oracle"
    );
    assert_eq!(compared, 55_514, "the corpus changed size");

    // The three per-declaration functions over their whole populations too.
    for case in &full.kinds {
        assert_eq!(
            kind_description(&case.kind, &case.modifiers),
            case.description
        );
        assert_eq!(css_kind(&case.kind), case.css);
    }
    for case in &full.breaks {
        assert_eq!(break_within(&case.name), case.html, "{}", case.name);
    }
    for case in &full.privates {
        assert_eq!(private_to_user_name(&case.name), case.user_name);
        assert_eq!(
            module_from_private_prefix(&case.name),
            case.module.as_deref()
        );
    }
    eprintln!(
        "{} kind combinations / {} names / {} private names",
        full.kinds.len(),
        full.breaks.len(),
        full.privates.len()
    );
}
