//! Every answer in this file was produced by the TypeScript prototype, not by
//! the Rust code it checks.
//!
//! `tests/data/page-parts-expected.json` was generated by
//! `tests/oracle/gen-page-parts-expected.ts`, which sliced `declHeader`,
//! `declHtml`, `headHtml`, `pageHeaderHtml` and `internalNavHtml` out of the
//! frozen prototype and ran them over the **real** IR with the **real** `.lidx`.
//!
//! **The fixture is a frozen value: HEAD has no way to regenerate it.** The
//! generator and the prototype it drove were removed with `experiments/` on
//! 2026-08-16 and exist only at tag `experiments-frozen`.
//!
//! # Why the prototype and not doc-gen4
//!
//! Same reason as M1-d1: `docInfoToHtml` walks `DocInfo`s built from a live
//! environment, and the IR carries a flattened, already-printed form of them.
//! There is no input both implementations could be handed. The prototype is the
//! other consumer of that IR and it is the one scoring 439/439 (plan §1).
//!
//! # M8-b: the comparison is over content, not bytes
//!
//! Up to M7 every assertion here was `got == want`. **M8-b rewrote the markup
//! on purpose** (`docs/plans/ui-redesign.md`), so that comparison can no longer
//! hold and gate A is finished (plan §1). What survives it is everything the
//! prototype's bytes *said* rather than how they said it, and that is what is
//! compared now:
//!
//! | | how |
//! |---|---|
//! | the anchors a page defines | the `id` attributes, **in order**, with the instance stubs' taken out — M8-c keys those off `data-name` instead |
//! | where every link goes | the `href` attributes, **in order**, with the two the head swapped |
//! | what a reader sees | the words with the tags stripped, as a **multiset** |
//! | what the instance stubs are for | the names the stubs carry |
//!
//! Two of the three are ordered, which is what keeps this from degenerating into
//! "the same pieces, somewhere". The word list is not: the head reordered (the
//! source link moved into it) and comparing it in order would only be asserting
//! that reordering, which is the change itself. **This is weaker than the byte
//! comparison it replaces** — a class name, an element or an attribute can move
//! without failing here — and it is the strength the oracle actually has now
//! that the two sides are not trying to be the same document.
//!
//! # The two halves
//!
//! - The committed fixture is self-contained. Each case carries the three
//!   sources of its world reduced to the names it looks up, plus the module
//!   file reduced to what `containedNames` and `moduleDeclNames` read, and the
//!   generator proves each reduction faithful by re-rendering with it.
//! - [`the_whole_corpus_carries_the_prototypes_content`] runs **all 4,750
//!   headers, all 4,560 declaration blocks and all 432 frames** against the real
//!   IR. It is `#[ignore]`d and needs `LITEDOC4_PAGE_PARTS_FULL` to point at
//!   the generator's `--full` output (77 MB, which does not belong in the
//!   repository).
//!
//! # What the real corpus does not reach
//!
//! **Nine of the 41 branches never fire** over the whole package
//! (`branchTotals` in the fixture): there is no `class`, no `inductive` and no
//! `class_inductive` declaration, no structure whose constructor is not `mk`,
//! no structure without a `ctor` member, no inherited field whose projection is
//! declared inside the structure's range, no implicit binder on a field, and no
//! module without imports. A mutation to any of them is invisible to real data,
//! and [`the_curated_cases_cover_what_the_package_does_not`] refuses to let
//! that quietly stop being true.

use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::path::PathBuf;

use litedoc4_ir::{Decl, IrTree, ModuleFile};
use litedoc4_render::autolink::{NameIndex, PageLinks, module_decl_names, page_root};
use litedoc4_render::code::CodeRenderer;
use litedoc4_render::decl::{DeclRenderer, UnplaceableName, decl_head_html, decl_signature};
use litedoc4_render::frame::{module_head_html, module_meta_html, module_source_url, sidebar_html};
use litedoc4_render::{ExternalLinks, LinkIndex, SiteMeta, head_html, topbar_html};
use serde::Deserialize;

const FIXTURE: &str = include_str!("data/page-parts-expected.json");

const DEFAULT_IR: &str = "/private/tmp/lean-doc-relay/w7h/base-ir";
const DEFAULT_LINK_INDEX: &str = "/private/tmp/lean-doc-relay/w7c/linkindex/link-index.lidx";

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    oracle: String,
    /// The revision prefix the source links were built with. 40 hex digits, or
    /// `coverage.ts` scores the tree lower (plan 決定 1).
    source_url: String,
    ir_modules: usize,
    /// Declarations in the IR — the `declHeader` denominator.
    ir_declarations: usize,
    /// Declarations that get a page entry — the `declHtml` denominator.
    page_declarations: usize,
    /// Names that appear as some declaration's member, across **every** module.
    suppressed_declarations: usize,
    known_entries: usize,
    link_index_entries: usize,
    known_modules: usize,
    /// How often each branch fires over the whole corpus.
    branch_totals: BTreeMap<String, u64>,
    /// How often each fires over the hand-written cases.
    curated_branches: BTreeMap<String, u64>,
    /// The branches with a zero in `branch_totals`, as the generator listed
    /// them. Stored as well as derivable so that a disagreement between the two
    /// is itself a failure.
    never_fires: BTreeSet<String>,
    cases: Vec<Case>,
    frames: Vec<Frame>,
}

/// One declaration, and the whole world it renders against.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Case {
    what: String,
    root: String,
    source_url: String,
    /// The module file, reduced: the rendered declaration verbatim, plus
    /// name/range/index stubs for the siblings when they turn out to matter.
    module: ModuleFile,
    /// Which declaration of `module` is rendered.
    at: usize,
    /// The IR's name -> module map.
    known: BTreeMap<String, String>,
    /// The dependency closure's map, as `.lidx` text.
    lidx: String,
    /// Module names contributed by the IR itself.
    ir_modules: Vec<String>,
    header: String,
    html: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Frame {
    what: String,
    module: String,
    root: String,
    source_url: String,
    imports: Vec<String>,
    member_names: Vec<String>,
    head: String,
    /// The prototype's `pageHeaderHtml`. Only two things in it survived M8-b:
    /// the module's name, which moved to the heading in `main`, and the search
    /// form, which stayed in the top bar.
    header: String,
    nav: String,
}

impl Case {
    /// The case's [`NameIndex`], built from its three sources the way a run
    /// builds it from the IR and the `.lidx`.
    fn index(&self) -> NameIndex {
        let mut builder = NameIndex::builder();
        for module in &self.ir_modules {
            builder.module_name(module);
        }
        for (name, module) in &self.known {
            builder.declaration(name, module);
        }
        // M7-c: the prototype had no dependency map, so its bytes are the
        // **fallback** branch — which an empty [`ExternalLinks`] reproduces
        // exactly. With a map every link into a dependency moves, on purpose
        // (`docs/implementation-plan.md` §1).
        //
        // 2026-08-17: and the prototype rendered the whole environment, so its
        // links point at pages it wrote. A run's world has pages for the target
        // package alone; the oracle is resolved in the world it was recorded in.
        builder.build_with_a_page_for_every_module(
            LinkIndex::parse(&self.lidx),
            ExternalLinks::default(),
        )
    }

    /// The head and the signature, which together are what `declHeader` was:
    /// M8-b split it in two because they wrap differently, and moved the source
    /// link out of the block's own `div.gh_link` into the head.
    fn head_and_signature(&self) -> String {
        let index = self.index();
        let decl = &self.module.declarations[self.at];
        let code = CodeRenderer::new(&index);
        let mut out = decl_head_html(
            decl,
            &page_root(&self.module.module),
            &self.module.module,
            &self.source_url,
        );
        out.push_str(&decl_signature(
            decl,
            &page_root(&self.module.module),
            &code,
        ));
        out
    }

    fn render(&self) -> Result<String, UnplaceableName> {
        let index = self.index();
        let decl = &self.module.declarations[self.at];
        let code = CodeRenderer::new(&index);
        let names = module_decl_names(&self.module);
        let links = PageLinks::new_unchecked(&index, &self.root, &names);
        let docs = links.renderer();
        let renderer = DeclRenderer::new(&self.module, &self.root, &self.source_url, code, &docs);
        renderer.decl_html(decl)
    }
}

impl Frame {
    fn names(&self) -> Vec<&str> {
        self.member_names.iter().map(String::as_str).collect()
    }
}

fn expected() -> Expected {
    serde_json::from_str(FIXTURE).expect("tests/data/page-parts-expected.json is valid")
}

#[test]
fn fixture_is_the_prototypes_own_output() {
    let e = expected();
    assert!(e.oracle.contains("render.ts"), "{}", e.oracle);
    assert!(e.oracle.contains("declHtml"), "{}", e.oracle);
    assert!(
        e.cases.len() >= 150,
        "only {} cases; the sample stopped covering the corpus",
        e.cases.len()
    );
    assert!(
        e.cases
            .iter()
            .filter(|c| c.what.starts_with("curated: "))
            .count()
            >= 18,
        "the hand-written cases are what reach the corners the package has none of"
    );
    assert!(
        e.frames
            .iter()
            .filter(|f| f.what.starts_with("curated: "))
            .count()
            >= 4
    );
    // Plan 決定 1: a tag or a branch here silently lowers the acceptance score,
    // because `coverage.ts` normalises `/blob/[0-9a-f]{40}/` and nothing else.
    let rev = e
        .source_url
        .rsplit_once("/blob/")
        .expect("the source URL is a /blob/<rev> prefix")
        .1;
    assert_eq!(rev.len(), 40, "{rev} is not a 40-hex revision");
    assert!(rev.bytes().all(|b| b.is_ascii_hexdigit()), "{rev}");
}

/// What the corpus is, pinned so that a number quoted anywhere else can be
/// traced to a run of the generator rather than to a memory of one.
///
/// **Two denominators, not one.** `declHeader` is computed for every
/// declaration in the IR; `declHtml` only for those that get a page entry,
/// which is the IR minus `suppressed` — the names that appear as some other
/// declaration's member, collected **across every module** (`render.ts`
/// 2043-2048). Collecting it per module leaves other modules' projections and
/// constructors on the page (plan §5).
#[test]
fn the_corpus_numbers_are_what_was_measured() {
    let e = expected();
    assert_eq!(e.ir_modules, 432);
    assert_eq!(e.ir_declarations, 4_750, "the declHeader denominator");
    assert_eq!(e.page_declarations, 4_560, "the declHtml denominator");
    assert_eq!(
        e.suppressed_declarations,
        e.ir_declarations - e.page_declarations,
        "every suppressed name is a declaration of some module, so the set's size \
         is exactly the number of pages entries lost"
    );
    // 実測. `render.ts:2042` says 186 in a comment; that number is older than
    // this IR, and the set is what was counted here.
    assert_eq!(e.suppressed_declarations, 190);
    assert_eq!(e.known_entries, 5_296, "names in `known`");
    assert_eq!(e.link_index_entries, 258_760, "names in the .lidx");
    assert_eq!(e.known_modules, 6_158);

    assert_eq!(
        e.branch_totals,
        BTreeMap::from(
            [
                // declHeader
                ("anchorsBreakWithin", 4_750),
                ("implArgs", 31_185),
                ("headerExplicitArg", 18_119),
                ("headerNoBinders", 106),
                ("extendsRendered", 1),
                ("headerStructureWithoutParents", 36),
                // declHtml
                ("ghLinks", 4_560),
                ("docstringsRendered", 3_277),
                ("declWithoutDocstring", 1_283),
                ("attributeBlocks", 104),
                ("attributeItems", 126),
                ("declWithoutAttributes", 4_456),
                ("kindStructure", 37),
                ("kindClass", 0),
                ("kindDefinition", 801),
                ("kindInstance", 91),
                ("kindInductive", 0),
                ("kindClassInductive", 0),
                ("kindOther", 3_631),
                // equationsHtml
                ("equationBlocks", 804),
                ("equationItems", 552),
                ("equationsOmittedNotices", 270),
                ("equationsDroppedOverLimit", 270),
                ("equationsAbsent", 88),
                // structureHtml / fieldToHtml
                ("memberTables", 37),
                ("memberFields", 156),
                ("memberFieldArgs", 49),
                ("memberFieldDocs", 117),
                ("memberFieldsInherited", 4),
                ("memberFieldsInheritedWithId", 0),
                ("fieldDirect", 152),
                ("fieldImplicitArg", 0),
                ("structureFieldsMk", 37),
                ("structureExt", 0),
                ("structureCtorMissing", 0),
                // the two stubs
                ("instancesForStubs", 838),
                ("classInstancesStubs", 0),
                // internalNavHtml
                ("navLinks", 4_560),
                ("importListItems", 3_503),
                ("importDuplicatesDropped", 432),
                ("navWithoutImports", 0),
                ("navWithoutMembers", 26),
            ]
            .map(|(k, n)| (k.to_owned(), n))
        ),
        "the branch profile of the corpus changed"
    );

    // Cross-checks between counters that have to agree by construction.
    assert_eq!(
        e.branch_totals["ghLinks"], e.page_declarations as u64,
        "every rendered declaration gets exactly one source link"
    );
    assert_eq!(
        e.branch_totals["navLinks"], e.page_declarations as u64,
        "and exactly one nav entry"
    );
    assert_eq!(
        e.branch_totals["anchorsBreakWithin"], e.ir_declarations as u64,
        "every header, page entry or not, links to itself"
    );
    assert_eq!(
        e.branch_totals["docstringsRendered"] + e.branch_totals["declWithoutDocstring"],
        e.page_declarations as u64
    );
    assert_eq!(
        e.branch_totals["fieldDirect"] + e.branch_totals["memberFieldsInherited"],
        e.branch_totals["memberFields"]
    );
    assert_eq!(
        e.branch_totals["kindStructure"] + e.branch_totals["kindClass"],
        e.branch_totals["memberTables"],
        "a members table comes from a structure or a class and from nothing else"
    );
    assert_eq!(
        e.branch_totals["instancesForStubs"],
        e.branch_totals["kindStructure"]
            + e.branch_totals["kindDefinition"]
            + e.branch_totals["kindInductive"]
    );
}

/// The comparison this file exists for, over the committed sample: every
/// declaration block says what the fixture's says.
///
/// **The fixture was the prototype's output until 2026-08-22 and is this
/// renderer's now** (`docs/plans/feature-sweep.md` §3【決定 1】/ C-4).
/// Feature-sweep C-2 gives every declaration a `Used by` block, so all 187 of
/// these cases gained a stub the prototype could not have had — the role of
/// this file changed **once**, deliberately, and `bless` below is what makes the
/// next change a regeneration rather than a decision.
///
/// `tests/data/PROVENANCE.md` asked for exactly this: "replace the fixture with
/// a regression test against our own output and say in the test name that the
/// oracle was lost". The name says it.
///
/// See the file heading for what "says" is reduced to. The header half is
/// compared separately from the block, because the fixture records it
/// separately and because it is the one place the *content* really did move —
/// M8-b put the source link in the head, where the prototype had it in a
/// `div.gh_link` above the block. **The header half is not blessed**: nothing in
/// bundle C touches a declaration's head or signature, and a regenerator that
/// rewrote it too would have hidden that.
/// Where two strings first differ, with a window either side.
///
/// The blocks are kilobytes long and a failure that printed both of them whole
/// would be unreadable, which is the same thing as unreported.
fn first_difference(want: &str, got: &str) -> String {
    let at = want
        .bytes()
        .zip(got.bytes())
        .position(|(a, b)| a != b)
        .unwrap_or_else(|| want.len().min(got.len()));
    let window = |text: &str| -> String {
        let start = text.floor_char_boundary(at.saturating_sub(40));
        let end = text.floor_char_boundary((at + 90).min(text.len()));
        text[start..end].to_owned()
    };
    format!(
        "byte {at} of {} (frozen) / {} (here)\n  frozen: …{}…\n  here:   …{}…",
        want.len(),
        got.len(),
        window(want),
        window(got)
    )
}

/// Rewrites `tests/data/page-parts-expected.json` from this renderer's output,
/// and **prints every case it changed**.
///
/// `LITEDOC4_BLESS=1 cargo test -p litedoc4-render --test page_parts`
///
/// The printing is the point: the fixture is one 840 KB line, so `git diff` of
/// it is not a review. What `docs/plans/feature-sweep.md` §3 asks for — *what
/// changed and because of which item* — is read out of this output.
///
/// **Only `html` is rewritten.** `header` is the same fixture's record of the
/// head and signature, and bundle C does not touch either; blessing it as well
/// would have made that unfalsifiable.
///
/// It is **idempotent, and asserts that it is** — twice: the file must
/// re-serialise to itself *before* any edit (or every value would arrive with a
/// different spelling and the real change would be lost among them), and what is
/// written must round-trip.
fn bless(e: &Expected) {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data/page-parts-expected.json");
    let original = std::fs::read_to_string(&path).expect("the fixture is readable");
    let mut document: serde_json::Value =
        serde_json::from_str(&original).expect("the fixture is JSON");
    let round_trip = serde_json::to_string(&document).expect("it came from JSON") + "\n";
    assert_eq!(
        round_trip, original,
        "re-serialising the fixture does not reproduce it; blessing would rewrite \
         the whole file and no diff of it could be reviewed"
    );

    let cases = document
        .get_mut("cases")
        .and_then(serde_json::Value::as_array_mut)
        .expect("the fixture has cases");
    let mut changed = 0usize;
    let mut head_moved = Vec::new();
    for (case, value) in e.cases.iter().zip(cases.iter_mut()) {
        if Content::of(&case.header)
            .matches_head(&Content::of(&case.head_and_signature()))
            .is_err()
        {
            head_moved.push(case.what.clone());
        }
        let got = case.render().expect("every case renders");
        if got == case.html {
            continue;
        }
        changed += 1;
        println!(
            "bless {}\n  {} B -> {} B",
            case.what,
            case.html.len(),
            got.len()
        );
        value["html"] = serde_json::Value::String(got);
    }
    assert!(
        head_moved.is_empty(),
        "the head or signature moved on {} case(s), which no item of bundle C does — \
         look at that before regenerating: {:?}",
        head_moved.len(),
        &head_moved[..head_moved.len().min(5)]
    );
    let updated = serde_json::to_string(&document).expect("values are strings") + "\n";
    std::fs::write(&path, &updated).expect("the fixture is writable");
    println!(
        "bless: {changed} of {} case(s) rewritten in {}",
        e.cases.len(),
        path.display()
    );
    assert_eq!(
        serde_json::to_string(
            &serde_json::from_str::<serde_json::Value>(&updated).expect("what was written is JSON")
        )
        .expect("round trip")
            + "\n",
        updated,
        "the file this wrote does not round-trip"
    );
}

#[test]
fn carries_the_same_content_as_the_frozen_output() {
    let e = expected();
    if std::env::var("LITEDOC4_BLESS").is_ok_and(|value| value == "1") {
        bless(&e);
        return;
    }
    let mut failures = Vec::new();
    let mut compared = 0usize;
    let (mut ids, mut hrefs, mut stubs, mut words) = (0usize, 0usize, 0usize, 0usize);
    for case in &e.cases {
        let want = Content::of(&case.header);
        let got = Content::of(&case.head_and_signature());
        // The head gained the source link, which is one href and the word
        // `source`. Nothing else about it may have moved.
        if let Err(why) = want.matches_head(&got) {
            failures.push(format!("{} (head + signature): {why}", case.what));
        }
        match case.render() {
            Ok(html) => {
                // **Byte for byte, now that both sides are ours.** `Content` was
                // the bridge between two different markups — the prototype wrote
                // `div.decl` where this writes `section.decl[data-kind]` — and a
                // bridge between a thing and itself only loses information. The
                // counters below still come from `Content`, because what they
                // guard is that the *sample* has not shrunk.
                if html != case.html {
                    failures.push(format!(
                        "{}: {}",
                        case.what,
                        first_difference(&case.html, &html)
                    ));
                }
                let want = Content::of(&case.html);
                ids += want.ids.len();
                hrefs += want.hrefs.len();
                stubs += want.stubs.len();
                words += want.words.len();
                compared += 1;
            }
            Err(e) => failures.push(format!("{}: {e}", case.what)),
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ from the frozen output:\n{}\n\n\
         If the change is intended, regenerate with:\n    \
         LITEDOC4_BLESS=1 cargo test -p litedoc4-render --test page_parts",
        failures.len(),
        e.cases.len(),
        failures.join("\n")
    );
    assert_eq!(compared, e.cases.len(), "a case did not render at all");
    // The sample's size, so that a fixture regenerated from a renderer that had
    // stopped emitting things cannot pass by being uniformly empty.
    // 【実測 2026-08-16 over the prototype's markup: 220 anchors, 1,011 links,
    // 30 stubs, 4,587 words. The numbers moved when C-4 re-froze the fixture on
    // this renderer's own output — the bounds below are the floor, not the
    // measurement.】
    eprintln!("compared {ids} anchors, {hrefs} links, {stubs} stubs, {words} words");
    assert!(
        ids > 200 && hrefs > 900 && stubs > 25 && words > 4_000,
        "{ids} anchors, {hrefs} links, {stubs} stubs, {words} words: the sample shrank"
    );
}

/// The frame, part by part. The prototype had three pieces and this crate has
/// five, so they are matched by what they carry rather than one to one:
///
/// | the prototype's | here |
/// |---|---|
/// | `<title>` | `<title>`, which now also names the site |
/// | the search form's `action` | the top bar's search form |
/// | `p.gh_nav_link` | the module heading's `a.src` |
/// | the import list | the import list |
/// | the `imported-by` stub | the `imported-by` stub |
/// | one `div.nav_link` per page entry | the sidebar's table of contents |
///
/// `page_root` and `module_source_url` are still compared byte for byte: they
/// are pure functions of a module name that M8-b did not touch, and they decide
/// where every other link on the page points.
#[test]
fn frames_carry_the_same_content_as_the_prototype() {
    let e = expected();
    let site = SiteMeta::default();
    let mut failures = Vec::new();
    for frame in &e.frames {
        let mut fail = |what: &str, want: String, got: String| {
            failures.push(format!(
                "{} ({what})\n  want: {want}\n  got:  {got}",
                frame.what
            ));
        };

        // The title still names the module, and the head still names nothing
        // outside the page's own root — which the prototype's did not (four
        // CDN scripts, plan §2.2).
        let head = head_html(&frame.module, &frame.root, &site);
        let want_title = between(&frame.head, "<title>", "</title>").unwrap_or_default();
        let got_title = between(&head, "<title>", "</title>").unwrap_or_default();
        if !got_title.starts_with(want_title) {
            fail("title", want_title.to_owned(), got_title.to_owned());
        }
        for href in attr_values(&head, "href")
            .into_iter()
            .chain(attr_values(&head, "src"))
        {
            if !href.starts_with(&frame.root) {
                fail(
                    "head asset",
                    format!("under {}", frame.root),
                    href.to_owned(),
                );
            }
        }

        // The search form still goes to the site's own search page.
        let bar = topbar_html(&frame.root, &site, true);
        let want_action = format!("{}search.html", frame.root);
        if !bar.contains(&format!("action=\"{want_action}\"")) {
            fail("search action", want_action, bar.clone());
        }

        // The module's source link, which the prototype kept in the nav.
        let want_src = frame
            .nav
            .find("gh_nav_link")
            .and_then(|at| attr_values(&frame.nav[at..], "href").first().copied())
            .unwrap_or_default()
            .to_owned();
        let modhead = module_head_html(&frame.module, &frame.source_url);
        let got_src = attr_values(&modhead, "href")
            .first()
            .copied()
            .unwrap_or_default()
            .to_owned();
        if got_src != want_src {
            fail("source link", want_src, got_src);
        }

        // The page still spells out which module it is. The prototype put it in
        // `h2.header_filename` at the top of the window; it is the `<h1>` of the
        // content column now, and the spelling — one `span.name` per component
        // — is [`litedoc4_render::break_within`]'s on both sides.
        let want_name = between(&frame.header, "header_filename break_within\">", "</h2>")
            .map(|name| words(name).join(" "))
            .unwrap_or_default();
        let got_name = between(&modhead, "<h1>", "</h1>")
            .map(|name| words(name).join(" "))
            .unwrap_or_default();
        if got_name != want_name {
            fail("module name", want_name, got_name);
        }

        // The import list: the same modules, in the same order, at the same
        // hrefs. M7-c: the prototype's are all relative, and the empty map is
        // what reproduces that (see `Case::index`). 2026-08-17: the prototype
        // wrote a page for every module it named, so this frame's world is one
        // where each of its imports has one — a run's would not, and that is the
        // difference the fix is about.
        let mut builder = NameIndex::builder();
        for import in &frame.imports {
            builder.module_name(import);
        }
        let index = builder.build(LinkIndex::default(), ExternalLinks::default());
        let meta = module_meta_html(&frame.root, &frame.imports, &index);
        let want_imports = list_items(&frame.nav, "<summary>Imports</summary><ul>");
        let got_imports = list_items(&meta, "<ul>");
        if want_imports != got_imports {
            fail(
                "imports",
                format!("{want_imports:?}"),
                format!("{got_imports:?}"),
            );
        }
        if !meta.contains("data-fill=\"imported-by\"") {
            fail(
                "imported-by stub",
                "a placeholder the script fills".to_owned(),
                meta.clone(),
            );
        }

        // One entry per page declaration, in page order.
        let sidebar = sidebar_html(&frame.root, &frame.names());
        let want_entries: Vec<String> = frame
            .nav
            .match_indices("class=\"nav_link\"")
            .filter_map(|(at, _)| attr_values(&frame.nav[at..], "href").first().copied())
            .map(str::to_owned)
            .collect();
        let got_entries: Vec<String> = between(&sidebar, "<ul class=\"toc\">", "</ul>")
            .map(|toc| {
                attr_values(toc, "href")
                    .into_iter()
                    .map(str::to_owned)
                    .collect()
            })
            .unwrap_or_default();
        if want_entries != got_entries {
            fail(
                "page entries",
                format!("{want_entries:?}"),
                format!("{got_entries:?}"),
            );
        }

        // Unchanged pure functions, still compared byte for byte.
        if page_root(&frame.module) != frame.root {
            fail("root", frame.root.clone(), page_root(&frame.module));
        }
        let source_url = module_source_url(&e.source_url, &frame.module);
        if source_url != frame.source_url {
            fail("sourceUrl", frame.source_url.clone(), source_url);
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} frames differ from the prototype:\n{}",
        failures.len(),
        e.frames.len(),
        failures.join("\n")
    );
}

/// The nine branches no real declaration or module reaches, and the fact that
/// the curated cases do reach them.
#[test]
fn the_curated_cases_cover_what_the_package_does_not() {
    let e = expected();
    let never: BTreeSet<String> = e
        .branch_totals
        .iter()
        .filter(|(_, n)| **n == 0)
        .map(|(k, _)| k.clone())
        .collect();
    assert_eq!(
        never, e.never_fires,
        "the generator and the totals disagree about which branches are dead"
    );
    assert_eq!(
        never,
        BTreeSet::from(
            [
                "classInstancesStubs",
                "fieldImplicitArg",
                "kindClass",
                "kindClassInductive",
                "kindInductive",
                "memberFieldsInheritedWithId",
                "navWithoutImports",
                "structureCtorMissing",
                "structureExt",
            ]
            .map(str::to_owned)
        ),
        "which branches the target package never reaches has changed"
    );
    for branch in &never {
        assert!(
            e.curated_branches.get(branch).copied().unwrap_or(0) > 0,
            "{branch} fires nowhere in the corpus and nowhere in the curated cases either: \
             nothing would catch a mutation to it"
        );
    }
    // And the curated set reaches everything, not only the nine.
    let all: BTreeSet<&String> = e.branch_totals.keys().collect();
    let curated: BTreeSet<&String> = e
        .curated_branches
        .iter()
        .filter(|(_, n)| **n > 0)
        .map(|(k, _)| k)
        .collect();
    assert_eq!(all, curated, "the curated cases stopped covering a branch");
}

/// The sample has to keep reaching every shape, or the comparison above decays
/// into one that a renderer emitting only headers would pass.
///
/// Every assertion here reads the **fixture's own bytes**. Until 2026-08-22
/// those were the prototype's and the probes below named its classes
/// (`div.decl_header`, `ul.structure_fields`, `span.impl_arg`); C-4 re-froze the
/// file on this renderer's output, so they name this renderer's. **The shapes
/// they stand for are the same ones** — that is what makes this a translation of
/// the test rather than a weakening of it, and every probe still has to match at
/// least one case or the sample lost that shape.
///
/// One probe did not survive the translation and is gone rather than reworded:
/// "an attribute block ending in a newline". It stood for the prototype's one
/// unflattened element, and this renderer flattens everything — there is no
/// newline anywhere in a declaration block to look for.
#[test]
fn the_sample_reaches_every_shape() {
    let e = expected();
    let any = |what: &str, p: &dyn Fn(&Case) -> bool| {
        assert!(e.cases.iter().any(p), "no case with {what}");
    };

    any("an attribute block before the signature", &|c| {
        c.html.contains("<div class=\"attrs\">@[")
    });
    any("more than one attribute", &|c| {
        c.html.contains("<div class=\"attrs\">@[")
            && c.html
                .split("<div class=\"attrs\">@[")
                .nth(1)
                .is_some_and(|s| s[..s.find(']').unwrap_or(0)].contains(", "))
    });
    any("an equations block", &|c| {
        c.html.contains("<ul class=\"equations\">")
    });
    any("the over-the-limit notice", &|c| {
        c.html
            .contains("One or more equations did not get rendered")
    });
    any("an instances-for stub", &|c| {
        c.html.contains("data-fill=\"instances-for\"")
    });
    any("a class instances stub", &|c| {
        c.html.contains("data-fill=\"instances\"")
    });
    // C-2's own shape, on every declaration whatever its kind.
    any("a used-by stub", &|c| {
        c.html.contains("data-fill=\"used-by\"")
    });
    any("an extends clause", &|c| {
        c.html.contains("<span class=\"extends\">extends</span> ")
    });
    any("two parents joined by a comma", &|c| {
        c.html.contains("</span>, <span id=\"")
    });
    any("a members table in `mk` form", &|c| {
        c.html.contains("<ul class=\"fields\" id=\"") && !c.html.contains("class=\"ctor-note\"")
    });
    any("a members table whose constructor is not `mk`", &|c| {
        c.html.contains("class=\"ctor-note\"")
    });
    any("a direct field", &|c| {
        c.html.contains("\" class=\"field\">")
    });
    any("a field docstring", &|c| {
        c.html.contains("class=\"field-doc\"")
    });
    any("an inherited field without an id", &|c| {
        c.html.contains("<li class=\"field inherited\">")
    });
    any("an inherited field with an id", &|c| {
        c.html.contains("\" class=\"field inherited\">")
    });
    any("an implicit binder", &|c| {
        c.html.contains("<span class=\"binder implicit\">")
    });
    any("a docstring", &|c| c.html.contains("<p>"));
    any("a name that needs escaping", &|c| {
        c.html
            .starts_with("<section class=\"decl\" id=\"A&lt;B&amp;C")
    });

    // An unlinkable constant in a signature, which is a `span.fn` and not an
    // anchor. Every block has at least the header's own `break_within` link, so
    // "no anchor at all" is not a shape a declaration can have.
    any("an unlinkable constant", &|c| {
        c.html.contains("<span class=\"fn\">")
    });

    // Every kind `cssKind` can produce, since it is a second mapping next to
    // `kindDescription` and collapsing the two is the obvious mistake. It is an
    // attribute here and was a class in the prototype's markup.
    let classes: BTreeSet<&str> = e
        .cases
        .iter()
        .filter_map(|c| {
            let at = c.html.find("data-kind=\"")? + 11;
            let end = c.html[at..].find('"')? + at;
            Some(&c.html[at..end])
        })
        .collect();
    // `ctor` is absent on purpose: a constructor is always some structure's
    // `ctor` member, so it is in `suppressed` and never gets a page entry.
    for want in [
        "def",
        "class",
        "theorem",
        "structure",
        "instance",
        "inductive",
        "opaque",
    ] {
        assert!(
            classes.contains(want),
            "no `data-kind={want}`; got {classes:?}"
        );
    }
    assert!(
        !classes.contains("definition") && !classes.contains("class_inductive"),
        "`cssKind` collapsed into the identity: {classes:?}"
    );

    // Every root the pages use, since it prefixes every link in a header.
    let roots: BTreeSet<&str> = e.cases.iter().map(|c| c.root.as_str()).collect();
    assert!(roots.len() >= 5, "only {roots:?}");
    let frame_roots: BTreeSet<&str> = e.frames.iter().map(|f| f.root.as_str()).collect();
    assert!(frame_roots.len() >= 5, "only {frame_roots:?}");

    // The frames' own corners.
    assert!(
        e.frames
            .iter()
            .any(|f| f.imports.len() != f.imports.iter().collect::<BTreeSet<_>>().len()),
        "no frame with a duplicate import; the de-duplication would be untested"
    );
    assert!(
        e.frames.iter().any(|f| f.imports.is_empty()),
        "no frame without imports"
    );
    assert!(
        e.frames.iter().any(|f| f.member_names.is_empty()),
        "no frame without page entries"
    );
    assert!(
        e.frames.iter().any(|f| f.module.contains('<')),
        "no module name that needs escaping"
    );
    assert!(
        e.frames
            .iter()
            .any(|f| f.member_names.iter().any(|n| n.contains('"'))),
        "no member name that needs escaping"
    );
}

/// Every header, every declaration block and every frame of the target package,
/// against the real IR and the real `.lidx`.
///
/// `#[ignore]`d: it needs `LITEDOC4_PAGE_PARTS_FULL` to name the generator's
/// `--full` output, and that file is 77 MB and does not belong in the
/// repository.
///
/// This is the only place the whole-run inputs are built the way a run builds
/// them — the name index from the dependency slices, the modules and the
/// `.lidx`; `suppressed` from **every** module — so it is what stands behind
/// the claim that the reduced worlds above are the same thing in miniature.
///
/// Compared over content since M8-b, exactly as the committed sample is.
#[test]
#[ignore = "corpus: needs LITEDOC4_PAGE_PARTS_FULL + LITEDOC4_IR + LITEDOC4_LINK_INDEX (tools/corpus-gate.sh)"]
fn the_whole_corpus_carries_the_prototypes_content() {
    let path = std::env::var("LITEDOC4_PAGE_PARTS_FULL").unwrap_or_else(|_| {
        panic!(
            "set LITEDOC4_PAGE_PARTS_FULL to a `--full` recording made by the generator at tag \
             experiments-frozen (HEAD cannot make one), or run this test through \
             tools/corpus-gate.sh, which is the only thing that should be asking for it"
        )
    });
    let ir_dir = PathBuf::from(std::env::var("LITEDOC4_IR").unwrap_or_else(|_| DEFAULT_IR.into()));
    let lidx_path = PathBuf::from(
        std::env::var("LITEDOC4_LINK_INDEX").unwrap_or_else(|_| DEFAULT_LINK_INDEX.into()),
    );

    #[derive(Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct Full {
        source_url: String,
        ir_declarations: usize,
        page_declarations: usize,
        headers: Vec<FullHeader>,
        decls: Vec<FullDecl>,
        frames: Vec<FullFrame>,
    }
    #[derive(Deserialize)]
    struct FullHeader {
        what: String,
        html: String,
    }
    #[derive(Deserialize)]
    struct FullDecl {
        what: String,
        header: String,
        html: String,
    }
    #[derive(Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct FullFrame {
        module: String,
        member_names: Vec<String>,
        head: String,
        nav: String,
    }

    let text = std::fs::read_to_string(&path).expect("LITEDOC4_PAGE_PARTS_FULL is readable");
    let full: Full = serde_json::from_str(&text).expect("the --full file is valid");

    let tree = IrTree::open(&ir_dir).expect("the IR opens");
    let modules = tree.load_modules().expect("every module reads");
    let links = LinkIndex::read(&lidx_path).expect("the .lidx reads");
    let mut builder = NameIndex::builder();
    for dep in tree.load_dep_maps().expect("every dependency slice reads") {
        builder.dep_map(&dep);
    }
    for module in &modules {
        builder.module(module);
    }
    // M7-c: the prototype had no dependency map, so its bytes are the
    // **fallback** branch — which an empty [`ExternalLinks`] reproduces
    // exactly. With a map every link into a dependency moves, on purpose
    // (`docs/implementation-plan.md` §1).
    //
    // 2026-08-17: the prototype also rendered the whole environment, so its
    // relative links into `Mathlib.*` point at pages it wrote. A run's world has
    // pages for the target package alone and would draw none of them, so the
    // oracle is compared in the world it was recorded in.
    let index = builder.build_with_a_page_for_every_module(links, ExternalLinks::default());
    let code = CodeRenderer::new(&index);

    // `render.ts:2043-2048` — across **every** module, which is why it cannot
    // be folded into the per-module loop below.
    let suppressed: HashSet<&str> = modules
        .iter()
        .flat_map(|m| &m.declarations)
        .flat_map(|d| &d.members)
        .map(|m| m.name.as_str())
        .collect();

    let site = SiteMeta::of_modules(modules.iter().map(|module| module.module.as_str()));

    let mut headers = 0usize;
    let mut decls = 0usize;
    let mut failures: Vec<String> = Vec::new();
    let note = |failures: &mut Vec<String>, what: &str, why: &str| {
        if failures.len() < 10 {
            failures.push(format!("{what}: {why}"));
        }
    };

    for (at, module) in modules.iter().enumerate() {
        let root = page_root(&module.module);
        let source_url = module_source_url(&full.source_url, &module.module);
        let names = module_decl_names(module);
        let page_links = PageLinks::new(&index, &root, &names);
        let docs = page_links.renderer();
        let renderer = DeclRenderer::new(module, &root, &source_url, code, &docs);

        // Every declaration's header, in IR order.
        for decl in &module.declarations {
            let want = full
                .headers
                .get(headers)
                .unwrap_or_else(|| panic!("the IR has more declarations than the oracle"));
            let what = format!("{} {} header", module.module, decl.name);
            assert_eq!(want.what, what, "the two sides walk the IR differently");
            let mut got = decl_head_html(
                decl,
                &page_root(&module.module),
                &module.module,
                &source_url,
            );
            got.push_str(&decl_signature(decl, &page_root(&module.module), &code));
            if let Err(why) = Content::of(&want.html).matches_head(&Content::of(&got)) {
                note(&mut failures, &what, &why);
            }
            headers += 1;
        }

        // Every declaration that gets a page entry, in page order.
        let mut page_decls: Vec<&Decl> = module
            .declarations
            .iter()
            .filter(|d| !suppressed.contains(d.name.as_str()))
            .collect();
        page_decls.sort_by_key(|d| (d.line, d.col, d.index));
        for decl in &page_decls {
            let want = full
                .decls
                .get(decls)
                .unwrap_or_else(|| panic!("the IR has more page entries than the oracle"));
            let what = format!("{} {}", module.module, decl.name);
            assert_eq!(want.what, what, "the two sides order the page differently");
            let mut header = decl_head_html(
                decl,
                &page_root(&module.module),
                &module.module,
                &source_url,
            );
            header.push_str(&decl_signature(decl, &page_root(&module.module), &code));
            if let Err(why) = Content::of(&want.header).matches_head(&Content::of(&header)) {
                note(&mut failures, &format!("{what} (header)"), &why);
            }
            match renderer.decl_html(decl) {
                Ok(html) => {
                    if let Err(why) = Content::of(&want.html).matches(&Content::of(&html)) {
                        note(&mut failures, &what, &why);
                    }
                }
                Err(e) => note(&mut failures, &what, &e.to_string()),
            }
            decls += 1;
        }

        // The frame. The oracle writes one per module in index order, so the
        // position is the check that the two sides walk the same list.
        let frame = &full.frames[at];
        assert_eq!(frame.module, module.module, "the frames are out of step");
        let member_names: Vec<&str> = page_decls.iter().map(|d| d.name.as_str()).collect();
        assert_eq!(
            frame.member_names, member_names,
            "{}: the nav's page order differs",
            module.module
        );
        let head = head_html(&module.module, &root, &site);
        let want_title = between(&frame.head, "<title>", "</title>").unwrap_or_default();
        let got_title = between(&head, "<title>", "</title>").unwrap_or_default();
        if !got_title.starts_with(want_title) {
            note(
                &mut failures,
                &format!("{} title", module.module),
                &format!("want {want_title}, got {got_title}"),
            );
        }
        let meta = module_meta_html(&root, &module.imports, &index);
        let want_imports = list_items(&frame.nav, "<summary>Imports</summary><ul>");
        let got_imports = list_items(&meta, "<ul>");
        if want_imports != got_imports {
            note(
                &mut failures,
                &format!("{} imports", module.module),
                &format!("want {want_imports:?}, got {got_imports:?}"),
            );
        }
        let sidebar = sidebar_html(&root, &member_names);
        let want_entries: Vec<&str> = frame
            .nav
            .match_indices("class=\"nav_link\"")
            .filter_map(|(at, _)| attr_values(&frame.nav[at..], "href").first().copied())
            .collect();
        let got_entries: Vec<&str> = between(&sidebar, "<ul class=\"toc\">", "</ul>")
            .map(|toc| attr_values(toc, "href"))
            .unwrap_or_default();
        if want_entries != got_entries {
            note(
                &mut failures,
                &format!("{} page entries", module.module),
                &format!("want {want_entries:?}, got {got_entries:?}"),
            );
        }
    }

    eprintln!(
        "whole corpus: {headers} headers, {decls} declaration blocks, {} frames",
        modules.len()
    );
    assert!(
        failures.is_empty(),
        "{} differ:\n{}",
        failures.len(),
        failures.join("\n")
    );
    assert_eq!(headers, full.ir_declarations);
    assert_eq!(decls, full.page_declarations);
    assert_eq!(headers, 4_750, "the corpus changed size");
    assert_eq!(decls, 4_560, "the corpus changed size");
    assert_eq!(modules.len(), full.frames.len());
}

// ------------------------------------------------------------------- helpers

/// What a fragment of HTML *says*, as opposed to how it says it.
///
/// See the file heading for why the comparison is this and not the bytes. Each
/// of the four lists is compared the strongest way it can be: the anchors and
/// the links in document order, the rest as sorted multisets.
#[derive(Debug)]
struct Content {
    /// `id` attributes in document order, **without** the instance stubs' —
    /// doc-gen4 keyed those off the element `id` and this crate keys them off
    /// `data-name`, so they are compared as [`Content::stubs`] instead.
    ids: Vec<String>,
    /// `href` attributes in document order.
    hrefs: Vec<String>,
    /// The names the instance stubs will be filled for, sorted.
    stubs: Vec<String>,
    /// Every word outside a tag, sorted.
    words: Vec<String>,
}

impl Content {
    fn of(html: &str) -> Self {
        let (mut ids, mut stubs) = (Vec::new(), Vec::new());
        for id in attr_values(html, "id") {
            match id
                .strip_prefix("instances-for-list-")
                .or_else(|| id.strip_prefix("instances-list-"))
            {
                Some(name) => stubs.push(name.to_owned()),
                None => ids.push(id.to_owned()),
            }
        }
        stubs.extend(
            attr_values(html, "data-name")
                .into_iter()
                .map(str::to_owned),
        );
        stubs.sort();

        // The one place M8-b changed what a block *says* rather than how: a
        // named constructor was `Name :: ( … )` wrapped around the field list
        // and is now `constructor Name` above it. Both spellings come out, and
        // the constructor's name is still compared — it is the field list's
        // `id` on either side.
        let text = drop_element(html, "class=\"structure_ext_ctor\"", "</li>");
        let text = drop_element(&text, "class=\"ctor-note\"", "</p>");
        let mut words: Vec<String> = words(&text).into_iter().map(str::to_owned).collect();
        words.sort();

        Self {
            ids,
            hrefs: attr_values(html, "href")
                .into_iter()
                .map(str::to_owned)
                .collect(),
            stubs,
            words,
        }
    }

    /// A whole declaration block against the prototype's.
    ///
    /// The head's two hrefs are swapped and nothing else moved: doc-gen4 put
    /// the source link in a `div.gh_link` **above** the block and this crate
    /// puts it in the head, after the self link.
    fn matches(&self, got: &Self) -> Result<(), String> {
        let mut hrefs = self.hrefs.clone();
        if hrefs.len() < 2 {
            return Err(format!(
                "the prototype's block has {} link(s); it always has its own and its source",
                hrefs.len()
            ));
        }
        hrefs.swap(0, 1);
        compare(&self.ids, &hrefs, &self.stubs, &self.words, got)
    }

    /// The head and the signature against the prototype's `declHeader`, which
    /// is the same content **plus** the source link M8-b moved into it.
    fn matches_head(&self, got: &Self) -> Result<(), String> {
        let mut hrefs = got.hrefs.clone();
        if hrefs.len() < 2 {
            return Err(format!(
                "the head has {} link(s), not the self link and the source",
                hrefs.len()
            ));
        }
        let source = hrefs.remove(1);
        if !source.contains("#L") {
            return Err(format!("{source} is not a source range"));
        }
        // `got` with the source link taken back out is what `declHeader` was.
        let bare = Self {
            ids: got.ids.clone(),
            hrefs,
            stubs: got.stubs.clone(),
            words: got.words.clone(),
        };
        let mut words = self.words.clone();
        words.push("source".to_owned());
        words.sort();
        compare(&self.ids, &self.hrefs, &self.stubs, &words, &bare)
    }
}

fn compare(
    ids: &[String],
    hrefs: &[String],
    stubs: &[String],
    words: &[String],
    got: &Content,
) -> Result<(), String> {
    if ids != got.ids {
        return Err(differ("anchors", ids, &got.ids));
    }
    if hrefs != got.hrefs {
        return Err(differ("links", hrefs, &got.hrefs));
    }
    if stubs != got.stubs {
        return Err(differ("instance stubs", stubs, &got.stubs));
    }
    if words != got.words {
        return Err(differ("words", words, &got.words));
    }
    Ok(())
}

/// Names what parted company, rather than printing two documents.
fn differ(what: &str, want: &[String], got: &[String]) -> String {
    let missing: Vec<&String> = want.iter().filter(|w| !got.contains(w)).take(6).collect();
    let extra: Vec<&String> = got.iter().filter(|g| !want.contains(g)).take(6).collect();
    if missing.is_empty() && extra.is_empty() {
        format!(
            "the same {what} in a different order\n  want: {:?}\n  got:  {:?}",
            &want[..want.len().min(12)],
            &got[..got.len().min(12)]
        )
    } else {
        format!("{what} differ\n  missing: {missing:?}\n  extra:   {extra:?}")
    }
}

/// Every ` name="…"` value, in document order. The leading space is what keeps
/// `id` from matching inside `data-name` and the like.
fn attr_values<'a>(html: &'a str, name: &str) -> Vec<&'a str> {
    let needle = format!(" {name}=\"");
    let mut out = Vec::new();
    let mut rest = html;
    while let Some(at) = rest.find(&needle) {
        let value = &rest[at + needle.len()..];
        let end = value.find('"').unwrap_or(value.len());
        out.push(&value[..end]);
        rest = &value[end..];
    }
    out
}

/// Every whitespace-separated run of text outside a tag.
fn words(html: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut rest = html;
    loop {
        let at = rest.find('<').unwrap_or(rest.len());
        out.extend(rest[..at].split_whitespace());
        match rest[at..].find('>') {
            Some(end) => rest = &rest[at + end + 1..],
            None => break,
        }
    }
    out
}

/// Removes every element whose opening tag contains `marker`, from its `<` to
/// the end of the `close` that follows.
fn drop_element(html: &str, marker: &str, close: &str) -> String {
    let mut out = String::with_capacity(html.len());
    let mut rest = html;
    while let Some(at) = rest.find(marker) {
        let open = rest[..at].rfind('<').unwrap_or(at);
        let end = rest[at..]
            .find(close)
            .map_or(rest.len(), |e| at + e + close.len());
        out.push_str(&rest[..open]);
        rest = &rest[end..];
    }
    out.push_str(rest);
    out
}

fn between<'a>(html: &'a str, open: &str, close: &str) -> Option<&'a str> {
    let at = html.find(open)? + open.len();
    let end = html[at..].find(close)? + at;
    Some(&html[at..end])
}

/// The `(href, text)` of every `<li>` of the list that follows `open`.
fn list_items(html: &str, open: &str) -> Vec<(String, String)> {
    let Some(list) = between(html, open, "</ul>") else {
        return Vec::new();
    };
    list.split("<li>")
        .skip(1)
        .filter_map(|item| {
            let href = (*attr_values(item, "href").first()?).to_owned();
            Some((href, words(item).join(" ")))
        })
        .collect()
}
