/-
dump-gc.lean -- print the code point ranges of the two Unicode general category
sets doc-gen4's docstring renderer tests for, as *UnicodeBasic* answers them.

WHY THIS FILE EXISTS
--------------------
Two functions in `DocGen4/Output/DocString.lean` classify characters by general
category, and both reach the generated bytes:

  * `mdGetHeadingId` (155-165) replaces every run of `P | Z | C` in a heading's
    plain text with one `-`, and that string is the heading's `id=` and the
    target of its `#` link.
  * `autoLinkInline` (175-197) splits code spans and Lean code blocks on
    `Z | C`, and each piece is looked up as a name.

doc-gen4 asks `UnicodeBasic`, which carries its own copy of the Unicode
character database. A Rust crate would carry a *different* copy: V8's tables and
this one disagree on 4,802 code points (measured 2026-08-11), nearly all of them
assignments one version has and the other does not. So the tables in
`crates/litedoc4-md/src/gc.rs` are dumped from the same `UnicodeBasic` build
doc-gen4 links, by this script.

Surrogates are reported as members without asking: `Char.ofNat` cannot
represent one (it yields `'A'`), Rust's `char` cannot hold one either, and
Unicode assigns them `Cs`, which is inside `C`.

usage (from the measurement target, which is where UnicodeBasic is built):
  cd /Users/haruka/dev/lean-projects
  lake env lean \
    --load-dynlib=.lake/packages/UnicodeBasic/.lake/build/lib/libUnicodeBasic_UnicodeBasic.dylib \
    --run dump-gc.lean

Prints `<set> [lo,hi]` per line, in code point order, `<set>` being `PZC` or
`ZC`.
-/
import UnicodeBasic

open Unicode

/-- The ranges on which `member` holds, over the whole code point space. -/
def rangesOf (member : Nat → Bool) : Array (Nat × Nat) := Id.run do
  let mut ranges : Array (Nat × Nat) := #[]
  let mut start : Option Nat := none
  for n in [0:0x110000] do
    match start, member n with
    | none, true => start := some n
    | some s, false =>
      ranges := ranges.push (s, n - 1)
      start := none
    | _, _ => pure ()
  if let some s := start then
    ranges := ranges.push (s, 0x10FFFF)
  return ranges

/-- Surrogates are `Cs`, which is in `C`, which is in both sets. -/
def isSurrogate (n : Nat) : Bool := n ≥ 0xD800 && n ≤ 0xDFFF

def inPZC (n : Nat) : Bool :=
  isSurrogate n || Char.ofNat n ∈ GC.P ||| GC.Z ||| GC.C

def inZC (n : Nat) : Bool :=
  isSurrogate n || Char.ofNat n ∈ GC.Z ||| GC.C

def emit (name : String) (member : Nat → Bool) : IO Unit := do
  let ranges := rangesOf member
  let total := ranges.foldl (fun acc (s, e) => acc + (e - s + 1)) 0
  IO.eprintln s!"{name}: {ranges.size} ranges, {total} code points"
  for (s, e) in ranges do
    IO.println s!"{name} [{s},{e}]"

def main : IO UInt32 := do
  emit "PZC" inPZC
  emit "ZC" inZC
  return 0
