#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run --allow-env
// gen-gc-table.ts -- write `src/gc.rs` from UnicodeBasic's own answers.
//
// doc-gen4 classifies on `UnicodeBasic`, whose character database is pinned by
// the target package's `lake-manifest.json`. Any other copy of the UCD is a
// different answer: V8's `\p{P}\p{Z}\p{C}` and this one disagree on 4,802 code
// points (measured 2026-08-11). So the ranges are dumped by `dump-gc.lean` from
// the build doc-gen4 links, and written here as Rust.
//
// npm/node are broken in this environment; this must run under deno.
//
// usage:
//   deno run --allow-read --allow-write --allow-run --allow-env \
//     crates/litedoc4-md/tests/oracle/gen-gc-table.ts
//   ... --check    fail if the committed src/gc.rs is not what this produces

const OUT = new URL("../../src/gc.rs", import.meta.url);
const DUMPER = new URL("dump-gc.lean", import.meta.url);
const DEFAULT_TARGET = "/Users/haruka/dev/lean-projects";

const args = Deno.args;
const flag = (name: string, fallback: string | null = null) => {
  const at = args.indexOf(name);
  return at >= 0 && at + 1 < args.length ? args[at + 1] : fallback;
};
const target = flag("--target", DEFAULT_TARGET)!;
const check = args.includes("--check");

const DYLIB = Deno.build.os === "darwin" ? "dylib" : "so";
const UNICODE_LIB =
  `.lake/packages/UnicodeBasic/.lake/build/lib/libUnicodeBasic_UnicodeBasic.${DYLIB}`;

const command = new Deno.Command("lake", {
  args: ["env", "lean", `--load-dynlib=${UNICODE_LIB}`, "--run", DUMPER.pathname],
  cwd: target,
  stdout: "piped",
  stderr: "inherit",
});
const { code, stdout } = await command.output();
if (code !== 0) throw new Error(`dump-gc.lean exited ${code}`);

const sets = new Map<string, [number, number][]>();
for (const line of new TextDecoder().decode(stdout).split("\n")) {
  if (line === "") continue;
  const at = line.indexOf(" ");
  const name = line.slice(0, at);
  if (!sets.has(name)) sets.set(name, []);
  sets.get(name)!.push(JSON.parse(line.slice(at + 1)));
}

for (const [name, ranges] of sets) {
  // -2 so that a first range starting at 0 satisfies `lo > previous + 1`.
  let previous = -2;
  for (const [lo, hi] of ranges) {
    if (!(lo > previous + 1 && hi >= lo)) {
      throw new Error(`${name}: ranges are not sorted and disjoint at [${lo},${hi}]`);
    }
    previous = hi;
  }
}

const pzc = sets.get("PZC")!;
const zc = sets.get("ZC")!;

/** The pin the tables came from, so a stale one can be spotted. */
const manifest = JSON.parse(await Deno.readTextFile(`${target}/lake-manifest.json`));
const unicodeBasic = (manifest.packages ?? []).find((p: any) => p.name === "UnicodeBasic");

const table = (name: string, ranges: [number, number][]) =>
  `static ${name}: [(u32, u32); ${ranges.length}] = [\n` +
  ranges
    .map(([lo, hi]) => `    (0x${lo.toString(16).toUpperCase()}, 0x${hi.toString(16).toUpperCase()}),`)
    .join("\n") +
  "\n];";

const source = `//! Holds the answers of Lean 4 / Unicode Basic (Apache-2.0, Copyright © 2023-2026
//! François G. Dorais), whose data derives from Unicode® character databases
//! (Copyright © 1991-2025 Unicode, Inc., <https://www.unicode.org/copyright.html>).
//! See this repository's NOTICE.
//!
//! The Unicode general category sets doc-gen4's docstring renderer tests for.
//!
//! **Generated by \`tests/oracle/gen-gc-table.ts\`; do not edit.** The ranges are
//! \`UnicodeBasic\`'s own answers, from the build doc-gen4 links, pinned at
//! \`${unicodeBasic?.rev ?? "unknown"}\` by the target package's
//! \`lake-manifest.json\`. Regenerate with the script above; \`--check\` fails if
//! this file is not what it produces.
//!
//! Not a general-purpose Unicode table: each set is a merge of several
//! categories, and both report surrogates as members (they are \`Cs\`, inside
//! \`C\`, and no \`char\` can hold one anyway).

/// \`P | Z | C\` as ${pzc.length} inclusive code point ranges, in order.
${table("P_Z_C", pzc)}

/// \`Z | C\` as ${zc.length} inclusive code point ranges, in order.
${table("Z_C", zc)}

fn contains(table: &[(u32, u32)], c: char) -> bool {
    let cp = c as u32;
    table
        .binary_search_by(|&(lo, hi)| {
            if hi < cp {
                std::cmp::Ordering::Less
            } else if lo > cp {
                std::cmp::Ordering::Greater
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

/// \`c ∈ Unicode.GC.P ||| Unicode.GC.Z ||| Unicode.GC.C\`.
///
/// What \`mdGetHeadingId\` drops runs of — see [\`crate::html::heading_id\`].
#[must_use]
pub fn is_p_z_c(c: char) -> bool {
    contains(&P_Z_C, c)
}

/// \`c ∈ Unicode.GC.Z ||| Unicode.GC.C\`.
///
/// What \`autoLinkInline\` splits code on. Punctuation is deliberately absent:
/// \`Nat.succ\` has to stay one word.
#[must_use]
pub fn is_z_c(c: char) -> bool {
    contains(&Z_C, c)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tables_are_sorted_and_disjoint() {
        for table in [P_Z_C.as_slice(), Z_C.as_slice()] {
            for pair in table.windows(2) {
                assert!(pair[0].0 <= pair[0].1, "{:?} is empty", pair[0]);
                assert!(
                    pair[0].1 + 1 < pair[1].0,
                    "{:?} and {:?} touch",
                    pair[0],
                    pair[1]
                );
            }
        }
    }

    /// \`Z | C\` is a subset of \`P | Z | C\`, and the difference is exactly the
    /// punctuation. If these two ever came from different dumps this fails.
    #[test]
    fn zc_is_inside_pzc() {
        for cp in 0..=0x10FFFFu32 {
            let Some(c) = char::from_u32(cp) else {
                continue;
            };
            assert!(!is_z_c(c) || is_p_z_c(c), "U+{cp:04X}");
        }
        // The ASCII punctuation \`autoLinkInline\` must not split on.
        for c in ['.', '_', '\\'', '!', '?', '-', ':'] {
            assert!(is_p_z_c(c) && !is_z_c(c), "{c:?}");
        }
    }

    #[test]
    fn the_categories_are_the_ones_named() {
        // \`Z\` and \`C\`: separators, controls, and the format characters.
        for c in [' ', '\\t', '\\n', '\\u{0}', '\\u{a0}', '\\u{ad}', '\\u{2028}'] {
            assert!(is_z_c(c), "U+{:04X}", c as u32);
        }
        // \`L\`, \`M\`, \`N\` and \`S\` are what a heading id keeps.
        for c in [
            'a',
            'Z',
            '0',
            'α',
            'ℕ',
            '∑',
            '→',
            '×',
            '\\u{1D4A9}',
            '\\u{301}',
        ] {
            assert!(!is_p_z_c(c), "U+{:04X}", c as u32);
        }
    }
}
`;

if (check) {
  const committed = await Deno.readTextFile(OUT);
  if (committed !== source) {
    console.error(`${OUT.pathname} is not what this script produces`);
    Deno.exit(1);
  }
  console.error(`${OUT.pathname} is current (${pzc.length} + ${zc.length} ranges)`);
} else {
  await Deno.writeTextFile(OUT, source);
  console.error(`${pzc.length} + ${zc.length} ranges -> ${OUT.pathname}`);
}
