//! The digest the frozen fixtures record artifacts by.
//!
//! WHY THIS IS NOT AN ORACLE, AND WHY FORKING IT AGAIN WOULD BUY NOTHING
//!
//! §16 of `docs/plans/refactoring.md` names [`fnv1a64`] as one of three places
//! where "the same judgement written twice" might be deliberate, and asks that
//! the question be put before anything is folded. It was, and the answer is no
//! 【実測 2026-08-23】:
//!
//!   - **No product code computes an FNV hash.** `crates/*/src/` contains no
//!     implementation of one at all, so this is not a second spelling of
//!     anything the tree ships. Nothing here can disagree with the program.
//!   - **The independent implementation is TypeScript, and it is not in this
//!     repository.** The digests these callers compare against are literals
//!     inside `litedoc4-incr/tests/data/{impact,merge}-expected.json` and
//!     `litedoc4-global/tests/data/global-expected.json`, whose own headers
//!     name what wrote them — `"Generated by tests/oracle/gen-impact-expected.ts
//!     from tools/impact-reference.sh --impl ts"` and a `generatedBy` pointing
//!     at `gen-global-expected.ts` over `experiments/stage7h/global.ts`. Those
//!     generators left HEAD with the prototype (tag `experiments-frozen`); what
//!     survives is their output.
//!   - So the independence being tested is **the prototype's bytes against this
//!     tree's bytes**, and the hash is the instrument of the comparison, not a
//!     side of it. For the comparison to mean anything the two sides must run
//!     *the same* function — which is why the four Rust copies §7 U6 folded
//!     (`incr/tests/impact.rs`, `incr/tests/merge.rs`, `global/tests/global.rs`,
//!     `global/tests/state_and_delta.rs`, six identical lines and the same two
//!     constants in each) were independent of nothing. A fifth copy would add
//!     no independence and one more thing able to drift.
//!
//! Written down here so that a later reader does not "restore" an independence
//! that never existed by forking it back out.

/// FNV-1a 64 of `bytes`, as sixteen lower-case hex digits.
///
/// A staleness check, not a security property: it is here so that a recorded
/// artifact can be compared without the fixture carrying megabytes of it.
///
/// The width is fixed at sixteen — the fixtures store the digest as text, and a
/// hash with a leading zero byte spelled `{hash:x}` would be fourteen
/// characters that no recorded value ever equals.
///
/// ```
/// // The published FNV-1a 64 vector for the empty input is the offset basis.
/// assert_eq!(litedoc4_testutil::hash::fnv1a64(b""), "cbf29ce484222325");
/// assert_eq!(litedoc4_testutil::hash::fnv1a64(b"a"), "af63dc4c8601ec8c");
/// ```
pub fn fnv1a64(bytes: &[u8]) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in bytes {
        hash = (hash ^ u64::from(*byte)).wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{hash:016x}")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The published FNV-1a 64 vectors.
    ///
    /// **Not a value read back out of a fixture.** Every digest in
    /// `tests/data/*-expected.json` is over a corpus tree that is not in this
    /// repository, so a fixture value cannot be recomputed here and a test that
    /// quoted one would only be asserting that this function equals itself.
    /// These three are the standard vectors: the empty input hashes to the
    /// offset basis, and the other two are the ones every FNV implementation
    /// publishes.
    #[test]
    fn the_published_vectors() {
        assert_eq!(fnv1a64(b""), "cbf29ce484222325");
        assert_eq!(fnv1a64(b"a"), "af63dc4c8601ec8c");
        assert_eq!(fnv1a64(b"foobar"), "85944171f73967e8");
    }

    /// Sixteen digits even when the top ones are zero.
    ///
    /// `oqda` hashes to `0x0000c5b4674b4b6e`; `{hash:x}` would print twelve
    /// characters and match no recorded digest. The fixtures store this as
    /// text, so the padding is part of the value rather than of the display.
    #[test]
    fn the_digest_is_zero_padded_to_sixteen_digits() {
        assert_eq!(fnv1a64(b"oqda"), "0000c5b4674b4b6e");
        assert_eq!(fnv1a64(b"oqda").len(), 16);
    }

    /// A byte is a byte: the hash runs over bytes rather than characters, and
    /// input that is not UTF-8 is exactly what
    /// `litedoc4-global/tests/global.rs` hands it (`search-index.bin`).
    #[test]
    fn the_input_is_bytes_and_not_text() {
        assert_eq!(fnv1a64(&[0xff, 0xff, 0xff]), "f998341be47bae14");
        // Order matters, so a reordered artifact is a different digest — the
        // whole point of `merge.rs`'s `assert_ne!` against the prototype.
        assert_ne!(fnv1a64(b"ab"), fnv1a64(b"ba"));
    }
}
