//! Milestone **M2-b**: the `contentHash` cache and the whole-package map delta.
//!
//! Two oracles, neither of which is this file's own opinion:
//!
//! - **`experiments/stage7h/oracle.sh`, transcribed.** Its contract is that a
//!   cached build equals a from-scratch build over *every* IR state, so both
//!   sides are run here over the same seven states — base / rerun / modified /
//!   removed / added / restored / stale-state — with one cache carried through,
//!   and all six artifacts compared byte for byte at each. The seventh state is
//!   the one that keeps plan §3's version-key discipline alive: a state file
//!   whose `derivation` was tampered with has to be dropped whole.
//! - **The frozen prototype's own answers**, for the two things a byte
//!   comparison of the six artifacts cannot see: the state file
//!   (`tests/data/…` has no copy — the real one is compared directly, see
//!   [`the_state_file_is_the_prototypes_bytes`]) and the delta
//!   (`tests/data/delta-expected.json`, generated by
//!   `tests/oracle/gen-delta-expected.ts` — **a frozen value**: the generator and
//!   the prototype it drove were removed with `experiments/` on 2026-08-16 and
//!   exist only at tag `experiments-frozen`, so HEAD cannot regenerate it).
//!
//! # Byte equality is not branch coverage (plan §7)
//!
//! Of the **35** [`BRANCHES`] this milestone added:
//!
//! | exercise | reaches |
//! |---|---:|
//! | the full-corpus six-file comparison (`tools/global-compare.sh` — M2-a's gate) | **5** |
//! | the seven states | **13** |
//! | everything real data can reach (seven states + the corpus delta) | **26** |
//! | curated cases only ([`NO_REAL_DATA_REACHES`]) | **9** |
//!
//! A run with no `--state` and no `--before` takes one path through all of
//! this, so the comparison M2-a was judged on cannot see 30 of the 35. The
//! dependency is asserted rather than commented:
//! [`the_curated_cases_cover_what_the_package_does_not`].

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};

use litedoc4_global::artifacts::ARTIFACT_PATHS;
use litedoc4_global::delta::Delta;
use litedoc4_global::facts::{ModuleFacts, PROTOTYPE_FACT_KEYS, autolink_tokens};
use litedoc4_global::state::{STATE_VERSION, State};
use litedoc4_global::{
    GlobalOptions, GlobalSummary, STATE_DERIVATION, STATE_FILE, build_global, facts_for, v8_gc,
};
use litedoc4_ir::{Index, IrTree};
use litedoc4_testutil::corpus;
use litedoc4_testutil::hash::fnv1a64;
use litedoc4_testutil::{TempDir, TempDirs};
use serde::Deserialize;
use serde_json::{Value, json};

/// The temporary directories this file makes. The prefix names the file,
/// so a directory a failed run leaves behind names what made it.
const TEMP: TempDirs = TempDirs::prefixed("litedoc4-state");

/// The one artifact this crate and the frozen prototype both write since M8-d,
/// and the one the delta reads back as `--before`.
///
/// **Named rather than `ARTIFACT_PATHS[n]`** 【判断】: it was the second entry
/// until M8-d deleted `declaration-data.bmp` from in front of it, and a
/// subscript into a list whose contents are a milestone's decision is a silent
/// mis-read the moment the list changes.
const NAME_MAP: &str = "declarations/name-map.json";

// --------------------------------------------------------------- the branches

/// Every branch M2-b added, named by an event of the run rather than by a line
/// of the code.
///
/// Named by events on purpose (plan §7's rule from M1): a counter that mirrors
/// the branch structure becomes a second definition of it and drifts. Each of
/// these is decided by [`observe`] from the inputs a run was given and the files
/// it produced.
const BRANCHES: [&str; 35] = [
    // State::load — eight ways to arrive at a cache, seven of them empty.
    "stateNotRequested",
    "stateFileMissing",
    "stateUnparseable",
    "stateVersionMismatch",
    "stateDerivationMismatch",
    "stateSchemaMismatch",
    "stateGeneratorMismatch",
    "stateAccepted",
    // facts_for — the hit test.
    "cacheHit",
    "cacheMissHashMoved",
    "cacheMissNotCached",
    // State::save.
    "saveSkipped",
    "saveWritten",
    "saveDroppedEntry",
    // Delta.
    "deltaOff",
    "deltaOn",
    "changedValueDiffers",
    "changedOnlyInBefore",
    "changedOnlyInAfter",
    "changedEmpty",
    "changedSampleTruncated",
    "affectedEmpty",
    "affectedNonEmpty",
    "witnessLimitReached",
    "witnessNotFirstToken",
    "affectedSortReorders",
    "affectedAboveBmp",
    "printSetEmptyFile",
    "printSetNonEmpty",
    "printSetOmitted",
    "deltaJsonWritten",
    "deltaJsonOmitted",
    // The timings record.
    "timingsWritten",
    "timingsOmitted",
    // The tokeniser's separator set (plan §8, V6).
    "tokenSeparatorV8Only",
];

/// What the full-corpus six-file byte comparison reaches — `--state` and
/// `--before` are both absent there, so one path through everything.
///
/// This is the M2-a gate (`tools/global-compare.sh`), and it is **5 of the 35**.
/// Only one branch outside this list depends on what is in the IR
/// (`tokenSeparatorV8Only`), and the target package does not have it.
const SIX_FILE_COMPARISON: [&str; 5] = [
    "cacheMissNotCached",
    "deltaOff",
    "saveSkipped",
    "stateNotRequested",
    "timingsOmitted",
];

/// What the real corpus reaches when it is driven through a delta —
/// [`the_delta_is_the_prototypes_delta`], which is the only place real data
/// meets `--before`.
const CORPUS_DELTA: [&str; 17] = [
    "affectedNonEmpty",
    "affectedSortReorders",
    "cacheMissNotCached",
    "changedEmpty",
    "changedOnlyInAfter",
    "changedOnlyInBefore",
    "changedValueDiffers",
    "deltaJsonOmitted",
    "deltaJsonWritten",
    "deltaOn",
    "printSetEmptyFile",
    "printSetNonEmpty",
    "saveSkipped",
    "stateNotRequested",
    "timingsOmitted",
    "witnessLimitReached",
    "witnessNotFirstToken",
];

/// The branches **no exercise over the real corpus reaches at all**: neither the
/// seven states nor the delta differential, whatever the data.
///
/// Nine of thirty-five. Four are foreign-state shapes that only an IR upgrade
/// or a corrupted file produces; the other five are properties the target
/// package does not have — no name above the BMP (U1 again), never more than
/// twenty changed names, never a change that nothing mentions, the pipeline
/// always asks for the print set, and **no code span in any docstring contains a
/// code point the two separator sets disagree about** (0 of 233,713 code points
/// inside 16,044 code spans 【実測 2026-08-12 →
/// `benchmarks/results/m2b-v6-token-separators.json`】, which is why the state
/// file is the prototype's bytes despite the two implementations tokenising
/// differently).
const NO_REAL_DATA_REACHES: [&str; 9] = [
    "affectedAboveBmp",
    "affectedEmpty",
    "changedSampleTruncated",
    "printSetOmitted",
    "stateGeneratorMismatch",
    "stateSchemaMismatch",
    "stateUnparseable",
    "stateVersionMismatch",
    "tokenSeparatorV8Only",
];

/// What one run of [`build_global`] was given and what came out of it.
struct Run<'a> {
    options: &'a GlobalOptions<'a>,
    index: &'a Index,
    /// The state file as it was **before** the run, if there was one.
    state_before: Option<String>,
    /// The state file as it is **after** the run.
    state_after: Option<String>,
    summary: &'a GlobalSummary,
    /// The facts of every module in index order, derived without a cache.
    facts: &'a [ModuleFacts],
    /// The two maps the delta compared, when it ran.
    before_map: Option<&'a BTreeMap<String, String>>,
}

/// Which branches a run reached.
///
/// Everything here is read off the run's inputs and outputs. Nothing re-derives
/// what the code under test decided — where a decision is needed (was this state
/// file usable? which modules should have hit?) it is made from the file on disk
/// and the index, and [`Sequence::step`] asserts that the code agreed.
fn observe(run: &Run<'_>) -> BTreeSet<&'static str> {
    let mut fired: BTreeSet<&'static str> = BTreeSet::new();
    let mut fire = |branch: &'static str| {
        assert!(
            BRANCHES.contains(&branch),
            "{branch} is not a counted branch"
        );
        fired.insert(branch);
    };

    match (run.options.state, &run.state_before) {
        (None, _) => fire("stateNotRequested"),
        (Some(_), None) => fire("stateFileMissing"),
        (Some(_), Some(text)) => match Verdict::of(text, run.index) {
            Verdict::Unparseable => fire("stateUnparseable"),
            Verdict::Foreign(which) => fire(which),
            Verdict::Usable(_) => fire("stateAccepted"),
        },
    }

    let cached = usable_cache(run);
    for entry in &run.index.modules {
        match cached.get(entry.module.as_str()) {
            None => fire("cacheMissNotCached"),
            Some(hash) if *hash == entry.content_hash => fire("cacheHit"),
            Some(_) => fire("cacheMissHashMoved"),
        }
    }
    if run.options.state.is_some() {
        fire("saveWritten");
        let live: BTreeSet<&str> = run
            .index
            .modules
            .iter()
            .map(|entry| entry.module.as_str())
            .collect();
        // Dropped, not merely stale: the entry was in the cache, its module is
        // not in the index any more, and the file that was just written does
        // not name it.
        let saved = saved_modules(run.state_after.as_deref());
        if cached
            .keys()
            .any(|module| !live.contains(module.as_str()) && !saved.contains(module.as_str()))
        {
            fire("saveDroppedEntry");
        }
    } else {
        fire("saveSkipped");
    }

    fire(if run.options.timings.is_some() {
        "timingsWritten"
    } else {
        "timingsOmitted"
    });

    // Read off the IR rather than off the facts: under the union no token can
    // contain a separator of either set, so the tokens cannot say whether the
    // split met one.
    if meets_a_v8_only_separator(run.options.ir) {
        fire("tokenSeparatorV8Only");
    }

    let (Some(delta), Some(before)) = (&run.summary.delta, run.before_map) else {
        fire("deltaOff");
        return fired;
    };
    fire("deltaOn");
    let after = name_map(run.options.out);
    for name in before.keys().chain(after.keys()) {
        match (before.get(name), after.get(name)) {
            (Some(a), Some(b)) if a != b => fire("changedValueDiffers"),
            (Some(_), None) => fire("changedOnlyInBefore"),
            (None, Some(_)) => fire("changedOnlyInAfter"),
            _ => {}
        }
    }
    if delta.changed.is_empty() {
        fire("changedEmpty");
    }
    if delta.changed.len() > 20 {
        fire("changedSampleTruncated");
    }
    // "The scan ran and found nothing", not "there was nothing to scan for":
    // the empty-change case is `changedEmpty`, and the two write the same file
    // by two different roads.
    if delta.affected.is_empty() {
        if !delta.changed.is_empty() {
            fire("affectedEmpty");
        }
    } else {
        fire("affectedNonEmpty");
    }
    if delta.affected.len() > 20 {
        fire("witnessLimitReached");
    }
    // The witness is the first *matching* token of the module's sorted token
    // list, which is only the first token when the changed name happens to sort
    // first.
    for witness in &delta.witnesses {
        let facts = run
            .facts
            .iter()
            .find(|facts| facts.module == witness.module)
            .expect("a witness names a module of this IR");
        if facts.tokens.first() != Some(&witness.name) {
            fire("witnessNotFirstToken");
        }
    }
    let in_index_order: Vec<&String> = run
        .facts
        .iter()
        .map(|facts| &facts.module)
        .filter(|module| delta.affected.contains(module))
        .collect();
    if in_index_order != delta.affected.iter().collect::<Vec<_>>() {
        fire("affectedSortReorders");
    }
    if delta
        .affected
        .iter()
        .any(|module| module.chars().any(|c| c as u32 > 0xFFFF))
    {
        fire("affectedAboveBmp");
    }
    match run.options.print_set {
        None => fire("printSetOmitted"),
        Some(path) => {
            let body = fs::read(path).expect("the print set was written");
            if delta.affected.is_empty() {
                assert_eq!(body, b"", "an empty affected set is a file with no bytes");
                fire("printSetEmptyFile");
            } else {
                fire("printSetNonEmpty");
            }
        }
    }
    fire(if run.options.delta_json.is_some() {
        "deltaJsonWritten"
    } else {
        "deltaJsonOmitted"
    });
    fired
}

/// Whether any code span in this IR's declaration docstrings holds a code point
/// **V8 splits on and UnicodeBasic does not** — the direction of the
/// disagreement that costs correctness (plan §8, V6, and
/// `litedoc4_global::facts::is_token_separator`).
///
/// The other direction is not looked for because it is empty: no code point is a
/// separator for UnicodeBasic and not for V8 【実測 2026-08-12, asserted by
/// `facts::tests::the_two_separator_sets_disagree_the_way_v6_measured_them`】.
///
/// Memoised per path — every tree this suite mutates is written before the first
/// run over it, so the answer for a path does not change once it has been asked.
fn meets_a_v8_only_separator(ir: &Path) -> bool {
    static SEEN: OnceLock<Mutex<BTreeMap<PathBuf, bool>>> = OnceLock::new();
    let seen = SEEN.get_or_init(|| Mutex::new(BTreeMap::new()));
    if let Some(answer) = seen.lock().expect("the memo is not poisoned").get(ir) {
        return *answer;
    }
    let tree = IrTree::open(ir).expect("the IR opens");
    let found = tree.modules().any(|module| {
        let module = module.expect("the module reads");
        module.declarations.iter().any(|decl| {
            decl.doc.as_deref().is_some_and(|doc| {
                backtick_spans(doc)
                    .iter()
                    .any(|span| span.chars().any(is_v8_only_separator))
            })
        })
    });
    seen.lock()
        .expect("the memo is not poisoned")
        .insert(ir.to_owned(), found);
    found
}

fn is_v8_only_separator(c: char) -> bool {
    v8_gc::is_z_c(c) && !litedoc4_md::gc::is_z_c(c)
}

/// The inside of every `` `...` ``, as ``/`([^`\n]+)`/g`` finds them — the
/// test's own reading of the regex, so that the crate's is not both the thing
/// under test and the authority on what it saw.
fn backtick_spans(doc: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut rest = doc;
    while let Some(open) = rest.find('`') {
        let after = &rest[open + 1..];
        // A run that stops on anything but a closing backtick is not a match,
        // and the regex engine retries from one position past the opening one.
        match after.find(['`', '\n']) {
            Some(at) if at > 0 && after.as_bytes()[at] == b'`' => {
                out.push(&after[..at]);
                rest = &after[at + 1..];
            }
            _ => rest = after,
        }
    }
    out
}

/// What a state file on disk is worth to a run over `index` — the test's own
/// reading of the four version keys, so that the code's reading has something to
/// disagree with.
enum Verdict {
    Unparseable,
    /// Which of the four keys disagreed.
    Foreign(&'static str),
    /// module -> the `contentHash` the entry was built for.
    Usable(BTreeMap<String, String>),
}

impl Verdict {
    fn of(text: &str, index: &Index) -> Self {
        let Ok(value) = serde_json::from_str::<Value>(text) else {
            return Self::Unparseable;
        };
        let Some(object) = value.as_object() else {
            return Self::Unparseable;
        };
        if object.get("stateVersion").and_then(Value::as_u64) != Some(STATE_VERSION) {
            return match object.get("stateVersion") {
                Some(Value::Number(_)) => Self::Foreign("stateVersionMismatch"),
                _ => Self::Unparseable,
            };
        }
        match object.get("derivation").and_then(Value::as_str) {
            Some(STATE_DERIVATION) => {}
            Some(_) => return Self::Foreign("stateDerivationMismatch"),
            None => return Self::Unparseable,
        }
        match object.get("schemaVersion").and_then(Value::as_u64) {
            Some(version) if version == u64::from(index.schema_version) => {}
            Some(_) => return Self::Foreign("stateSchemaMismatch"),
            None => return Self::Unparseable,
        }
        match object.get("generator").and_then(Value::as_str) {
            Some(generator) if generator == index.generator => {}
            Some(_) => return Self::Foreign("stateGeneratorMismatch"),
            None => return Self::Unparseable,
        }
        let modules = object.get("modules").and_then(Value::as_object);
        Self::Usable(
            modules
                .map(|modules| {
                    modules
                        .iter()
                        .filter_map(|(module, facts)| {
                            let hash = facts.get("contentHash")?.as_str()?;
                            Some((module.clone(), hash.to_owned()))
                        })
                        .collect()
                })
                .unwrap_or_default(),
        )
    }
}

/// The entries the run should have been able to hit, module -> hash.
fn usable_cache(run: &Run<'_>) -> BTreeMap<String, String> {
    match (run.options.state, &run.state_before) {
        (Some(_), Some(text)) => match Verdict::of(text, run.index) {
            Verdict::Usable(entries) => entries,
            _ => BTreeMap::new(),
        },
        _ => BTreeMap::new(),
    }
}

/// The modules a state file names, or none when there is no file.
fn saved_modules(state: Option<&str>) -> BTreeSet<String> {
    let Some(text) = state else {
        return BTreeSet::new();
    };
    serde_json::from_str::<Value>(text)
        .ok()
        .and_then(|value| Some(value.get("modules")?.as_object()?.keys().cloned().collect()))
        .unwrap_or_default()
}

fn name_map(site: &Path) -> BTreeMap<String, String> {
    let text = fs::read_to_string(site.join(NAME_MAP)).expect("name-map.json was written");
    serde_json::from_str(&text).expect("name-map.json is a flat string map")
}

// ------------------------------------------------------------- the sequence

/// One run of the seven states, carrying a cache from the first to the last.
struct Sequence {
    work: TempDir,
    state: PathBuf,
    /// The branches every step of this sequence reached, together.
    covered: BTreeSet<&'static str>,
    steps: usize,
}

/// What one state of the sequence proved.
struct Step {
    hits: usize,
    misses: usize,
}

impl Sequence {
    fn new(what: &str) -> Self {
        let work = TEMP.make(what);
        let state = work.path().join("state");
        Self {
            work,
            state,
            covered: BTreeSet::new(),
            steps: 0,
        }
    }

    /// `oracle.sh`'s `step`: build the same IR twice — from scratch, and with
    /// the cache carried in from the last state — and compare all six.
    fn step(&mut self, name: &str, ir: &Path) -> Step {
        self.steps += 1;
        let scratch = self.work.path().join(format!("{name}-scratch"));
        let cached = self.work.path().join(format!("{name}-cached"));
        let timings = self.work.path().join(format!("{name}-timings.json"));
        let _ = fs::remove_dir_all(&scratch);
        let _ = fs::remove_dir_all(&cached);

        let tree = IrTree::open(ir).expect("the IR opens");
        let facts = facts_for(&tree, &State::empty())
            .expect("the IR reads")
            .facts;

        // The from-scratch side: the program M2-a was judged on, unchanged.
        let scratch_options = GlobalOptions::new(ir, &scratch);
        let scratch_summary = build_global(&scratch_options).expect("the from-scratch build runs");
        assert_eq!(scratch_summary.cache_hits, 0, "{name}: no state, no hits");
        assert_eq!(scratch_summary.state_bytes, 0, "{name}: no state, no file");
        self.covered.extend(observe(&Run {
            options: &scratch_options,
            index: tree.index(),
            state_before: None,
            state_after: None,
            summary: &scratch_summary,
            facts: &facts,
            before_map: None,
        }));

        // The cached side, carrying whatever the last step left behind.
        let state_before = fs::read_to_string(self.state.join(STATE_FILE)).ok();
        let mut options = GlobalOptions::new(ir, &cached);
        options.state = Some(&self.state);
        options.timings = Some(&timings);
        let summary = build_global(&options).expect("the cached build runs");
        let state_after = fs::read_to_string(self.state.join(STATE_FILE)).ok();

        // What the state file on disk said should have hit, decided here rather
        // than taken from the code that decided it.
        let expected = usable_cache(&Run {
            options: &options,
            index: tree.index(),
            state_before: state_before.clone(),
            state_after: state_after.clone(),
            summary: &summary,
            facts: &facts,
            before_map: None,
        });
        let predicted = tree
            .index()
            .modules
            .iter()
            .filter(|entry| expected.get(&entry.module) == Some(&entry.content_hash))
            .count();
        assert_eq!(
            summary.cache_hits, predicted,
            "{name}: the cache hit on modules whose hash had moved, or missed on ones it had"
        );
        assert_eq!(
            summary.cache_hits + summary.cache_misses,
            tree.index().modules.len(),
            "{name}: every module is either read or reused"
        );

        // The oracle's own assertion: the two builds are the same files.
        for path in ARTIFACT_PATHS {
            let want = fs::read(scratch.join(path)).expect("the from-scratch artifact");
            let got = fs::read(cached.join(path)).expect("the cached artifact");
            assert!(
                want == got,
                "{name}: {path} differs between the from-scratch and the cached build at byte {} \
                 ({} B against {} B)",
                got.iter()
                    .zip(&want)
                    .position(|(a, b)| a != b)
                    .unwrap_or_else(|| want.len().min(got.len())),
                got.len(),
                want.len(),
            );
        }

        // The state file names exactly the modules the index does, in its order.
        let saved: Value = serde_json::from_str(
            state_after
                .as_deref()
                .expect("the cached build wrote a state"),
        )
        .expect("the state file is JSON");
        let saved_modules: Vec<&String> = saved["modules"]
            .as_object()
            .expect("the state has a module map")
            .keys()
            .collect();
        let index_modules: Vec<&String> = tree
            .index()
            .modules
            .iter()
            .map(|entry| &entry.module)
            .collect();
        assert_eq!(
            saved_modules, index_modules,
            "{name}: the saved state is not the index's modules in the index's order"
        );

        // The timings record: what `oracle.sh` reads the counts out of.
        let record: Value =
            serde_json::from_str(&fs::read_to_string(&timings).expect("the timings were written"))
                .expect("the timings are JSON");
        assert_eq!(record["cacheHits"], json!(summary.cache_hits), "{name}");
        assert_eq!(record["cacheMisses"], json!(summary.cache_misses), "{name}");
        assert_eq!(record["state"], json!("on"), "{name}");

        self.covered.extend(observe(&Run {
            options: &options,
            index: tree.index(),
            state_before,
            state_after,
            summary: &summary,
            facts: &facts,
            before_map: None,
        }));

        Step {
            hits: summary.cache_hits,
            misses: summary.cache_misses,
        }
    }

    /// Rewrites one key of the state file, the way `oracle.sh`'s seventh step
    /// does with `derivation`.
    fn tamper(&self, key: &str, value: Value) {
        let path = self.state.join(STATE_FILE);
        let mut state: Value =
            serde_json::from_str(&fs::read_to_string(&path).expect("there is a state to tamper"))
                .expect("the state is JSON");
        state[key] = value;
        fs::write(
            &path,
            serde_json::to_string(&state).expect("the state serialises"),
        )
        .expect("the state is writable");
    }

    fn corrupt(&self, body: &str) {
        fs::write(self.state.join(STATE_FILE), body).expect("the state is writable");
    }
}

/// The seven states, run over whatever IR `base` is, with `work` for the copies.
///
/// The mutations are synthetic and are **not** claimed to be what the extractor
/// would emit — `oracle.sh` says the same. They only have to be a valid IR whose
/// bytes and hash move together, which is the invariant the cache is keyed on.
fn seven_states(what: &str, base: &Path, trees: &TempDir) -> Sequence {
    let mut sequence = Sequence::new(what);
    let modules = IrTree::open(base)
        .expect("the base IR opens")
        .index()
        .modules
        .len();

    // 1. the unchanged tree with no state at all: the cache must not be needed
    //    for correctness, only for speed.
    let base_step = sequence.step("base", base);
    assert_eq!((base_step.hits, base_step.misses), (0, modules));

    // 2. the same tree again: every module is a hit and the bytes must not move.
    let rerun = sequence.step("rerun", base);
    assert_eq!((rerun.hits, rerun.misses), (modules, 0));

    // 3. one module's bytes change, and the hash moves with them.
    let modified_ir = trees.path().join("ir-mod");
    copy_ir(base, &modified_ir);
    mutate_modified(&modified_ir);
    let modified = sequence.step("modified", &modified_ir);
    assert_eq!((modified.hits, modified.misses), (modules - 1, 1));

    // 4. two modules disappear. The index is the authority on what exists, so
    //    the cache entries have to go with them.
    let removed_ir = trees.path().join("ir-del");
    copy_ir(&modified_ir, &removed_ir);
    let gone = mutate_removed(&removed_ir, 2);
    assert_eq!(gone.len(), 2);
    let removed = sequence.step("removed", &removed_ir);
    assert_eq!((removed.hits, removed.misses), (modules - 2, 0));

    // 5. a module appears, with declarations nothing has seen.
    let added_ir = trees.path().join("ir-add");
    copy_ir(&removed_ir, &added_ir);
    mutate_added(&added_ir);
    let added = sequence.step("added", &added_ir);
    assert_eq!((added.hits, added.misses), (modules - 2, 1));

    // 6. back to the original tree, with a state that has seen all of the
    //    above. A cache that only ever grows passes every step so far and fails
    //    this one: the module that was modified has its old hash back, the two
    //    that were deleted are not in the state any more, and the one that was
    //    added must not survive into the file.
    let restored = sequence.step("restored", base);
    assert_eq!((restored.hits, restored.misses), (modules - 3, 3));

    // 7. a state written by a different derivation is a guess, not a cache.
    sequence.tamper("derivation", json!("some older rule"));
    let stale = sequence.step("stale-state", base);
    assert_eq!(
        (stale.hits, stale.misses),
        (0, modules),
        "a state with a foreign derivation id was used as a cache"
    );
    sequence
}

// ------------------------------------------------------------- the IR states

fn read_json(path: &Path) -> Value {
    serde_json::from_str(&fs::read_to_string(path).unwrap_or_else(|e| panic!("{path:?}: {e}")))
        .unwrap_or_else(|e| panic!("{path:?}: {e}"))
}

fn write_json(path: &Path, value: &Value) {
    fs::create_dir_all(path.parent().expect("a file has a parent")).expect("writable");
    fs::write(path, serde_json::to_string(value).expect("serialises")).expect("writable");
}

/// A copy of an IR tree that can be mutated without touching the original —
/// which for the real corpus is a fixture this suite must not write to.
fn copy_ir(from: &Path, to: &Path) {
    let _ = fs::remove_dir_all(to);
    fs::create_dir_all(to).expect("writable");
    let index = read_json(&from.join("index.json"));
    fs::write(
        to.join("index.json"),
        fs::read(from.join("index.json")).expect("readable"),
    )
    .expect("writable");
    let files = index["modules"]
        .as_array()
        .expect("modules")
        .iter()
        .chain(index["dependencyMaps"].as_array().into_iter().flatten())
        .map(|entry| entry["file"].as_str().expect("a file path").to_owned());
    for file in files {
        let target = to.join(&file);
        fs::create_dir_all(target.parent().expect("a file has a parent")).expect("writable");
        fs::copy(from.join(&file), target).expect("copyable");
    }
}

/// The index entries sorted the way `oracle.sh` sorts them: most declarations
/// first, ties in index order (Python's sort is stable, and so is this one).
fn by_declarations(index: &Value) -> Vec<usize> {
    let modules = index["modules"].as_array().expect("modules");
    let mut order: Vec<usize> = (0..modules.len()).collect();
    order.sort_by_key(|i| std::cmp::Reverse(modules[*i]["declarations"].as_u64().unwrap_or(0)));
    order
}

/// State 3: a declaration is renamed and the module's hash moves with it.
fn mutate_modified(ir: &Path) -> String {
    let index_path = ir.join("index.json");
    let mut index = read_json(&index_path);
    let at = by_declarations(&index)[0];
    let file = index["modules"][at]["file"]
        .as_str()
        .expect("a file")
        .to_owned();
    let module_path = ir.join(&file);
    let mut module = read_json(&module_path);
    let last = module["declarations"]
        .as_array()
        .expect("declarations")
        .last()
        .expect("at least one declaration")["name"]
        .as_str()
        .expect("a name")
        .to_owned();
    let renamed = format!(
        "{}_renamed",
        module["declarations"][0]["name"].as_str().expect("a name")
    );
    module["declarations"][0]["name"] = json!(renamed);
    module["declarations"][0]["doc"] = json!(format!("mentions `Nat.find` and `{last}`"));
    write_json(&module_path, &module);

    let hash = index["modules"][at]["contentHash"]
        .as_str()
        .expect("a hash")
        .to_owned();
    index["modules"][at]["contentHash"] = json!(format!("0000{}", &hash[4..]));
    let module_name = index["modules"][at]["module"]
        .as_str()
        .expect("a name")
        .to_owned();
    write_json(&index_path, &index);
    module_name
}

/// State 4: `count` modules nobody imports disappear, files and index entries
/// both.
///
/// Leaves only, so that the tree stays consistent — `oracle.sh` says the same.
/// It takes both in one pass; this one takes them one at a time and recomputes,
/// because **the target package has exactly one module nobody imports**
/// 【実測: `InformationTheory`, the root that imports all 431 others】 and one
/// deletion does not distinguish "drop the entries that left" from "drop the
/// last entry".
fn mutate_removed(ir: &Path, count: usize) -> Vec<String> {
    let index_path = ir.join("index.json");
    let mut names = Vec::new();
    for _ in 0..count {
        let mut index = read_json(&index_path);
        let modules = index["modules"].as_array().expect("modules").clone();
        let own: BTreeSet<&str> = modules
            .iter()
            .map(|entry| entry["module"].as_str().expect("a name"))
            .collect();
        let mut imported: BTreeSet<String> = BTreeSet::new();
        for entry in &modules {
            let module = read_json(&ir.join(entry["file"].as_str().expect("a file")));
            for import in module["imports"].as_array().expect("imports") {
                let import = import.as_str().expect("a name");
                if own.contains(import) {
                    imported.insert(import.to_owned());
                }
            }
        }
        let Some(gone) = modules
            .iter()
            .find(|entry| !imported.contains(entry["module"].as_str().expect("a name")))
        else {
            break;
        };
        let name = gone["module"].as_str().expect("a name").to_owned();
        fs::remove_file(ir.join(gone["file"].as_str().expect("a file"))).expect("removable");
        index["modules"] = Value::Array(
            modules
                .iter()
                .filter(|entry| entry["module"].as_str() != Some(name.as_str()))
                .cloned()
                .collect(),
        );
        index["moduleCount"] = json!(index["modules"].as_array().expect("modules").len());
        write_json(&index_path, &index);
        names.push(name);
    }
    names
}

/// State 5: a module appears, with declarations no other module declares.
fn mutate_added(ir: &Path) -> String {
    let index_path = ir.join("index.json");
    let mut index = read_json(&index_path);
    let at = by_declarations(&index)[1];
    let source = index["modules"][at].clone();
    let mut module = read_json(&ir.join(source["file"].as_str().expect("a file")));
    let new = format!("{}Added", module["module"].as_str().expect("a name"));
    module["module"] = json!(new);
    for decl in module["declarations"].as_array_mut().expect("declarations") {
        decl["name"] = json!(format!("{}_added", decl["name"].as_str().expect("a name")));
    }
    module["imports"]
        .as_array_mut()
        .expect("imports")
        .push(source["module"].clone());
    let file = format!("modules/{new}.json");
    let body = serde_json::to_string(&module).expect("serialises");
    fs::write(ir.join(&file), &body).expect("writable");
    index["modules"]
        .as_array_mut()
        .expect("modules")
        .push(json!({
            "bytes": body.len(),
            "contentHash": "addedaddedadded1",
            "declarations": module["declarations"].as_array().expect("declarations").len(),
            "file": file,
            "module": new,
        }));
    index["moduleCount"] = json!(index["modules"].as_array().expect("modules").len());
    write_json(&index_path, &index);
    new
}

// ------------------------------------------------------------ a synthetic IR

/// A declaration with every schema-5 key `litedoc4_ir` requires — the same
/// shape the (now frozen) `tests/oracle/gen-global-expected.ts` wrote.
#[expect(
    clippy::needless_pass_by_value,
    reason = "`json!` takes the value, so a reference would only move the clone"
)]
fn decl(name: &str, kind: &str, doc: Option<&str>, type_code: Value) -> Value {
    json!({
        "name": name, "kind": kind, "modifiers": [], "binders": [], "implicits": [],
        "binderCode": [], "type": "Prop", "typeCode": type_code, "line": 1, "col": 0,
        "endLine": 1, "endCol": 1, "index": 0, "members": [], "doc": doc,
        "equations": [], "equationCode": [], "refs": [],
    })
}

/// One module of a synthetic IR: name, imports, declarations, and the hash the
/// index will carry for it.
struct Synthetic {
    module: &'static str,
    hash: &'static str,
    imports: Vec<&'static str>,
    decls: Vec<Value>,
}

fn write_synthetic(root: &Path, modules: &[Synthetic], deps: &[(&str, Value)]) {
    let mut entries = Vec::new();
    let mut declarations = 0usize;
    for module in modules {
        let file = format!("modules/{}.json", module.module);
        let body = serde_json::to_string(&json!({
            "schemaVersion": 5,
            "module": module.module,
            "imports": module.imports,
            "moduleDocs": [],
            "tactics": [],
            "declarations": module.decls,
        }))
        .expect("serialises");
        let path = root.join(&file);
        fs::create_dir_all(path.parent().expect("a parent")).expect("writable");
        fs::write(&path, &body).expect("writable");
        declarations += module.decls.len();
        entries.push(json!({
            "bytes": body.len(),
            "contentHash": module.hash,
            "declarations": module.decls.len(),
            "file": file,
            "module": module.module,
        }));
    }
    let mut dep_entries = Vec::new();
    for (package, map) in deps {
        let file = format!("deps/{package}.json");
        let body = serde_json::to_string(&json!({
            "schemaVersion": 5, "package": package, "declarations": map,
        }))
        .expect("serialises");
        let path = root.join(&file);
        fs::create_dir_all(path.parent().expect("a parent")).expect("writable");
        fs::write(&path, &body).expect("writable");
        dep_entries.push(json!({
            "bytes": body.len(),
            "entries": map.as_object().expect("a map").len(),
            "file": file,
            "package": package,
        }));
    }
    write_json(
        &root.join("index.json"),
        &json!({
            "declarationCount": declarations,
            "dependencyMaps": dep_entries,
            "generator": "tests/state_and_delta.rs",
            "hashAlgorithm": "lean-string-hash-64/hex16",
            "leanVersion": "4.31.0",
            "moduleCount": modules.len(),
            "modules": entries,
            "schemaVersion": 5,
        }),
    );
}

/// U+1D49C MATHEMATICAL SCRIPT CAPITAL A: a surrogate pair, so it sorts *below*
/// every BMP name in UTF-16 and above them by code point (plan §7, U1). No name
/// of the target package is above the BMP【実測】, so nothing derived from the
/// corpus can tell the affected set's sort order from a UTF-8 one.
const ASTRAL: &str = "\u{1D49C}";

/// U+FB00 LATIN SMALL LIGATURE FF: the other half of U1.
///
/// [`ASTRAL`] alone proves nothing about the sort — its first UTF-16 code unit
/// is 0xD835, which is above every ASCII letter in *both* orders, so a UTF-8
/// sort puts it in the same place. It is only against a BMP character above the
/// surrogate range that the two orders invert: `𝒜` sorts **before** `ﬀ` in
/// UTF-16 and after it by code point. Every affected-set assertion below needs
/// both.
const LIGATURE: &str = "\u{FB00}";

/// The package the seven synthetic states start from.
///
/// Six modules, of which `Pkg.B` has the most declarations (so it is the one
/// state 3 modifies) and three are leaves (so states 4 and 5 have something to
/// remove and copy).
fn synthetic_base(root: &Path) {
    let astral_module: &'static str = Box::leak(format!("Pkg.{ASTRAL}").into_boxed_str());
    let astral_decl: &'static str = Box::leak(format!("Pkg.{ASTRAL}.g").into_boxed_str());
    write_synthetic(
        root,
        &[
            Synthetic {
                module: "Pkg",
                hash: "1111111111111111",
                imports: vec![],
                decls: vec![decl(
                    "Pkg.a",
                    "def",
                    Some("See `Pkg.B.b` and `Nat.find`."),
                    json!([]),
                )],
            },
            Synthetic {
                module: "Pkg.B",
                hash: "2222222222222222",
                imports: vec!["Pkg"],
                decls: vec![
                    decl(
                        "Pkg.B.b",
                        "instance",
                        Some("An instance mentioning `Pkg.a`."),
                        json!([[0, 5, 1, "Cls.B"]]),
                    ),
                    decl("Pkg.B.c", "theorem", Some("`Pkg.a` again."), json!([])),
                ],
            },
            Synthetic {
                module: "Pkg.C",
                hash: "3333333333333333",
                imports: vec!["Pkg", "Pkg.B"],
                decls: vec![decl(
                    "Pkg.C.d",
                    "theorem",
                    Some("`Pkg.B.b` and [x](Pkg.a)."),
                    json!([]),
                )],
            },
            Synthetic {
                module: "Pkg.Leaf1",
                hash: "4444444444444444",
                imports: vec!["Pkg"],
                decls: vec![decl("Pkg.Leaf1.e", "def", None, json!([]))],
            },
            Synthetic {
                module: "Pkg.Leaf2",
                hash: "5555555555555555",
                imports: vec!["Pkg.B"],
                decls: vec![decl("Pkg.Leaf2.f", "def", Some("`Pkg.a`"), json!([]))],
            },
            Synthetic {
                module: astral_module,
                hash: "6666666666666666",
                imports: vec!["Pkg"],
                decls: vec![decl(astral_decl, "def", Some("`Pkg.a`"), json!([]))],
            },
        ],
        &[("Dep", json!({ "Dep.one": "Dep.Home" }))],
    );
}

// ------------------------------------------------------------------ the tests

/// `oracle.sh`'s seven states over an IR built here, so that this passes on a
/// machine that has never seen the target package.
#[test]
fn the_seven_states_agree_with_a_from_scratch_build() {
    let trees = TEMP.make("synthetic-states");
    let base = trees.path().join("ir");
    synthetic_base(&base);
    let sequence = seven_states("synthetic", &base, &trees);
    assert_eq!(sequence.steps, 7);
}

/// The same seven states over the real 432-module IR — `#[ignore]`d because
/// that IR is not in this repository, the convention `tests/global.rs` uses for
/// the corpus.
#[test]
#[ignore = "corpus: needs LITEDOC4_IR (tools/corpus-gate.sh)"]
fn the_seven_states_agree_over_the_real_corpus() {
    let ir = corpus_ir();
    let trees = TEMP.make("corpus-states");
    let base = trees.path().join("ir");
    copy_ir(&ir, &base);
    let sequence = seven_states("corpus", &base, &trees);
    assert_eq!(sequence.steps, 7);
}

/// The facts this crate derives, against the state file the frozen prototype
/// wrote over the same IR — **byte for byte, modulo the derivation string**.
///
/// This is the only oracle [`ModuleFacts::tokens`] has over the whole corpus
/// that is a file rather than a digest, and it is worth having for one reason:
/// no artifact carries the tokens, so the artifact comparison is blind to
/// 818,331 B of facts that the map delta is entirely made of. 432 modules'
/// imports, declaration kinds, instance heads and token lists agree to the byte.
///
/// # M8-d: the comparison is now against a *shim*, and that is the whole edit
///
/// [`ModuleFacts`] grew [`ModuleFacts::instances_for`], which the prototype has
/// no notion of, so the file on disk is no longer the prototype's bytes and
/// never can be again. What is still comparable is everything else, so the
/// prototype's seven keys are re-serialised here through [`PrototypeFacts`] —
/// the same trick `tests/global.rs` uses for its digest — and *that* is compared
/// byte for byte. The two assertions after it are what keep the shim honest: the
/// file that was actually written has to *start* with these bytes' keys, in this
/// order, and agree on every one of them, for every module. **It does not name
/// the keys that follow** — that is HEAD's shape, it is asserted where HEAD is
/// ([`litedoc4_global::facts::PROTOTYPE_FACT_KEYS`]), and naming it here is what went
/// stale: this test cannot run on this machine, so C-2's `refs` falsified a
/// hand-written "plus one appended key" without a single failure anywhere.
///
/// The derivation string differs on purpose, so that neither implementation can
/// read the other's cache; the prototype's is substituted before the comparison
/// and that is the only other edit.
#[test]
#[ignore = "corpus: needs LITEDOC4_IR + LITEDOC4_PROTOTYPE_STATE (tools/corpus-gate.sh)"]
fn the_state_file_is_the_prototypes_bytes() {
    let ir = corpus_ir();
    // `raw` and not `path`: the `fs::read` below is the stronger check — it
    // reports the `io::Error`, which says *why* the file could not be read
    // rather than only that a file count came out zero.
    let prototype = corpus::LITEDOC4_PROTOTYPE_STATE.raw();
    let want = fs::read(&prototype).unwrap_or_else(|e| {
        panic!(
            "no prototype state at {} ({e}): set LITEDOC4_PROTOTYPE_STATE, or run this test \
             through tools/corpus-gate.sh, which is the only thing that should be asking for it",
            prototype.display()
        )
    });
    // Pinned so that the numbers in the report have a home: 26 bytes of
    // `stage7h/global.ts facts v1` against 24 of `litedoc4-global facts v2`.
    assert_eq!(want.len(), 841_949);
    assert_eq!(
        STATE_DERIVATION.len() + 2,
        "stage7h/global.ts facts v1".len()
    );

    let work = TEMP.make("state-bytes");
    let site = work.path().join("site");
    let state = work.path().join("state");
    let mut options = GlobalOptions::new(&ir, &site);
    options.state = Some(&state);
    let summary = build_global(&options).expect("the corpus builds");
    let got = fs::read_to_string(state.join(STATE_FILE)).expect("the state was written");
    assert_eq!(got.len(), summary.state_bytes);
    // **The total is not pinned, on purpose**【判断 2026-08-22】. `got.len()` is
    // a joint property of HEAD and of whichever corpus `LITEDOC4_IR` names, so a
    // bare integer cannot say which of the two moved when it fails — and one of
    // them has moved: feature-sweep C-2 added `ModuleFacts::refs`, worth
    // 472,440 B on the 422-module IR this machine can still produce 【実測
    // 2026-08-22 → `benchmarks/results/usedby-2026-08-22.txt` §3】, on a state
    // file that was 838 KB.
    //
    // The numbers the pin used to carry keep their conditions instead of their
    // assert: the v1 file was **841,947 B** and `instancesFor` on the
    // **432-module** corpus cost **20,052 B**, of which 432 x 17 is the empty
    // key itself — **861,999 B** in total 【実測 2026-08-16】. That corpus is
    // gone from here (`/private/tmp/lean-doc-relay/w7h/base-ir`) and the target
    // package no longer has 432 modules, so the `refs` term of the sum has no
    // measurement, and inventing one would be worse than having none.
    //
    // What stays asserted is what the corpus does not decide: the file is
    // self-consistent with the summary (above), the prototype's half of it is
    // pinned by `shim.len()` (below), and every module's entry starts with the
    // prototype's keys and agrees on all seven. A restorer who re-measures the
    // total puts it in `benchmarks/results/`, which is where a number that only
    // means something together with its conditions belongs.

    // The prototype's shape, from the facts the file above was built from.
    let tree = IrTree::open(&ir).expect("the corpus opens");
    let facts = facts_for(&tree, &State::empty())
        .expect("the corpus reads")
        .facts;
    let shim = serde_json::to_string(&PrototypeState {
        state_version: STATE_VERSION,
        derivation: STATE_DERIVATION,
        schema_version: tree.index().schema_version,
        generator: &tree.index().generator,
        modules: PrototypeModules(&facts),
    })
    .expect("the shim serialises");
    assert_eq!(shim.len(), 841_947);
    // `PrototypeFacts` is the second transcription of the prototype's seven
    // keys (`tests/global.rs`'s `Facts` is the first). Neither is the source:
    // both are checked against it, so a change to one cannot quietly disagree
    // with the other.
    assert_eq!(
        serde_json::from_str::<Value>(&shim).expect("the shim is JSON")["modules"]
            .as_object()
            .and_then(|modules| modules.values().next())
            .and_then(Value::as_object)
            .map(|facts| facts.keys().map(String::as_str).collect::<Vec<_>>())
            .expect("the shim has at least one module"),
        PROTOTYPE_FACT_KEYS,
        "PrototypeFacts is no longer the prototype's keys"
    );

    let want = String::from_utf8(want)
        .expect("the state is UTF-8")
        .replacen("stage7h/global.ts facts v1", STATE_DERIVATION, 1);
    assert_eq!(want.len(), shim.len());
    assert!(
        want == shim,
        "the facts differ from the prototype's at byte {}",
        shim.bytes()
            .zip(want.bytes())
            .position(|(a, b)| a != b)
            .unwrap_or(shim.len())
    );

    // …and the file on disk is the shim plus one key per module, last.
    let written: Value = serde_json::from_str(&got).expect("the state is JSON");
    let shimmed: Value = serde_json::from_str(&shim).expect("the shim is JSON");
    let written_modules = written["modules"].as_object().expect("a module map");
    let shimmed_modules = shimmed["modules"].as_object().expect("a module map");
    assert_eq!(
        written_modules.keys().collect::<Vec<_>>(),
        shimmed_modules.keys().collect::<Vec<_>>(),
        "the two files do not name the same modules in the same order"
    );
    for (module, entry) in written_modules {
        let entry = entry.as_object().expect("one module's facts");
        let shimmed = shimmed_modules[module].as_object().expect("the same");
        let keys: Vec<&str> = entry.keys().map(String::as_str).collect();
        let prototype: Vec<&str> = shimmed.keys().map(String::as_str).collect();
        assert!(
            keys.starts_with(&prototype),
            "{module}: the state file's keys do not start with the prototype's — {keys:?}"
        );
        for (key, value) in shimmed {
            assert_eq!(&entry[key], value, "{module}.{key}");
        }
    }
}

/// [`ModuleFacts`] with the prototype's seven keys and no others, in the
/// prototype's order — the shape `stage7h/global.ts` wrote and the only shape
/// its file can be compared with.
///
/// A copy of the field list rather than a `#[serde(skip)]` on the real struct
/// 【判断】: skipping the key would keep it out of the cache too, and a cached
/// entry that has lost `instancesFor` is a site whose Instances For blocks are
/// empty on every module that hit. The duplication is what makes the omission
/// local to this test.
#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
struct PrototypeFacts<'a> {
    module: &'a str,
    content_hash: &'a str,
    imports: &'a [String],
    tactics: usize,
    decls: &'a [(String, String)],
    instances: &'a [(String, String)],
    tokens: &'a [String],
}

impl<'a> From<&'a ModuleFacts> for PrototypeFacts<'a> {
    fn from(facts: &'a ModuleFacts) -> Self {
        Self {
            module: &facts.module,
            content_hash: &facts.content_hash,
            imports: &facts.imports,
            tactics: facts.tactics,
            decls: &facts.decls,
            instances: &facts.instances,
            tokens: &facts.tokens,
        }
    }
}

/// The wrapper `state.rs` writes, with the same key order.
#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
struct PrototypeState<'a> {
    state_version: u64,
    derivation: &'a str,
    schema_version: u32,
    generator: &'a str,
    modules: PrototypeModules<'a>,
}

struct PrototypeModules<'a>(&'a [ModuleFacts]);

impl serde::Serialize for PrototypeModules<'_> {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.collect_map(
            self.0
                .iter()
                .map(|facts| (facts.module.as_str(), PrototypeFacts::from(facts))),
        )
    }
}

/// The map delta against the prototype's own answer for the same mutation,
/// over the real corpus.
///
/// `--print-set` is compared byte for byte because it is the file the
/// incremental pipeline consumes; the counts beside it are what a digest cannot
/// say when it disagrees.
#[test]
#[ignore = "corpus: needs LITEDOC4_IR + LITEDOC4_REFERENCE_GLOBAL (tools/corpus-gate.sh)"]
fn the_delta_is_the_prototypes_delta() {
    let expected = delta_fixture();
    let (ir, reference) = (corpus_ir(), corpus_reference());

    // `before` is the reference `name-map.json` with the three edits the
    // generator chose, rebuilt here from the recorded choice rather than
    // committed: it is 602,729 B of the prototype's own output plus five
    // strings.
    let after: BTreeMap<String, String> = serde_json::from_str(
        &fs::read_to_string(reference.join(NAME_MAP)).expect("the reference name map"),
    )
    .expect("the name map is a flat string map");
    let mutation = &expected.mutation;
    let mut before = after.clone();
    assert!(
        before.contains_key(&mutation.moved_name) && before.contains_key(&mutation.dropped_name),
        "the reference tree is not the one the fixture was taken from"
    );
    before.insert(mutation.moved_name.clone(), mutation.moved_to.clone());
    before.remove(&mutation.dropped_name);
    before.insert(
        mutation.inserted_name.clone(),
        mutation.inserted_module.clone(),
    );
    assert_eq!(before.len(), expected.before_names);
    assert_eq!(after.len(), expected.after_names);

    let work = TEMP.make("delta-differential");
    let before_path = work.path().join("before.json");
    fs::write(
        &before_path,
        serde_json::to_string(&before).expect("serialises"),
    )
    .expect("writable");
    let print_set = work.path().join("set.txt");
    let delta_json = work.path().join("delta.json");
    let site = work.path().join("site");
    let mut options = GlobalOptions::new(&ir, &site);
    options.before = Some(&before_path);
    options.print_set = Some(&print_set);
    options.delta_json = Some(&delta_json);
    let summary = build_global(&options).expect("the corpus builds");
    let delta = summary.delta.as_ref().expect("--before turns the delta on");

    assert_eq!(delta.before_names, expected.before_names);
    assert_eq!(delta.after_names, expected.after_names);
    assert_eq!(delta.changed.len(), expected.changed_names);
    assert_eq!(delta.changed, expected.changed_sample, "changed sample");
    assert_eq!(delta.affected.len(), expected.affected);
    assert_eq!(delta.affected, expected.affected_modules);
    let witnesses: Vec<(String, String)> = delta
        .witnesses
        .iter()
        .map(|w| (w.module.clone(), w.name.clone()))
        .collect();
    let want: Vec<(String, String)> = expected
        .witnesses
        .iter()
        .map(|w| (w.module.clone(), w.name.clone()))
        .collect();
    assert_eq!(witnesses, want, "witnesses");

    let body = fs::read(&print_set).expect("the print set was written");
    assert_eq!(body.len(), expected.print_set_bytes);
    assert_eq!(fnv1a64(&body), expected.print_set_fnv1a64);
    assert_eq!(body, delta.print_set().into_bytes());

    let tree = IrTree::open(&ir).expect("the corpus opens");
    let facts = facts_for(&tree, &State::empty())
        .expect("the corpus reads")
        .facts;
    let mut covered = observe(&Run {
        options: &options,
        index: tree.index(),
        state_before: None,
        state_after: None,
        summary: &summary,
        facts: &facts,
        before_map: Some(&before),
    });

    // The other half of the file format, and the case the pipeline takes on
    // most runs: an unchanged map writes a file with no bytes in it at all.
    let unchanged = work.path().join("unchanged.txt");
    let name_map = reference.join(NAME_MAP);
    let mut options = GlobalOptions::new(&ir, &site);
    options.before = Some(&name_map);
    options.print_set = Some(&unchanged);
    let summary = build_global(&options).expect("the corpus builds");
    let delta = summary.delta.as_ref().expect("--before turns the delta on");
    assert!(delta.changed.is_empty(), "the reference map is this map");
    assert_eq!(
        fs::read(&unchanged)
            .expect("the print set was written")
            .len(),
        expected.unchanged_print_set_bytes
    );
    assert_eq!(expected.unchanged_print_set_bytes, 0);
    covered.extend(observe(&Run {
        options: &options,
        index: tree.index(),
        state_before: None,
        state_after: None,
        summary: &summary,
        facts: &facts,
        before_map: Some(&after),
    }));

    // What the real corpus reaches by being run through a delta at all — the
    // other half of the coverage claim in
    // `the_curated_cases_cover_what_the_package_does_not`, measured here
    // because these two builds are the only ones over the corpus that pass
    // `--before`.
    assert_eq!(
        covered,
        BTreeSet::from(CORPUS_DELTA),
        "which branches the corpus delta reaches has changed"
    );
}

/// The delta's corners, none of which the corpus reaches: an empty change set,
/// a change nothing mentions, more than twenty of everything, a module above
/// the BMP, and an affected set whose order is not the index's.
#[test]
fn the_curated_deltas_reach_what_the_corpus_does_not() {
    let covered = curated_delta_branches();
    for branch in [
        "changedEmpty",
        "changedSampleTruncated",
        "affectedEmpty",
        "witnessLimitReached",
        "witnessNotFirstToken",
        "affectedSortReorders",
        "affectedAboveBmp",
        "printSetEmptyFile",
        "printSetOmitted",
        "deltaJsonOmitted",
    ] {
        assert!(
            covered.contains(branch),
            "no curated delta reaches {branch}"
        );
    }
}

/// V6 end to end: the curated IR reaches `tokenSeparatorV8Only`, which is the
/// branch that decides which separator set the affected set is computed with.
///
/// Asserted **whether or not the corpus is on this machine**: the whole point
/// of the curated case is that no real data reaches this branch
/// ([`NO_REAL_DATA_REACHES`]), so the one exercise it has must not travel with
/// the corpus. Split out of
/// [`the_curated_tokens_reach_what_the_corpus_does_not`], which is `#[ignore]`d
/// because its other half reads the corpus.
///
/// [`the_curated_tokens_reach_what_the_corpus_does_not`]: the_curated_tokens_reach_what_the_corpus_does_not
#[test]
fn the_curated_tokens_reach_the_disputed_separator() {
    assert!(curated_token_branches().contains("tokenSeparatorV8Only"));
}

/// The other half of V6: the measured fact that makes the curated case above
/// the only thing testing the separator set — the target package contains none
/// of the 4,803 code points the two tables disagree about.
#[test]
#[ignore = "corpus: needs LITEDOC4_IR (tools/corpus-gate.sh)"]
fn the_curated_tokens_reach_what_the_corpus_does_not() {
    let ir = corpus_ir();
    assert!(
        !meets_a_v8_only_separator(&ir),
        "the target package now contains a code point the two separator sets disagree about: the \
         state file can no longer be expected to be the prototype's bytes, and V6's measurement \
         (0 of 233,713 code points inside 16,044 code spans) has to be taken again"
    );
}

/// The dependency this milestone's coverage rests on, stated so that it fails
/// when it stops being true (plan §7: 「全件バイト一致」は分岐被覆の証明ではない).
///
/// Four claims, all of them counted rather than believed:
///
/// 1. The full-corpus six-file comparison — what M2-a was judged on — reaches
///    **5 of the 35** branches M2-b added. Every `--state` and `--before` path
///    is invisible to it.
/// 2. The seven states reach **13 of 35**; the seventeen delta branches and
///    three of the four foreign-state shapes are outside what a cache sequence
///    can produce.
/// 3. Together with the corpus delta, real data reaches **26 of 35**. The other
///    **9** ([`NO_REAL_DATA_REACHES`]) are reachable only by a written-down
///    case, so every one of them is one.
/// 4. Everything together is all 35.
#[test]
fn the_curated_cases_cover_what_the_package_does_not() {
    let trees = TEMP.make("coverage");
    let base = trees.path().join("ir");
    synthetic_base(&base);

    // (1) A run with neither flag: one path through every branch here.
    let work = TEMP.make("six-file");
    let options = GlobalOptions::new(&base, work.path());
    let tree = IrTree::open(&base).expect("the IR opens");
    let facts = facts_for(&tree, &State::empty()).expect("reads").facts;
    let summary = build_global(&options).expect("builds");
    let six_file = observe(&Run {
        options: &options,
        index: tree.index(),
        state_before: None,
        state_after: None,
        summary: &summary,
        facts: &facts,
        before_map: None,
    });
    assert_eq!(
        six_file,
        BTreeSet::from(SIX_FILE_COMPARISON),
        "the six-file byte comparison reaches a different set of branches than it did"
    );
    assert_eq!(six_file.len(), 5);

    // (2) The seven states.
    let sequence = seven_states("coverage", &base, &trees);
    let uncovered: BTreeSet<&str> = BRANCHES
        .iter()
        .copied()
        .filter(|branch| !sequence.covered.contains(branch))
        .collect();
    assert_eq!(
        uncovered,
        BTreeSet::from([
            // The delta, all of it: the seven states never pass `--before`.
            "deltaOn",
            "changedValueDiffers",
            "changedOnlyInBefore",
            "changedOnlyInAfter",
            "changedEmpty",
            "changedSampleTruncated",
            "affectedEmpty",
            "affectedNonEmpty",
            "witnessLimitReached",
            "witnessNotFirstToken",
            "affectedSortReorders",
            "affectedAboveBmp",
            "printSetEmptyFile",
            "printSetNonEmpty",
            "printSetOmitted",
            "deltaJsonWritten",
            "deltaJsonOmitted",
            // Three of the four ways a state file can be foreign. `oracle.sh`
            // only has the fourth (`derivation`), and the other three are the
            // ones an IR upgrade would actually produce.
            "stateUnparseable",
            "stateVersionMismatch",
            "stateSchemaMismatch",
            "stateGeneratorMismatch",
            // No docstring of the synthetic package — or of the real one —
            // contains a code point the two separator sets disagree about.
            "tokenSeparatorV8Only",
        ]),
        "which branches the seven states leave uncovered has changed"
    );
    assert_eq!(sequence.covered.len(), 13);

    // (3) Everything real data can reach, and what is left over.
    let mut real_data = sequence.covered.clone();
    real_data.extend(CORPUS_DELTA);
    assert_eq!(real_data.len(), 26);
    let only_curated: BTreeSet<&str> = BRANCHES
        .iter()
        .copied()
        .filter(|branch| !real_data.contains(branch))
        .collect();
    assert_eq!(
        only_curated,
        BTreeSet::from(NO_REAL_DATA_REACHES),
        "which branches no real-data exercise reaches has changed"
    );

    // (4) Everything, together. The curated cases are what stands between the
    // eight branches above and nothing at all testing them.
    let mut all = real_data;
    let curated = {
        let mut curated = curated_delta_branches();
        curated.extend(curated_state_branches());
        curated.extend(curated_token_branches());
        curated
    };
    for branch in NO_REAL_DATA_REACHES {
        assert!(
            curated.contains(branch),
            "{branch} is reached by no real data and by no curated case either"
        );
    }
    all.extend(curated);
    let missing: Vec<&str> = BRANCHES
        .iter()
        .copied()
        .filter(|branch| !all.contains(branch))
        .collect();
    assert!(
        missing.is_empty(),
        "these branches fire nowhere at all: {missing:?}"
    );
    assert_eq!(all.len(), BRANCHES.len());
}

// -------------------------------------------------------- the curated cases

/// The four ways a state file can be foreign that the seven states do not
/// produce: unparseable, and each of the three version keys other than
/// `derivation`.
///
/// Every one of them must load as an empty cache — silently, and with every
/// module read again.
fn curated_state_branches() -> BTreeSet<&'static str> {
    let trees = TEMP.make("foreign-states");
    let base = trees.path().join("ir");
    synthetic_base(&base);
    let modules = IrTree::open(&base).expect("opens").index().modules.len();

    let mut covered = BTreeSet::new();
    for (what, damage) in [
        ("unparseable", Damage::Corrupt("{\"stateVersion\": ")),
        ("not JSON at all", Damage::Corrupt("nonsense")),
        ("an empty file", Damage::Corrupt("")),
        ("a JSON array", Damage::Corrupt("[]")),
        ("a newer format", Damage::Key("stateVersion", json!(99))),
        ("another schema", Damage::Key("schemaVersion", json!(3))),
        (
            "another extractor",
            Damage::Key("generator", json!("some other extractor")),
        ),
    ] {
        let mut sequence = Sequence::new(what);
        let warm = sequence.step("warm", &base);
        assert_eq!(warm.misses, modules);
        let hot = sequence.step("hot", &base);
        assert_eq!(hot.hits, modules, "{what}: the cache did not warm up");
        match damage {
            Damage::Corrupt(body) => sequence.corrupt(body),
            Damage::Key(key, value) => sequence.tamper(key, value),
        }
        let cold = sequence.step("damaged", &base);
        assert_eq!(
            (cold.hits, cold.misses),
            (0, modules),
            "{what}: a state that is not this run's was used as a cache"
        );
        covered.extend(sequence.covered);
    }
    covered
}

enum Damage {
    Corrupt(&'static str),
    Key(&'static str, Value),
}

/// U+088F ARABIC HALF MADDA OVER MADDA: **a separator for V8 and not for
/// UnicodeBasic**, the first of the 4,803 code points the two tables disagree
/// about 【実測 2026-08-12】. Nothing in the target package contains it, or any
/// of the other 4,802.
const V8_ONLY_SEPARATOR: char = '\u{088F}';

/// V6: the tokeniser splits on the **union** of the prototype's separator set
/// and the renderer's, and the corpus reaches neither half of the disagreement.
///
/// The failure this rules out is silent. With the split narrowed to
/// UnicodeBasic's set — the renderer's, and the obvious "simplification" —
/// `` `Pkg.moved\u{088F}Tail` `` is one token, `Pkg.moved` is not among a
/// module's tokens, and the module is **missing from the affected set** when
/// `Pkg.moved` moves. Nothing downstream notices: the site builds and the page
/// keeps a link to the module the name used to live in.
fn curated_token_branches() -> BTreeSet<&'static str> {
    let trees = TEMP.make("curated-tokens");
    let ir = trees.path().join("ir");
    let split_doc = format!("`Pkg.moved{V8_ONLY_SEPARATOR}Tail`");
    write_synthetic(
        &ir,
        &[
            Synthetic {
                module: "Pkg.Alpha",
                hash: "1111111111111111",
                imports: vec![],
                decls: vec![decl("Pkg.moved", "def", None, json!([]))],
            },
            // The control: the same name in a code span with nothing unusual in
            // it, so that a delta that finds nothing at all is not mistaken for
            // the separator being handled.
            Synthetic {
                module: "Pkg.Plain",
                hash: "2222222222222222",
                imports: vec![],
                decls: vec![decl("Pkg.Plain.p", "def", Some("`Pkg.moved`."), json!([]))],
            },
            Synthetic {
                module: "Pkg.Split",
                hash: "3333333333333333",
                imports: vec![],
                decls: vec![decl("Pkg.Split.s", "def", Some(&split_doc), json!([]))],
            },
        ],
        &[],
    );

    let site = trees.path().join("site");
    build_global(&GlobalOptions::new(&ir, &site)).expect("builds");
    let mut before = name_map(&site);
    before.insert("Pkg.moved".to_owned(), "Somewhere.Else".to_owned());
    let (fired, delta) = run_delta(&trees, "separator", &ir, before, true, true);
    assert_eq!(delta.changed, ["Pkg.moved"]);
    assert_eq!(
        delta.affected,
        ["Pkg.Plain", "Pkg.Split"],
        "`Pkg.Split` mentions `Pkg.moved` before a code point V8 separates on and UnicodeBasic \
         does not; splitting on UnicodeBasic's set alone drops it from the affected set and \
         leaves its page linking a name that has moved"
    );
    assert_eq!(delta.witnesses[1].name, "Pkg.moved");
    // The same thing one level down, so that a failure above can be read
    // without guessing which half of the pipeline moved.
    assert_eq!(
        autolink_tokens(&split_doc),
        ["Pkg.moved", "moved", "Tail"],
        "the split is not the union of the two separator sets: U+{:04X} stayed inside a token",
        V8_ONLY_SEPARATOR as u32
    );
    assert!(
        fired.contains("tokenSeparatorV8Only"),
        "the curated IR does not actually contain a disputed code point"
    );
    fired
}

/// The delta's corners, over IRs small enough to say what the answer should be.
fn curated_delta_branches() -> BTreeSet<&'static str> {
    let trees = TEMP.make("curated-deltas");
    let mut covered = BTreeSet::new();

    // A package whose modules mention each other, in an index order that is not
    // the sorted order, and whose last two modules are the U1 pair: `Pkg.𝒜`
    // sorts before `Pkg.ﬀ` in UTF-16 and after it by code point, so the
    // affected set below is the only thing in this suite that can tell
    // `cmp_utf16` from `str::cmp`.
    let astral_module: &'static str = Box::leak(format!("Pkg.{ASTRAL}").into_boxed_str());
    let astral_decl: &'static str = Box::leak(format!("Pkg.{ASTRAL}.g").into_boxed_str());
    let ligature_module: &'static str = Box::leak(format!("Pkg.{LIGATURE}").into_boxed_str());
    let ligature_decl: &'static str = Box::leak(format!("Pkg.{LIGATURE}.h").into_boxed_str());
    let ir = trees.path().join("ir");
    write_synthetic(
        &ir,
        &[
            Synthetic {
                module: "Pkg.Zed",
                hash: "1111111111111111",
                imports: vec![],
                // `Pkg.aaa` sorts before `Pkg.moved` among this module's
                // tokens, so the witness is not the first token unless the scan
                // looks for the *matching* one.
                decls: vec![decl(
                    "Pkg.Zed.z",
                    "def",
                    Some("`Pkg.aaa` and `Pkg.moved`."),
                    json!([]),
                )],
            },
            Synthetic {
                module: "Pkg.Alpha",
                hash: "2222222222222222",
                imports: vec![],
                decls: vec![
                    decl("Pkg.aaa", "def", Some("`Pkg.moved`."), json!([])),
                    decl("Pkg.moved", "def", None, json!([])),
                ],
            },
            Synthetic {
                module: astral_module,
                hash: "3333333333333333",
                imports: vec![],
                decls: vec![decl(astral_decl, "def", Some("`Pkg.moved`."), json!([]))],
            },
            Synthetic {
                module: ligature_module,
                hash: "5555555555555555",
                imports: vec![],
                decls: vec![decl(ligature_decl, "def", Some("`Pkg.moved`."), json!([]))],
            },
            Synthetic {
                module: "Pkg.Quiet",
                hash: "4444444444444444",
                imports: vec![],
                decls: vec![decl("Pkg.Quiet.q", "def", Some("no names here"), json!([]))],
            },
        ],
        &[("Dep", json!({ "Dep.one": "Dep.Home" }))],
    );

    let site = trees.path().join("site");
    let after: BTreeMap<String, String> = {
        let work = GlobalOptions::new(&ir, &site);
        build_global(&work).expect("builds");
        name_map(&site)
    };

    // 1. Nothing changed: the scan is skipped and the print set is a file with
    //    no bytes.
    let (fired, delta) = run_delta(&trees, "unchanged", &ir, after.clone(), true, true);
    assert!(delta.changed.is_empty() && delta.affected.is_empty());
    covered.extend(fired);

    // 2. A change nothing mentions: the scan runs and finds nothing.
    let mut quiet = after.clone();
    quiet.insert("Unmentioned.name".to_owned(), "Elsewhere".to_owned());
    let (fired, delta) = run_delta(&trees, "unmentioned", &ir, quiet, true, true);
    assert_eq!(delta.changed, ["Unmentioned.name"]);
    assert!(delta.affected.is_empty(), "nothing mentions that name");
    covered.extend(fired);

    // 3. All three kinds of change at once, on names the modules do mention.
    //    The affected set is written out in full here because it is the one
    //    assertion in this crate that a UTF-8 sort fails: `Pkg.𝒜` **before**
    //    `Pkg.ﬀ` (plan §7, U1).
    let mut moved = after.clone();
    moved.insert("Pkg.moved".to_owned(), "Somewhere.Else".to_owned());
    moved.remove("Pkg.aaa");
    moved.insert("Dep.gone".to_owned(), "Dep.Home".to_owned());
    let (fired, delta) = run_delta(&trees, "moved", &ir, moved, true, true);
    assert_eq!(delta.changed, ["Dep.gone", "Pkg.aaa", "Pkg.moved"]);
    assert_eq!(
        delta.affected,
        [
            "Pkg.Alpha".to_owned(),
            "Pkg.Zed".to_owned(),
            format!("Pkg.{ASTRAL}"),
            format!("Pkg.{LIGATURE}"),
        ],
        "the affected set is not in UTF-16 code unit order"
    );
    // Scanned in index order, so the witness list is not the sorted one.
    assert_eq!(
        delta
            .witnesses
            .iter()
            .map(|w| w.module.as_str())
            .collect::<Vec<_>>(),
        [
            "Pkg.Zed",
            "Pkg.Alpha",
            &format!("Pkg.{ASTRAL}"),
            &format!("Pkg.{LIGATURE}")
        ],
    );
    // `Pkg.Zed`'s tokens are `Pkg.aaa`, `Pkg.moved`, `aaa`, `moved` in UTF-16
    // order; both of the first two changed, and the first one is the witness.
    assert_eq!(delta.witnesses[0].name, "Pkg.aaa");
    covered.extend(fired);

    // 4. The delta with neither output file: the counts still come back.
    let mut again = after;
    again.insert("Pkg.moved".to_owned(), "Somewhere.Else".to_owned());
    let (fired, _) = run_delta(&trees, "no-outputs", &ir, again, false, false);
    covered.extend(fired);

    // 5. More than twenty changed names and more than twenty affected modules:
    //    the sample and the witness list are both capped, and the corpus's
    //    delta (3 changed names) reaches neither cap.
    let big = trees.path().join("ir-big");
    let mut modules = Vec::new();
    for i in 0..22 {
        let module: &'static str = Box::leak(format!("Pkg.M{i:02}").into_boxed_str());
        let name: &'static str = Box::leak(format!("Pkg.M{i:02}.d").into_boxed_str());
        modules.push(Synthetic {
            module,
            hash: "7777777777777777",
            imports: vec![],
            decls: vec![decl(name, "def", Some("`Everywhere.name`"), json!([]))],
        });
    }
    write_synthetic(&big, &modules, &[]);
    let big_site = trees.path().join("site-big");
    build_global(&GlobalOptions::new(&big, &big_site)).expect("builds");
    let mut before = name_map(&big_site);
    before.insert("Everywhere.name".to_owned(), "Gone.Away".to_owned());
    for i in 0..25 {
        before.insert(format!("Extra.n{i:02}"), "Gone.Away".to_owned());
    }
    let (fired, delta) = run_delta(&trees, "capped", &big, before, true, true);
    assert_eq!(delta.changed.len(), 26);
    assert_eq!(delta.affected.len(), 22);
    assert_eq!(
        delta.witnesses.len(),
        20,
        "the witness list is capped at 20"
    );
    covered.extend(fired);
    covered
}

/// Runs one delta over `ir` with `before` as the previous map.
#[expect(
    clippy::needless_pass_by_value,
    reason = "callers build the map for this call and have no use for it after"
)]
fn run_delta(
    trees: &TempDir,
    what: &str,
    ir: &Path,
    before: BTreeMap<String, String>,
    print_set: bool,
    delta_json: bool,
) -> (BTreeSet<&'static str>, Delta) {
    let before_path = trees.path().join(format!("{what}-before.json"));
    fs::write(
        &before_path,
        serde_json::to_string(&before).expect("serialises"),
    )
    .expect("writable");
    let site = trees.path().join(format!("{what}-site"));
    let set = trees.path().join(format!("{what}-set.txt"));
    let json = trees.path().join(format!("{what}-delta.json"));

    let mut options = GlobalOptions::new(ir, &site);
    options.before = Some(&before_path);
    options.print_set = print_set.then_some(set.as_path());
    options.delta_json = delta_json.then_some(json.as_path());
    let summary = build_global(&options).unwrap_or_else(|e| panic!("{what}: {e}"));
    let tree = IrTree::open(ir).expect("opens");
    let facts = facts_for(&tree, &State::empty()).expect("reads").facts;

    // The delta as data has to agree with the two files it wrote.
    let delta = summary.delta.as_ref().expect("--before turns the delta on");
    if print_set {
        let body = fs::read_to_string(&set).expect("the print set was written");
        assert_eq!(body, delta.print_set(), "{what}");
    }
    if delta_json {
        let record: Value =
            serde_json::from_str(&fs::read_to_string(&json).expect("the summary was written"))
                .expect("the summary is JSON");
        assert_eq!(record["affected"], json!(delta.affected.len()), "{what}");
        assert_eq!(record["changedNames"], json!(delta.changed.len()), "{what}");
        assert_eq!(
            record["affectedModules"],
            json!(delta.affected),
            "{what}: the summary and the print set name different modules"
        );
    }
    // The same answer, computed straight from the two maps: the file-driven
    // path and the library path cannot drift apart.
    let after = name_map(&site);
    assert_eq!(*delta, Delta::compute(&before, &after, &facts), "{what}");

    let fired = observe(&Run {
        options: &options,
        index: tree.index(),
        state_before: None,
        state_after: None,
        summary: &summary,
        facts: &facts,
        before_map: Some(&before),
    });
    (fired, delta.clone())
}

// ------------------------------------------------------------------- fixture

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct DeltaExpected {
    mutation: Mutation,
    before_names: usize,
    after_names: usize,
    changed_names: usize,
    changed_sample: Vec<String>,
    affected: usize,
    affected_modules: Vec<String>,
    witnesses: Vec<ExpectedWitness>,
    print_set_bytes: usize,
    print_set_fnv1a64: String,
    unchanged_print_set_bytes: usize,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Mutation {
    moved_name: String,
    moved_to: String,
    dropped_name: String,
    inserted_name: String,
    inserted_module: String,
}

#[derive(Deserialize)]
struct ExpectedWitness {
    module: String,
    name: String,
}

fn delta_fixture() -> DeltaExpected {
    serde_json::from_str(include_str!("data/delta-expected.json"))
        .expect("tests/data/delta-expected.json is valid")
}

/// The mutation was chosen by the generator to make the scan mean something:
/// three names, one of each kind, all of them mentioned by real docstrings.
#[test]
fn the_delta_fixture_is_a_real_delta() {
    let e = delta_fixture();
    assert!(
        e.changed_names > 0,
        "a delta with nothing changed proves nothing"
    );
    assert!(
        e.affected > 0,
        "a delta that affects nothing proves nothing"
    );
    assert_eq!(e.changed_sample.len(), e.changed_names.min(20));
    assert_eq!(e.affected, e.affected_modules.len());
    assert_eq!(e.witnesses.len(), 20.min(e.affected));
    assert!(
        e.affected > 20,
        "the corpus delta has to exceed the witness cap for the cap to be exercised"
    );
    assert_eq!(e.unchanged_print_set_bytes, 0);
    assert_ne!(e.mutation.moved_name, e.mutation.dropped_name);
}

// ------------------------------------------------------------------- helpers

/// The generated IR of the target package, or a panic naming what to set.
///
/// Every caller is `#[ignore]`d, so reaching this function at all means the
/// corpus gate asked for the test by name. Returning "not here, never mind"
/// there would be a green result for a comparison that never ran.
fn corpus_ir() -> PathBuf {
    corpus::LITEDOC4_IR.path()
}

/// The reference tree the frozen prototype wrote, or a panic naming what to set.
fn corpus_reference() -> PathBuf {
    corpus::LITEDOC4_REFERENCE_GLOBAL.path()
}
