#!/usr/bin/env bash
# Build `lean_exe litedoc4` the way a consumer builds it, and print where it landed.
#
# Lake cannot run beside this repository's own `lakefile.lean`: there is
# deliberately no `lean-toolchain` there, because one that named a *higher*
# version would rewrite a consumer's own file on `lake update` and a *lower* one
# would be ignored without a warning (measured 2026-08-18 →
# `benchmarks/results/lake-package-probe-2026-08-18.txt` §1). So the only way to
# build this package is from a workspace that requires it, and this script writes
# the smallest such workspace: one `[[require]]` and a `lean-toolchain` copied
# from the package the caller names.
#
# **The toolchain is copied, not pinned here.** The executable a consumer runs is
# compiled by *their* Lean, so the honest thing to compile it with is theirs; a
# version of our own would also make elan fetch a second toolchain nobody asked
# for.
#
# The workspace goes under `<repo>/.lake/host` rather than a temporary directory
# so that one cache path (`<repo>/.lake`) holds both it and the build output.
# Restoring one without the other makes Lake re-resolve and rebuild everything,
# which is the cost a cache is there to avoid.
#
# usage: build-lean-exe.sh --toolchain-from <lean package> [--lake <path>]
#
#   --toolchain-from <dir>  the package whose `lean-toolchain` compiles this
#                           (required). Nothing else is read from it.
#   --lake <path>           the lake executable (default: $LAKE, else `lake`)
#
# Prints the path to the executable on stdout, and nothing else — the Lake build
# log goes to stderr, so a caller can take `$(build-lean-exe.sh …)` directly.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FROM=""
LAKE="${LAKE:-lake}"

while [ $# -gt 0 ]; do
  case "$1" in
    --toolchain-from) FROM="$2"; shift 2 ;;
    --lake) LAKE="$2"; shift 2 ;;
    -h|--help) sed -n '/^# usage:/,/^set -euo/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//;$d'; exit 0 ;;
    *) echo "unknown argument: $1 (see --help)" >&2; exit 2 ;;
  esac
done

[ -n "$FROM" ] || { echo "--toolchain-from <lean package> is required" >&2; exit 2; }
[ -d "$FROM" ] || { echo "no such package: $FROM" >&2; exit 1; }
FROM="$(cd "$FROM" && pwd)"

HOST="$REPO/.lake/host"
mkdir -p "$HOST"
if [ -f "$FROM/lean-toolchain" ]; then
  cp "$FROM/lean-toolchain" "$HOST/lean-toolchain"
else
  # Not an error: a package without the file takes elan's default, and so does
  # this. Said out loud because "which Lean compiled it" is the question this
  # script exists to answer.
  echo "no $FROM/lean-toolchain; the build takes elan's default toolchain" >&2
  rm -f "$HOST/lean-toolchain"
fi

cat > "$HOST/lakefile.toml" <<TOML
# Generated by tools/build-lean-exe.sh. The only package here is the require
# below: it exists so that Lake has a root to build litedoc4 from.
name = "litedoc4host"

[[require]]
name = "«litedoc4»"
path = "$REPO"
TOML

(cd "$HOST" && "$LAKE" build litedoc4/litedoc4) >&2

BIN="$REPO/.lake/build/bin/litedoc4"
# Lake exiting 0 having written nothing is the shape this repository keeps
# catching, so the filesystem is asked rather than the exit code.
[ -x "$BIN" ] || { echo "lake build litedoc4/litedoc4 exited 0 but there is no $BIN" >&2; exit 1; }
echo "$BIN"
