#!/usr/bin/env python3
"""Carry `fixtures/md/*-expected.json` into `test/Litedoc4Test/MdOracleCases.lean`.

The two fixtures hold answers minted outside the Lean half — MD4Lean's own parse
trees, and the HTML the doc-gen4 transcription produced when the oracle was last
asked. An invariant that reads them has to hold its own input (a test depends on
zero hardware and no cwd), and Lean has no `include_str!`, so the corpora are
written into a generated module the way `tools/gen-assets.py` writes `assets/`
into `src/Litedoc4/Assets.lean`.

usage: tools/gen-md-oracle-cases.py [--check]

  --check   generate into memory and compare against the file on disk, without
            writing. Non-zero when they differ. This is what the gate runs.

THE CANONICAL AST ENCODING
--------------------------
`md4lean-expected.json`'s `ast` is a tagged-array tree (`tools/oracle/dump-ast.lean`
defines it). It is carried here as one string per case, serialised by
`json.dumps(ast, ensure_ascii=False, separators=(",", ":"))`, which is: no
whitespace; `"` `\\` `\\b` `\\f` `\\n` `\\r` `\\t` escaped as themselves, every other
code point below U+0020 as `\\u00xx` in lowercase hex, and everything from U+0020
up written out raw as UTF-8. `Litedoc4Test.encDocument` is the Lean side of that
same encoding, and the invariant compares the two strings.

THE LEAN LITERAL ESCAPES, AND WHY THIS LIST AND NOT A LONGER ONE
----------------------------------------------------------------
Measured 2026-09-02 against the toolchain `e2e/micro` pins, by compiling each
spelling and printing `String.toUTF8` back
(→ `benchmarks/results/lean-string-escapes-2026-09-02.txt`):

    \\\\ \\" \\xHH (exactly two digits, greedy no further)   round-trip
    a code point from U+0020 up, written out raw           round-trip,
                                                           astral included
    \\uD83D\\uDE00 (a surrogate pair, as JSON spells it)      COMPILES, and
                                                           yields two NUL bytes

The last line is why this generator refuses a surrogate rather than encoding it:
Lean accepts the spelling and silently produces the wrong bytes, which is the
shape where the output and the exit code disagree. Anything else unmeasured stops
the generator too.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCGEN4 = ROOT / "fixtures" / "md" / "docgen4-expected.json"
MD4LEAN = ROOT / "fixtures" / "md" / "md4lean-expected.json"
OUT = ROOT / "test" / "Litedoc4Test" / "MdOracleCases.lean"


def literal(where, s):
    """`s` as a Lean string literal, including the quotes."""
    out = ['"']
    for offset, char in enumerate(s):
        code = ord(char)
        if char == "\\":
            out.append("\\\\")
        elif char == '"':
            out.append('\\"')
        elif code < 0x20 or code == 0x7F:
            out.append("\\x%02x" % code)
        elif 0xD800 <= code <= 0xDFFF:
            sys.exit(
                f"{where}: surrogate U+{code:04X} at offset {offset}. Lean spells "
                f"`\\uD800` without complaining and hands back a NUL byte, so this "
                f"cannot be encoded on a guess."
            )
        else:
            out.append(char)
    out.append('"')
    return "".join(out)


def canonical(ast):
    return json.dumps(ast, ensure_ascii=False, separators=(",", ":"))


def read_fixture(path):
    if not path.is_file():
        sys.exit(f"{path.relative_to(ROOT)} is not there; the corpora it carries cannot be generated")
    cases = json.loads(path.read_text(encoding="utf-8")).get("cases")
    if not cases:
        sys.exit(f"{path.relative_to(ROOT)} holds no cases; an empty corpus is 0 of 0 agreeing")
    return cases


def generate():
    docgen4 = {"cases": read_fixture(DOCGEN4)}
    md4lean = {"cases": read_fixture(MD4LEAN)}

    out = [
        "/- Generated by `tools/gen-md-oracle-cases.py` from\n",
        "`fixtures/md/docgen4-expected.json` and `fixtures/md/md4lean-expected.json`.\n",
        "Do not edit.\n",
        "\n",
        "`test/Litedoc4Test/MdOracle.lean` is the reader, and it is where the sizes\n",
        "these arrays have to keep are written down: a count generated from the same\n",
        "fixture as the cases would shrink along with them. -/\n",
        "\n",
        "namespace Litedoc4Test\n",
        "\n",
        "/-- `(what, root, md, html)`. `html` is what `docstring` has to produce for\n",
        "`md` under that case's `root` and `MdOracle.docGen4EmptyAnalyzer`. -/\n",
        "def docgen4OracleCases : Array (String × String × String × String) := #[\n",
    ]
    rows = []
    for case in docgen4["cases"]:
        where = f"docgen4 {case['what']!r}"
        rows.append(
            "  ("
            + literal(where, case["what"])
            + ", "
            + literal(where, case["root"])
            + ",\n   "
            + literal(where, case["md"])
            + ",\n   "
            + literal(where, case["html"])
            + ")"
        )
    out.append(",\n".join(rows))
    out.append("]\n\n")

    out.append(
        "/-- `(what, flags, md, astJson)`. `astJson` is MD4Lean's own tree for `md`\n"
        "under `flags`, in the encoding `encDocument` writes. The flags are per case:\n"
        "the corners the docstring dialect cannot reach were answered by MD4Lean under\n"
        "other flags rather than by hand. -/\n"
        "def md4leanOracleCases : Array (String × UInt32 × String × String) := #[\n"
    )
    rows = []
    for case in md4lean["cases"]:
        where = f"md4lean {case['what']!r}"
        rows.append(
            "  ("
            + literal(where, case["what"])
            + ", "
            + str(case["flags"])
            + ",\n   "
            + literal(where, case["md"])
            + ",\n   "
            + literal(where, canonical(case["ast"]))
            + ")"
        )
    out.append(",\n".join(rows))
    out.append("]\n\n")
    out.append("end Litedoc4Test\n")
    return "".join(out)


def main(argv):
    check = False
    for arg in argv[1:]:
        if arg == "--check":
            check = True
        else:
            sys.exit(f"usage: gen-md-oracle-cases.py [--check]\nunknown argument `{arg}`")

    fresh = generate()
    if not check:
        OUT.write_text(fresh, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)} ({len(fresh.encode('utf-8'))} B)")
        return 0

    if not OUT.exists():
        sys.exit(f"{OUT.relative_to(ROOT)} does not exist; run tools/gen-md-oracle-cases.py")
    on_disk = OUT.read_text(encoding="utf-8")
    if on_disk == fresh:
        print(
            f"{OUT.relative_to(ROOT)} is what fixtures/md/ generates "
            f"({len(fresh.encode('utf-8'))} B)"
        )
        return 0

    fresh_lines, disk_lines = fresh.splitlines(), on_disk.splitlines()
    where = f"{len(disk_lines)} lines on disk, {len(fresh_lines)} generated"
    for i, (a, b) in enumerate(zip(fresh_lines, disk_lines), 1):
        if a != b:
            where = f"line {i} differs ({len(b)} chars on disk, {len(a)} generated)"
            break
    sys.exit(
        f"{OUT.relative_to(ROOT)} is not what fixtures/md/ generates: {where}.\n"
        f"Run tools/gen-md-oracle-cases.py."
    )


if __name__ == "__main__":
    sys.exit(main(sys.argv))
