#!/usr/bin/env python3
"""Embed `assets/` into `src/Litedoc4/Assets.lean` as Lean string literals.

The Rust half reaches these files with `include_str!`; Lean has no equivalent,
so the bytes are written into a generated module. Measured 2026-08-31
(`benchmarks/results/purelean-assets-literal-2026-08-31.txt`): a 29 KB literal
parses, compiles and round-trips byte for byte, and rebuilding the module costs
under half a second.

usage: tools/gen-assets.py [--check]

  --check   generate into memory and compare against the file on disk, without
            writing. Non-zero when they differ. This is what the gate runs.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "Litedoc4" / "Assets.lean"

# `themeBootJs` is last and deliberately outside `assets` below: `frame.rs`
# inlines it into every page's `<head>` rather than writing it as a file, so it
# is an asset of the binary and not of the site.
SOURCES = [
    ("styleCss", "style.css", True),
    ("appJs", "app.js", True),
    ("faviconSvg", "favicon.svg", True),
    ("themeBootJs", "theme-boot.js", False),
]


def escape(name, body):
    """Escape for a Lean string literal.

    Two characters, because that is what these four files need (measured): no
    CR and no control character other than newline and tab. A file that later
    carries one stops the generator rather than being encoded on a guess —
    Lean's `\\x` and `\\u` escapes have not been measured here, and inventing an
    encoding that is wrong produces a site whose CSS is subtly not the CSS.
    """
    for offset, char in enumerate(body):
        code = ord(char)
        if (code < 0x20 and char not in "\n\t") or code == 0x7F:
            sys.exit(
                f"{name}: control character U+{code:04X} at offset {offset}. "
                f"The generator escapes only `\\` and `\"`; measure how Lean "
                f"spells this one before extending it."
            )
    return body.replace("\\", "\\\\").replace('"', '\\"')


def generate():
    out = [
        "/- Generated by `tools/gen-assets.py` from `assets/`. Do not edit.\n",
        "\n",
        "The site's static files, carried in the binary rather than shipped beside\n",
        "it, so they cannot be a version behind the renderer that names their\n",
        "classes. -/\n",
        "\n",
        "namespace Litedoc4\n",
        "\n",
    ]
    for ident, filename, _ in SOURCES:
        body = (ROOT / "assets" / filename).read_text(encoding="utf-8")
        out.append(f"def {ident} : String :=\n  \"{escape(filename, body)}\"\n\n")

    listed = ", ".join(
        f'("{filename}", {ident})' for ident, filename, in_site in SOURCES if in_site
    )
    out.append(
        "/-- Each asset's path **under the site root**, paired with its bytes.\n"
        "The paths are flat, relative and `/`-separated because they are URLs a\n"
        "page asks for, not filesystem paths. -/\n"
        f"def assets : Array (String × String) :=\n  #[{listed}]\n\n"
    )
    out.append("end Litedoc4\n")
    return "".join(out)


def main(argv):
    check = False
    for arg in argv[1:]:
        if arg == "--check":
            check = True
        else:
            sys.exit(f"usage: gen-assets.py [--check]\nunknown argument `{arg}`")

    fresh = generate()
    if not check:
        OUT.write_text(fresh, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)} ({len(fresh.encode('utf-8'))} B)")
        return 0

    if not OUT.exists():
        sys.exit(f"{OUT.relative_to(ROOT)} does not exist; run tools/gen-assets.py")
    on_disk = OUT.read_text(encoding="utf-8")
    if on_disk == fresh:
        print(f"{OUT.relative_to(ROOT)} is what assets/ generates ({len(fresh.encode('utf-8'))} B)")
        return 0

    # Named by line, not by a diff: the bodies are one line each and up to
    # 29 KB, so a line-level diff prints the whole stylesheet.
    fresh_lines, disk_lines = fresh.splitlines(), on_disk.splitlines()
    where = "line count differs"
    for i, (a, b) in enumerate(zip(fresh_lines, disk_lines), 1):
        if a != b:
            where = f"line {i} differs ({len(b)} chars on disk, {len(a)} generated)"
            break
    sys.exit(
        f"{OUT.relative_to(ROOT)} is not what assets/ generates: {where}.\n"
        f"Run tools/gen-assets.py."
    )


if __name__ == "__main__":
    sys.exit(main(sys.argv))
